<?php
/** Long-form guide content, batch 7. See content-long-1.php for the shape. */
if (!defined('ABSPATH')) exit;

return [
    'Specialised driver training' => [
        'cat' => '',
        'short' => 'Specialised driver training is assessment and lessons for people with a disability, including learning to drive with adaptive controls or in a modified vehicle. It usually starts with an assessment by a qualified professional.',
        'overview' => "Driving can bring independence, but disability can affect the skills driving needs, such as vision, reaction time, movement and attention. A specialised driver assessment looks at whether and how you can drive safely, and recommends any equipment or training you need. It is usually carried out by an occupational therapist with additional driver assessment training, sometimes together with a driving instructor.\n\nTraining follows the assessment. Specialist driving instructors teach in vehicles fitted with dual controls and adaptive equipment such as hand controls, steering aids or modified pedals. They help you learn to use the equipment and to drive safely in real traffic.\n\nLicensing and vehicle rules vary between states, and modifications need to meet standards and be approved. Ask the assessor and instructor what applies where you live, and plan for the time it can take to complete assessment, training and any vehicle changes.",
        'choose' => [
            'Ask about the qualifications and experience of the assessor and instructor.',
            'Check that lessons are in a suitable vehicle with the right controls.',
            'Ask what the assessment involves and how results are shared.',
            'Find out how the process links to licensing requirements in your state.',
            'Ask how they help with vehicle modifications.',
        ],
        'start' => [
            'Talk to your doctor about driving and your health.',
            'Book a driver assessment with a qualified professional.',
            'Follow the recommendations for training and equipment.',
            'Check licensing and vehicle requirements with the relevant authority.',
        ],
        'faq' => [
            ['Do I need an assessment before I learn?', 'Usually yes, to check what equipment and training suit you.'],
            ['Can I learn to drive if I use a wheelchair?', 'Many people do, with suitable vehicle modifications. An assessment can advise.'],
            ['Who decides whether I can hold a licence?', 'Licensing is decided by the relevant state or territory authority. The assessment provides information.'],
        ],
    ],
    'Specialised transport' => [
        'cat' => 'Transport',
        'short' => 'Specialised transport is transport in a vehicle suited to your needs, for example one with a wheelchair lift, or with a driver trained to help you get in and out.',
        'overview' => "For some people, a standard taxi or car is not an option. Specialised transport provides vehicles that are accessible, such as vans with lifts and secure wheelchair fittings, and drivers who are trained to assist with transfers, restraints and any additional needs.\n\nServices vary. Some transport people to appointments, activities and social events, while others run regular routes for programs. Bookings may need to be made in advance, and some services are limited by area and hours.\n\nWhen choosing, ask about the vehicles and how equipment is secured, the training and screening of drivers, how bookings and changes work and what happens if a vehicle is delayed. Check whether an assistant travels with you if you need one, and whether trips are shared with others.",
        'choose' => [
            'Ask about the vehicle and how your equipment is secured.',
            'Find out how drivers are trained and screened.',
            'Check how bookings, changes and cancellations work.',
            'Ask about service areas and hours.',
            'Find out whether trips are shared and how long they can take.',
        ],
        'start' => [
            'Write down where and when you need to travel.',
            'Contact providers and ask about vehicles and availability.',
            'Book a trial trip if you can.',
            'Agree how regular trips will be arranged.',
        ],
        'faq' => [
            ['Can I bring my own wheelchair?', 'Yes, in most cases. Tell the provider the type of chair when you book.'],
            ['Can a support worker travel with me?', 'Often yes. Ask the provider about seating and any rules.'],
            ['What if I need to change my booking?', 'Check notice periods in the service agreement.'],
        ],
    ],
    'Specialist Disability Accommodation (SDA)' => [
        'cat' => 'Housing (SDA & SIL)',
        'short' => 'Specialist Disability Accommodation is housing with special design features for people with very high support needs or extreme functional impairment. It covers the building, not the support services delivered inside it.',
        'overview' => "SDA homes are designed and built to a higher standard than ordinary housing. Features can include wider doorways, reinforced ceilings for hoists, accessible bathrooms and kitchens, and smart technology or robust construction for people who need it. The design aims to make it easier for residents to live safely and independently.\n\nThe housing and the support are separate. SDA is the home. Support services, such as personal care and help with daily tasks, are provided by a support provider, and a person can choose the provider that works for them. Some people have both SDA and Supported Independent Living, but they are different things.\n\nSDA is intended for a small number of people. Eligibility is decided against specific criteria and needs supporting evidence, often from an occupational therapist. If you are thinking about SDA, talk to your planner or support coordinator early, and ask about the design categories and locations available.",
        'choose' => [
            'Ask an occupational therapist to assess whether SDA might suit you.',
            'Visit homes and check the design features against your needs.',
            'Ask how the housing provider and support provider work together.',
            'Check location, including access to transport, shops and family.',
            'Ask about the agreement, including rights and how to end it.',
        ],
        'start' => [
            'Talk to your planner or support coordinator about whether SDA may be an option.',
            'Gather evidence of your support needs with your therapists.',
            'Explore available homes and providers.',
            'Understand the agreement before you sign.',
        ],
        'faq' => [
            ['Do I have to use the same organisation for housing and support?', 'No. You can choose your support provider separately.'],
            ['Can I live with someone I choose?', 'Ask the housing provider what is possible in the home you are interested in.'],
            ['How do I find out if I am eligible?', 'Talk to your planner or support coordinator. Eligibility is assessed against specific criteria.'],
        ],
    ],
    'Specialist Positive Behaviour Support' => [
        'cat' => 'Behaviour support',
        'short' => 'A specialist practitioner works to understand the reasons behind behaviours of concern and develops a positive behaviour support plan focused on the person\'s needs and quality of life.',
        'overview' => "Behaviours of concern, such as aggression, self-injury or withdrawal, often have a reason. They may be a way of communicating, a response to pain, stress or an environment that does not suit, or the result of unmet needs. Positive behaviour support looks for the reasons and focuses on meeting the person's needs.\n\nA behaviour support practitioner assesses the person, observes them in different settings and talks with the people who know them. They then write a plan that explains the reasons and sets out strategies, such as changes to the environment, teaching new skills and ways to respond that keep everyone safe. The plan is reviewed as needs change.\n\nBehaviour support practitioners must meet requirements set by the NDIS Commission, and there are rules about the use of restrictive practices. Ask about their approach, how they involve the person and family and how they work with the people who will put the plan into practice.",
        'choose' => [
            'Ask about the practitioner\'s qualifications and experience.',
            'Find out how they involve the person and the people who know them best.',
            'Check how they will work with the workers who implement the plan.',
            'Ask how they handle restrictive practices and oversight.',
            'Ask how the plan will be reviewed.',
        ],
        'start' => [
            'Talk to your planner or support coordinator about behaviour support.',
            'Contact practitioners and ask about their approach.',
            'Share information about the behaviours, when they occur and what has been tried.',
            'Agree how the plan will be shared and reviewed.',
        ],
        'faq' => [
            ['Is positive behaviour support about punishment?', 'No. It focuses on understanding the reasons and meeting needs, not punishment or control.'],
            ['Who writes the plan?', 'A behaviour support practitioner, with input from the person and those around them.'],
            ['Can family be involved?', 'Yes. Family knowledge is valuable, and consistency helps.'],
        ],
        'src' => ['ndiscommission'],
    ],
    'Specialist Support Coordination (Level 3)' => [
        'cat' => 'Support coordination',
        'short' => 'Specialist support coordination is a higher level of support coordination for people in complex situations, who need extra help to resolve barriers and get supports working together.',
        'overview' => "Some people face complex circumstances, such as a risk of homelessness, conflict between services, multiple health and disability needs or difficulty getting supports in place. Specialist support coordinators work with these situations. They help resolve barriers, manage risks and get different services to work together.\n\nThe coordinator usually takes an active role for a period, focusing on stabilising the situation and building the person's capacity and their network of supports. As things settle, a lower level of coordination may be enough. The goal is not to replace other supports, but to help make them work.\n\nBecause the situations are complex, experience matters. Ask about their background, how they work with clinicians and other services and how they measure success. You may also want to ask how they will keep you informed and involved throughout.",
        'choose' => [
            'Ask about experience with complex situations like yours.',
            'Find out how they work with health, housing and other services.',
            'Check how they communicate with you and your family.',
            'Ask how they measure progress and when support is expected to reduce.',
            'Ask about their availability and how urgent matters are handled.',
        ],
        'start' => [
            'Talk to your planner about whether this support fits your situation.',
            'Gather information about your current supports and challenges.',
            'Meet a few coordinators and choose someone you trust.',
            'Agree goals and how you will review them.',
        ],
        'faq' => [
            ['How is this different from ordinary support coordination?', 'It is intended for complex situations and involves more intensive work to resolve barriers.'],
            ['Is it long-term?', 'Often it is for a defined period, with the aim of stabilising the situation.'],
            ['Can I change my specialist coordinator?', 'Yes. Check the agreement for notice.'],
        ],
    ],
    'Speech pathology' => [
        'cat' => 'Therapy services',
        'short' => 'Speech pathologists assess and treat difficulties with speaking, understanding, communication, and with eating and swallowing. They work with people of all ages.',
        'overview' => "Communication and swallowing are complex skills. Speech pathologists help children learning to talk, people who stutter, adults recovering from stroke, people with communication disability who use devices and people with difficulty eating or drinking safely.\n\nAn assessment looks at how you communicate or swallow and what is getting in the way. Therapy may involve exercises, strategies, working with family and carers, setting up communication systems and giving advice on safe eating. Speech pathologists often work with other professionals, such as dietitians and occupational therapists.\n\nLook for a speech pathologist who is a Certified Practising Speech Pathologist through Speech Pathology Australia, and ask about experience with your situation. Sessions can be at a clinic, at home, at school or by video.",
        'choose' => [
            'Ask whether they are a Certified Practising Speech Pathologist.',
            'Check their experience with your age group and needs.',
            'Ask how they involve family and other supporters.',
            'Find out where sessions can take place.',
            'Ask how they set goals and review progress.',
        ],
        'start' => [
            'Note the difficulties you or your child have.',
            'Contact speech pathologists and describe your situation.',
            'Book an assessment and ask what it involves.',
            'Practise the strategies between sessions.',
        ],
        'faq' => [
            ['Do I need a referral to see a speech pathologist?', 'Often not, though check with the practice.'],
            ['Can speech pathology help with eating and swallowing?', 'Yes. Speech pathologists assess and treat swallowing difficulties.'],
            ['Can it help adults?', 'Yes. They work with adults after stroke, brain injury and with many conditions.'],
        ],
    ],
    'Study and learning skills' => [
        'cat' => 'Life skills',
        'short' => 'Study and learning skills support helps students build skills for learning, such as planning, note-taking, time management and confidence.',
        'overview' => "Learning is easier with good strategies. Study skills support helps with planning your week, breaking assignments into steps, taking notes, revising for tests, staying motivated and dealing with stress. For students with disability, it can also involve learning to use assistive technology and to ask for the adjustments they need.\n\nSupport can come from tutors, therapists and specialist coaches. It might be one-to-one or in a small group, at school, at home or online. The best approach depends on how you learn, so look for someone who takes the time to understand your strengths and challenges.\n\nThe same skills help at school, in vocational study, at university and in adult learning. Building them early gives a foundation for later study and work, and can make a big difference to confidence.",
        'choose' => [
            'Ask how they find out how you learn best.',
            'Check their experience with students with disability.',
            'Ask whether they can support the use of assistive technology.',
            'Find out how they work with your school or education provider.',
            'Ask how progress will be measured.',
        ],
        'start' => [
            'Think about which study tasks are hardest.',
            'Talk to your teachers or disability service.',
            'Find a tutor or coach with the right experience.',
            'Set goals and review them regularly.',
        ],
        'faq' => [
            ['Can this help with exams?', 'Yes. Support can include revision strategies and managing exam stress.'],
            ['Is this the same as tutoring?', 'Tutoring focuses on a subject, while study skills support focuses on how you learn.'],
            ['Can it be done online?', 'Often yes. Many tutors and coaches work online, so ask providers whether they offer it.'],
        ],
    ],
    'Support Connection (Level 1)' => [
        'cat' => 'Support coordination',
        'short' => 'Support connection is help to understand your plan and connect with providers and community services, without ongoing coordination.',
        'overview' => "When a plan is new or complex, knowing where to start can be hard. Support connection gives you a short period of help to understand what is in your plan and to find and link with the providers and community services that can deliver your supports.\n\nIt is lighter than support coordination. There is no ongoing case management, and the focus is on getting you started and building your confidence to manage on your own. For some people that is all they need.\n\nIf you find you need more help later, such as managing several providers or resolving problems, a higher level of coordination may be a better fit. Ask your planner or a coordinator to talk through what suits you.",
        'choose' => [
            'Ask how they will help you understand your plan.',
            'Find out how they help you find and compare providers.',
            'Check how they will build your confidence to manage on your own.',
            'Ask about how long the support usually lasts.',
            'Ask how you can get more help if you need it later.',
        ],
        'start' => [
            'Read your plan and note the supports you want to set up.',
            'Contact coordinators and ask what they offer.',
            'Agree what you want to achieve.',
            'Review after the support ends and ask for more help if needed.',
        ],
        'faq' => [
            ['What is the difference from support coordination?', 'Support connection is shorter and lighter. Support coordination involves more ongoing help.'],
            ['Can I move to support coordination later?', 'Talk to your planner about changing the support if your needs change.'],
            ['Do I need it?', 'It can help if you are new to the NDIS or unsure where to begin.'],
        ],
    ],
    'Support Coordination (Level 2)' => [
        'cat' => 'Support coordination',
        'short' => 'A support coordinator helps you put your plan into action: finding providers, setting up services, understanding your budget and building your ability to manage your supports.',
        'overview' => "Turning an NDIS plan into real supports takes work. A support coordinator helps you understand your plan, find providers that suit you, arrange service agreements and keep everything running. Over time they aim to build your skills and confidence so you can manage more yourself.\n\nCoordinators do not make decisions for you. They explain options, help you compare providers and speak up with you when things go wrong. They can also help you prepare for plan reviews and gather evidence.\n\nBecause a coordinator can influence which providers you use, it is worth asking how they handle conflicts of interest. A good coordinator is transparent about any relationships with providers, presents a range of options and puts your goals first.",
        'choose' => [
            'Ask about their experience with people like you.',
            'Find out how they handle conflicts of interest.',
            'Check how often you will hear from them and how you contact them.',
            'Ask how they help you build your own skills.',
            'Ask how they help with plan reviews.',
        ],
        'start' => [
            'Read your plan and list your goals.',
            'Meet a few coordinators and choose one you trust.',
            'Agree what they will help with and how you will work together.',
            'Review regularly and change coordinator if it is not working.',
        ],
        'faq' => [
            ['Does my coordinator choose my providers?', 'No. They help you compare options, but you decide.'],
            ['Can I change coordinator?', 'Yes. Check the agreement for notice.'],
            ['Can a coordinator help me at plan review?', 'Yes. They can help you prepare and provide information.'],
        ],
    ],
    'Supported Independent Living (SIL)' => [
        'cat' => 'Housing (SDA & SIL)',
        'short' => 'Supported Independent Living is help with daily tasks in a shared home, so a person can live as independently as possible. It covers the support provided, not the housing itself.',
        'overview' => "SIL supports people who need regular help with tasks such as personal care, meals, household jobs and getting out and about, and who live in a shared home. The support is designed to build independence, not to do everything for the person, and it can include overnight support.\n\nSIL is separate from the housing. A person might live in a home they rent, a home owned by the provider or Specialist Disability Accommodation, and the support provider delivers the support. The aim is that residents choose who they live with and who supports them.\n\nChoosing a SIL provider is an important decision. Visit homes, meet staff and housemates and ask how decisions are made in the home. Ask about the roster, how staff are trained and how you can change or end the arrangement if it is not working.",
        'choose' => [
            'Visit the home and meet staff and housemates.',
            'Ask how the provider decides who lives together.',
            'Check how you have a say in decisions about the home.',
            'Ask about staffing, training and the roster.',
            'Understand how the arrangement can be changed or ended.',
        ],
        'start' => [
            'Talk to your planner or support coordinator about whether SIL is right.',
            'Compare providers and visit homes.',
            'Discuss what a typical day would look like.',
            'Agree the arrangement and plan how it will be reviewed.',
        ],
        'faq' => [
            ['Can I choose my housemates?', 'You should have a say. Ask how the provider handles this.'],
            ['Is SIL the same as SDA?', 'No. SIL is support; SDA is housing.'],
            ['What if I want to move?', 'Ask about notice and how a move would be planned.'],
        ],
    ],
    'Supported employment' => [
        'cat' => 'Employment & education support',
        'short' => 'Supported employment is ongoing support in a workplace for people who need it to keep working, delivered by a provider working alongside the employer and the person.',
        'overview' => "Supported employment gives people who need ongoing help the chance to hold a paid job. Support is built into the job, and might include supervision, adapted tasks, extra training and regular check-ins. It can be provided in a workplace run by a disability enterprise, or alongside an employer in the open workforce.\n\nWork arrangements vary. Wages and conditions depend on the workplace and the industrial arrangements that apply, and some people have their pay set with the help of a supported wage assessment. It is important to ask how wages are assessed and reviewed before you accept a role.\n\nThe right job is one you find meaningful and can do well with the support you need. Ask providers about the work on offer, how they match people to jobs and how support will change over time, including whether there are pathways to other kinds of work if you want them.",
        'choose' => [
            'Ask about the types of work and how you are matched to a role.',
            'Find out how wages are assessed and reviewed.',
            'Check how much support is provided and by whom.',
            'Ask about pathways to other work if you want to change.',
            'Ask how they involve you in decisions about your job.',
        ],
        'start' => [
            'Think about the work you would like to do.',
            'Speak to your planner or employment provider about supported employment.',
            'Visit workplaces and try tasks if you can.',
            'Ask questions about pay and conditions before you agree.',
        ],
        'faq' => [
            ['Is supported employment paid work?', 'Yes. Ask about how wages are set.'],
            ['Can I move to open employment later?', 'Some people do. Ask providers about pathways.'],
            ['Where can I get advice on workplace rights?', 'Government services and advocacy organisations provide information.'],
        ],
        'src' => ['jobaccess'],
    ],
];
