<?php
/** Long-form guide content, batch 6. See content-long-1.php for the shape. */
if (!defined('ABSPATH')) exit;

return [
    'Psychosocial Recovery Coaching' => [
        'cat' => 'Support coordination',
        'short' => 'A psychosocial recovery coach supports people with psychosocial disability to set goals, build skills, connect with services and take part in daily life and the community on their own terms.',
        'overview' => "Psychosocial disability can arise from a mental health condition and can affect how a person manages everyday activities, relationships and taking part in the community. Recovery, in this context, is not about being cured. It is about living a life that has meaning to you, with the supports you need.\n\nA recovery coach works alongside you. They help you work out what matters, set goals and take steps towards them. They can help you build skills, connect with services and community groups, and make sense of your plan and the supports available. The relationship is built on trust, and the coach respects your choices and pace.\n\nRecovery coaching overlaps with support coordination, but the emphasis is on your personal recovery goals and on building your capacity. Ask providers about their approach, how they involve you in decisions and how they work with your other supports, such as clinicians and family.",
        'choose' => [
            'Ask about the coach\'s experience with psychosocial disability and lived experience.',
            'Find out how they help you set goals and review progress.',
            'Check how they work with your clinicians, family and other supports.',
            'Ask how they handle difficult times, including when you are unwell.',
            'Ask how flexible appointments are and where they take place.',
        ],
        'start' => [
            'Think about what recovery means for you and what you would like to work towards.',
            'Talk to your planner or support coordinator about whether this support is in your plan.',
            'Meet a few coaches and choose someone you feel comfortable with.',
            'Set a small first goal and review it together.',
        ],
        'faq' => [
            ['What does psychosocial disability mean?', 'A disability that can arise from a mental health condition. It affects how a person manages daily activities, relationships and participation.'],
            ['Is a recovery coach a therapist?', 'No. A coach supports goals, skills and connections, while therapy is provided by clinicians such as psychologists.'],
            ['Can my family take part in my recovery goals?', 'Yes, if you want them to be. Discuss with your coach how family and friends can support you.'],
        ],
    ],
    'Recreation equipment' => [
        'cat' => 'Assistive technology & equipment',
        'short' => 'Recreation equipment lets you take part in sport, hobbies and leisure, and includes adapted bikes, sports wheelchairs and specialised gear for a particular activity.',
        'overview' => "Being active and doing things you enjoy is important for health and wellbeing. Recreation equipment removes barriers to taking part. Examples include hand cycles and adapted bikes, sports wheelchairs, adaptive skis and paddles, adapted fishing gear, and accessories that make it easier to hold, grip or balance.\n\nThe right equipment depends on the activity, your abilities and where you will use it. A therapist, sporting organisation or specialist supplier can advise, and many clubs run come-and-try days where you can test equipment before committing. This is a good way to find out whether an activity suits you.\n\nSome sports have specific equipment standards, so check with the sport if you plan to compete. Ask about fitting, training and maintenance, and think about how you will store and transport equipment.",
        'choose' => [
            'Try equipment at a come-and-try day or with a specialist supplier.',
            'Ask a therapist to check fit and safety.',
            'Check whether the equipment meets the requirements of your sport.',
            'Ask about servicing, spare parts and warranty.',
            'Think about storage and transport.',
        ],
        'start' => [
            'Choose an activity you want to try.',
            'Contact a local club or specialist supplier.',
            'Try equipment before buying.',
            'Arrange training and a maintenance plan.',
        ],
        'faq' => [
            ['Where can I try adaptive sports?', 'Local clubs, sporting organisations and disability sport groups run trial sessions.'],
            ['Is recreation equipment expensive?', 'It can be. Try before you buy, and ask suppliers about second-hand options.'],
            ['Can children use adapted sports equipment?', 'Yes. Equipment can be sized and adjusted for children, and they grow, so reviews are important.'],
        ],
    ],
    'Recurring transport allowance' => [
        'cat' => 'Transport',
        'short' => 'A recurring transport allowance is a regular allowance related to travel for people who cannot use public transport because of their disability. How it works is set out in the person\'s plan.',
        'overview' => "Getting around can be one of the biggest costs for people who cannot use public transport. Instead of paying for each trip through a provider, some plans include an allowance that covers ongoing travel needs. This gives flexibility, because you can choose how to travel, whether by taxi, rideshare, your own vehicle or a combination.\n\nThe allowance is intended for travel related to your disability and your goals, such as getting to work, study, community activities and appointments. How it can be used and how much is included depends on your plan and your circumstances, so it is worth reading the wording carefully.\n\nIf you are unsure how transport is set up in your plan, speak to your planner, Local Area Coordinator or support coordinator. They can explain what it covers, how it is paid and how to keep records so you can show how it has been used.",
        'choose' => [
            'Read how transport is described in your plan.',
            'Ask your planner what the allowance can and cannot be used for.',
            'Keep records of trips and costs.',
            'Compare transport options for the trips you make regularly.',
            'Ask about other transport supports if the allowance does not meet your needs.',
        ],
        'start' => [
            'Check your plan for transport funding.',
            'List your regular trips and costs.',
            'Ask your planner or coordinator how the allowance works.',
            'Keep receipts and notes so you can review how it is being used.',
        ],
        'faq' => [
            ['Can I use the allowance for taxis?', 'Ask your planner how it can be used in your circumstances.'],
            ['What if the allowance is not enough?', 'Speak to your planner or support coordinator about your travel needs and what can be done.'],
            ['Do I need to keep receipts?', 'It is a good idea, because you may be asked to show how funds were used.'],
        ],
    ],
    'School Leaver Employment Supports (SLES)' => [
        'cat' => 'Employment & education support',
        'short' => 'School Leaver Employment Supports help young people who are finishing school to build work skills, get work experience and prepare for a job.',
        'overview' => "Leaving school is a big step, and for young people with disability the path to work can be less clear. SLES supports the move from school to work. It typically includes exploring interests, building work-related skills, work experience, help finding a job and support to settle in once started.\n\nPrograms are usually delivered by an employment or disability provider, and can include one-to-one and group activities. They often work closely with the school, family and, where relevant, other employment services, so that the young person has a clear plan.\n\nStart early. Talking about the future in the last years of school gives time to try different things, build confidence and make decisions. Ask providers how they involve the young person and family, what work experience they can arrange and how they support people after they start a job.",
        'choose' => [
            'Ask what activities and work experience the provider offers.',
            'Find out how they involve the young person in planning.',
            'Check their connections with local employers.',
            'Ask how they support people after they start work.',
            'Ask how they work with the school and family.',
        ],
        'start' => [
            'Talk about work goals in the last years of school.',
            'Speak to the school and your planner about employment supports.',
            'Meet a few providers and ask about their programs.',
            'Agree a plan with goals, activities and review dates.',
        ],
        'faq' => [
            ['When should planning for work begin?', 'In the final years of school, so there is time to explore and prepare.'],
            ['What if my child does not know what work they want?', 'That is common. Programs include exploring interests and trying things out.'],
            ['Is SLES the same as a government employment program?', 'No. They are different systems, and some people use both. Ask your planner and providers how they fit together.'],
        ],
        'src' => ['jobaccess'],
    ],
    'Self-management training' => [
        'cat' => 'Plan management',
        'short' => 'Self-management training helps NDIS participants who manage, or want to manage, their own plan to do it well, covering budgeting, choosing providers, keeping records and making claims.',
        'overview' => "Self-managing your plan gives you the most flexibility and control. You choose your providers, agree prices, pay invoices and claim the money back. It also means responsibility for keeping records, staying within your budget and understanding the rules about what supports can be paid for.\n\nTraining helps you build the skills to do this with confidence. It can cover how your plan is structured, how to set up a budget, how to negotiate with providers, how to keep good records and how to make claims. Some people combine self-management with a plan manager for part of their plan.\n\nTraining can come from plan managers, support coordinators and specialist trainers. Ask what the training covers, whether it is one-to-one or in a group and whether they offer ongoing support if you get stuck. It is worth learning the basics before you start, so you feel in control from day one.",
        'choose' => [
            'Ask what the training covers and how long it takes.',
            'Find out whether it is one-to-one, group or online.',
            'Check whether ongoing support is available if you get stuck.',
            'Ask how they help you set up records and budgets.',
            'Check whether they can help you compare plan management options.',
        ],
        'start' => [
            'Read your plan and note which parts you want to manage.',
            'Contact providers who offer self-management training.',
            'Set up a simple budget and record system.',
            'Review after a few months to see how it is going.',
        ],
        'faq' => [
            ['Can I self-manage part of my plan?', 'Some people manage only part of their plan. Ask your planner what is possible.'],
            ['What records do I need to keep?', 'Invoices, receipts and notes about services, so you can show how funds were used.'],
            ['Can I switch to a plan manager later?', 'Yes, you can change how your plan is managed. Ask your planner.'],
        ],
    ],
    'Short Term Accommodation (STA) / respite' => [
        'cat' => 'Respite care',
        'short' => 'Short term accommodation is a short stay away from home, giving you a break or a change and giving family or carers a period of respite.',
        'overview' => "A break can be valuable for everyone. For the person with disability, a short stay can be a chance to try new activities, meet people and experience some independence. For family and carers, it is a rest that helps them recharge and stay well.\n\nSome services are purpose-built respite houses, while others are shared homes that offer occasional stays. Support is provided during the stay, and activities may be planned. Getting to know the service before a longer stay, through a visit or a short first stay, helps everyone feel comfortable.\n\nBooking early is wise, because popular services fill up, especially around school holidays. Ask about what to bring, how medication and health needs are managed, and how families can keep in touch during the stay.",
        'choose' => [
            'Visit the service and meet the staff before booking.',
            'Ask how they get to know you and your routine.',
            'Check accessibility and how health needs and medication are managed.',
            'Ask about activities and how you can choose what to do.',
            'Find out how families can keep in touch during a stay.',
        ],
        'start' => [
            'Think about what kind of break would be most helpful.',
            'Contact services and ask about availability and visits.',
            'Try a short stay first if you can.',
            'Book ahead for busy periods.',
        ],
        'faq' => [
            ['Can I visit before staying?', 'Many services welcome a visit or a short trial stay. Ask.'],
            ['Is respite only for people who live with family?', 'No. People in a range of living arrangements use short term accommodation.'],
            ['What should I bring?', 'The service will tell you. Usually clothing, medication, personal items and anything that helps you feel at home.'],
        ],
    ],
    'Skill-building camps and classes' => [
        'cat' => 'Life skills',
        'short' => 'Skill-building camps and classes are programs where people build skills such as independence, social confidence and recreation in a supported group setting.',
        'overview' => "Camps and classes give people an intensive chance to learn and try new things. A camp might be a few days of activities such as cooking, teamwork, outdoor recreation and independence skills, while a class might run weekly on topics such as art, music, cooking or money skills.\n\nThe group setting adds an important element: people meet others, make friends and see what is possible. Staff and support workers help everyone take part, and activities are adapted to different abilities.\n\nWhen choosing a program, look at what is on offer, who it is for and how it builds skills you want. Ask about staff-to-participant ratios, supervision, medication and personal care support, and what happens if someone becomes unwell or does not want to continue.",
        'choose' => [
            'Check who the program is designed for, including age and support needs.',
            'Ask about staff numbers, training and supervision.',
            'Find out how personal care and medication are handled.',
            'Ask how they handle homesickness or someone wanting to leave.',
            'Ask how skills learned will be followed up afterwards.',
        ],
        'start' => [
            'Decide what skills or experiences you want.',
            'Contact providers and ask for program details.',
            'Discuss support needs with the organisers.',
            'Prepare for the camp or class and plan how to practise afterwards.',
        ],
        'faq' => [
            ['Is a camp suitable if I have never been away from home?', 'Many camps are designed for first-time participants. Ask how they support people and whether a short trial is possible.'],
            ['Can I bring my own support worker?', 'Often yes. Ask the organisers.'],
            ['What if I do not enjoy it?', 'Ask about the process for leaving early or changing activities.'],
        ],
    ],
    'Skill-building community access' => [
        'cat' => 'Life skills',
        'short' => 'Skill-building community access is support in the community that focuses on learning a skill while you are out, such as using public transport, handling money or joining a local group.',
        'overview' => "Community outings can be about enjoyment, but they can also be about learning. With skill-building support, a worker helps you practise a specific skill in the place where you will use it. That might be catching a bus, paying for groceries, ordering at a café, using a library or joining a club.\n\nProgress is planned. You and the worker agree a goal, break it into steps and practise, with the worker gradually stepping back as you gain confidence. Regular reviews check that you are learning and that the goal is still the right one.\n\nThis is different from one-to-one community access, where the emphasis is on taking part and having support to do it. Many people do both, and providers can help you decide which mix suits you.",
        'choose' => [
            'Ask how goals are set and how progress is measured.',
            'Find out how the worker steps back as you gain skills.',
            'Check how the provider keeps you safe in the community.',
            'Ask how they work with family and other supporters.',
            'Ask how the plan changes when you achieve a goal.',
        ],
        'start' => [
            'Choose one skill you want to learn in the community.',
            'Talk to providers about how they would teach it.',
            'Agree steps, dates and a review.',
            'Practise between sessions where you can.',
        ],
        'faq' => [
            ['How long does it take to learn a skill?', 'It varies from person to person. Regular practice and clear steps help.'],
            ['Can I work on more than one skill?', 'Yes, though it can help to focus on one or two at a time.'],
            ['What if I feel anxious in the community?', 'Tell your worker. Good support starts gently and builds up.'],
        ],
    ],
    'Social and recreation activities' => [
        'cat' => 'Community access',
        'short' => 'Social and recreation activities help you enjoy your leisure time and connect with others through sport, hobbies, social groups and outings.',
        'overview' => "Time spent doing things you enjoy with people you like is central to wellbeing. Social and recreation supports help make that possible. They might involve going to a movie, joining a walking group, taking part in a sport, attending a social club or trying a new hobby.\n\nSome people prefer group activities, others prefer one-to-one, and many like a mix. You should have a real say in what you do, and providers should listen when your interests change. Good programs offer variety and let you try things before deciding.\n\nThink about the practicalities too, such as transport, costs of activities, timing and how support will be arranged. A provider can help you plan, and you can review it often to make sure it is still right for you.",
        'choose' => [
            'Ask how you can choose or suggest activities.',
            'Find out how transport to and from activities is arranged.',
            'Check who covers the cost of activities.',
            'Ask about the group size and how people are supported.',
            'Ask how you can change your mind.',
        ],
        'start' => [
            'List activities you enjoy or would like to try.',
            'Talk to providers about what they offer.',
            'Try a few and see what you like.',
            'Review regularly and change activities as your interests change.',
        ],
        'faq' => [
            ['Can I go with a friend?', 'Often yes. Ask the provider how it works.'],
            ['What if I want to try something unusual?', 'Tell the provider. Many are happy to explore new ideas.'],
            ['Are activities always in a group?', 'No. Support can be one-to-one or in a group, depending on your preference.'],
        ],
    ],
    'Social skills and relationship development' => [
        'cat' => 'Life skills',
        'short' => 'This support helps you make friends, communicate and keep healthy relationships, through coaching and practice in one-to-one or group settings.',
        'overview' => "Social skills are the many small things we do to connect with others: starting a conversation, reading body language, taking turns, handling disagreement and understanding what other people might be feeling. Some people find these skills harder to learn, and benefit from explicit teaching and practice.\n\nSupport can take the form of coaching sessions, small groups or practice in real situations. A therapist, psychologist, speech pathologist or trained support worker might lead it. Good programs are respectful, they build on your strengths and they do not try to change who you are.\n\nRelationships also include friendships, family, romantic relationships and safety. Support can cover topics such as boundaries, consent and staying safe online, delivered in a way that suits you. Ask providers about their approach and how they involve family where you want them to.",
        'choose' => [
            'Ask about the qualifications and experience of the people leading the support.',
            'Find out whether the approach respects your identity and strengths.',
            'Check whether sessions are one-to-one or in a group.',
            'Ask how skills are practised in real situations.',
            'Ask how they address topics such as boundaries and safety.',
        ],
        'start' => [
            'Think about the social situations you want to feel more confident in.',
            'Talk to providers about their approach.',
            'Start with small goals and build up.',
            'Review how it is going and adjust.',
        ],
        'faq' => [
            ['Is this only for children?', 'No. People of all ages can benefit from support with social skills and relationships.'],
            ['Will I be expected to act differently?', 'A respectful program helps you build skills you choose, without expecting you to hide who you are.'],
            ['Can it help with making friends online?', 'Yes. Many programs also cover staying safe and connecting online.'],
        ],
    ],
    'Social work' => [
        'cat' => 'Therapy services',
        'short' => 'Social workers help people work through practical and emotional challenges, connect with services and understand their rights and options.',
        'overview' => "Social workers support people during difficult times and help them make sense of complex systems. They might help with a family crisis, housing or financial stress, navigating health and disability services, advocating for your rights or dealing with major life changes.\n\nThey use counselling skills, knowledge of services and understanding of how social factors affect wellbeing. A social worker can help you identify what you need, connect you with the right services and speak up alongside you where it helps.\n\nSocial workers usually have a university degree and many are members of the Australian Association of Social Workers. Ask about their experience with your situation, whether they can see you at home or online and how they will work with your other supports.",
        'choose' => [
            'Ask about the social worker\'s qualifications and membership of a professional association.',
            'Find out whether they have experience with your situation.',
            'Check whether they can see you at home or online.',
            'Ask how they work with your other supports.',
            'Ask how they handle confidentiality.',
        ],
        'start' => [
            'Think about the issues you want help with.',
            'Contact social workers and ask about their approach.',
            'Book a first session and share what is happening.',
            'Agree next steps and how often you will meet.',
        ],
        'faq' => [
            ['How is a social worker different from a counsellor?', 'Their roles overlap. Social workers often focus on practical support and connecting with services as well as emotional support.'],
            ['Can a social worker help with housing?', 'They can help you understand your options and connect with services.'],
            ['Is what I say confidential?', 'Social workers keep information private, with limited exceptions. They explain this at the start.'],
        ],
    ],
];
