<?php
/** Long-form guide content, batch 2. See content-long-1.php for the shape. */
if (!defined('ABSPATH')) exit;

return [
    'Counselling' => [
        'cat' => 'Therapy services',
        'short' => 'Counselling is talking with a trained professional about difficult feelings, life changes or challenges, and building ways to cope. It is a private, respectful space to work things through at your own pace.',
        'overview' => "People come to counselling for many reasons: stress, grief, relationship difficulties, adjusting to a diagnosis or a change in circumstances, or simply wanting to understand themselves better. A counsellor listens without judgement, helps you make sense of what you are experiencing and works with you on practical strategies.\n\nApproaches differ. Some counsellors focus on talking through experiences, others teach specific skills for managing thoughts, emotions or relationships. There is no single right method, and the most important factor in many studies is whether you feel comfortable and understood by the person you are working with.\n\nCounselling is separate from other mental health supports such as psychology or psychiatry, although the boundaries can overlap. If you are unsure which is best for you, a GP or an experienced provider can help you decide, and you can change your approach as your needs change.",
        'choose' => [
            'Ask about the counsellor\'s qualifications and professional membership.',
            'Find out whether they have experience with the kind of concerns you have.',
            'Ask how sessions work, how long they are and how often people usually attend.',
            'Check how they handle privacy and what the limits of confidentiality are.',
            'Consider whether you feel comfortable, and feel free to try more than one counsellor.',
        ],
        'start' => [
            'Think about what you would like to get from counselling.',
            'Contact a small number of counsellors and ask about their approach.',
            'Book a first session and see how it feels.',
            'Review after a few sessions whether it is helping and what to change.',
        ],
        'faq' => [
            ['How long does counselling take?', 'It varies. Some people find a few sessions enough, while others prefer longer-term support. Your counsellor can talk with you about what to expect.'],
            ['Can I bring someone with me?', 'Often yes, depending on the counsellor and your needs. Ask when you book.'],
            ['What if I feel worse after a session?', 'It is normal to feel emotional after difficult conversations. If it continues or worries you, tell your counsellor or another health professional.'],
        ],
    ],
    'Cultural, religious and civic participation' => [
        'cat' => 'Community access',
        'short' => 'This support helps you take part in cultural, religious or civic life, for example attending a place of worship, a community event or a local meeting, in ways that respect your beliefs and choices.',
        'overview' => "Belonging to a culture, faith or community is important to many people, and taking part in civic life gives a voice in decisions that affect you. For people with disability, practical barriers such as transport, physical access, communication or the need for personal support can get in the way of taking part.\n\nA support worker can help with the practicalities. That might mean going with you to a service at your place of worship, helping you attend a cultural festival, supporting you to enrol to vote or go to a council meeting, or helping you connect with a community group that matches your interests.\n\nThe support should reflect what matters to you, not what a provider assumes. Good providers ask about your beliefs and preferences, respect them, and where possible match you with workers who understand your culture, language or faith.",
        'choose' => [
            'Ask whether the provider has experience supporting people from your cultural or faith background.',
            'Find out whether workers who speak your language are available.',
            'Check how they will respect religious practices, dietary needs and dress.',
            'Ask how flexible the support can be around important dates and events.',
            'Find out how they will help you connect with community groups on your own terms.',
        ],
        'start' => [
            'Think about what you would like to take part in and how often.',
            'Tell providers about your beliefs, preferences and any needs they should know about.',
            'Agree how support will work in practice, including transport and timing.',
            'Review regularly and change things if your interests change.',
        ],
        'faq' => [
            ['Can a support worker attend religious services with me?', 'Often yes, if you want them to. Discuss expectations with the worker and the place of worship so everyone is comfortable.'],
            ['Can I request a worker of a particular gender or background?', 'You can ask, and providers will do what they can. Availability varies, so raise it early.'],
            ['Does this include voting?', 'Support to take part in civic life can include getting to a polling place and understanding your options. Ask the provider what they can help with.'],
        ],
    ],
    'Customised prosthetics and orthotics' => [
        'cat' => 'Assistive technology & equipment',
        'short' => 'Prosthetics replace a missing limb or body part, and orthotics support or correct a part of the body. Customised devices are designed, made and fitted for one person by a qualified practitioner.',
        'overview' => "A prosthesis is an artificial limb or body part. An orthosis is a device such as a brace, splint or shoe insert that supports, protects or corrects a part of the body that is still there. Customised devices are made from measurements, scans or casts of the individual, so they fit properly and work with the way the person moves.\n\nProsthetists and orthotists are the health professionals who assess, design, fit and adjust these devices. They also teach people how to use and care for them. Because bodies change over time, and devices wear, regular reviews are an ongoing part of care rather than a one-off event.\n\nLook for practitioners with recognised qualifications and professional membership. Ask how many fittings are usually needed, how adjustments are handled and what support is available to help you learn to use a new device, especially in the early weeks.",
        'choose' => [
            'Ask about the practitioner\'s qualifications, experience and professional membership.',
            'Find out how many appointments are usually needed and where they take place.',
            'Ask about follow-up, adjustments and repairs.',
            'Check how the device will be reviewed as your needs change.',
            'Ask how they work with your other health professionals, such as a physiotherapist.',
        ],
        'start' => [
            'Talk to your doctor or therapist about whether a device may help.',
            'Book an assessment with a prosthetist or orthotist.',
            'Attend fittings and trials and ask questions about care and use.',
            'Arrange regular reviews and know who to call if something does not feel right.',
        ],
        'faq' => [
            ['How long does a custom device last?', 'It depends on the device, how much it is used and how your body changes. Your practitioner can tell you what to expect and when to review.'],
            ['Will it hurt to use?', 'A well-fitted device should be comfortable. It is normal to need time to adapt, but discomfort or skin problems should be reported straight away.'],
            ['Can children have custom devices?', 'Yes. Children grow quickly so devices are reviewed and replaced more often. A practitioner with experience in paediatrics can help.'],
        ],
    ],
    'Daily living and life skills development' => [
        'cat' => 'Life skills',
        'short' => 'This support builds everyday skills such as cooking, budgeting, using public transport and managing a household, so you can do more for yourself.',
        'overview' => "Life skills support is about learning. Rather than doing tasks for you, a support worker, therapist or coach helps you learn how to do them yourself, at a pace that suits you. Common goals include cooking simple meals, keeping a home clean, managing money, using buses and trains, and keeping appointments.\n\nGood programs start with what you want to achieve. Together you break a goal into steps, practise in real situations and review progress. Repetition and encouragement matter, and so does starting with skills that matter to you, because motivation makes learning easier.\n\nSome people use this support in the lead-up to a big change, such as moving out or starting work. Others use it to build confidence after an illness or injury. Whatever the reason, the aim is greater independence and choice.",
        'choose' => [
            'Ask how the provider sets goals with you and measures progress.',
            'Look for a teaching approach that builds your skills instead of doing tasks for you.',
            'Ask whether support can happen in your own home and community.',
            'Find out how they adjust if something is not working.',
            'Ask how long support is usually needed and how it reduces as you gain confidence.',
        ],
        'start' => [
            'Choose two or three skills you would like to learn first.',
            'Talk to providers and describe your goals.',
            'Agree a simple plan with steps and a review date.',
            'Practise between sessions, and celebrate progress.',
        ],
        'faq' => [
            ['Is this only for young people?', 'No. People of all ages learn new skills, whether preparing for independent living or adjusting after a change in their health.'],
            ['What if I learn slowly?', 'That is fine. Good support works at your pace, breaks tasks into small steps and repeats them as often as needed.'],
            ['Can family help me practise?', 'Yes. Ask your provider how to involve family so the same approach is used at home.'],
        ],
    ],
    'Dietitian' => [
        'cat' => 'Therapy services',
        'short' => 'A dietitian gives evidence-based advice about food and nutrition, including for medical conditions, feeding difficulties or particular dietary needs. They work with you and your other health professionals.',
        'overview' => "Nutrition affects energy, growth, weight, bowel health and the management of many conditions. A dietitian assesses what you eat, what you need and what gets in the way, then works with you on a practical plan. This can include managing diabetes, coping with food allergies, gaining or losing weight safely, or planning meals when eating is difficult.\n\nFor people with disability, dietitians often work with speech pathologists and doctors. They can help people who have difficulty swallowing, who use tube feeding, or who have sensory or behavioural challenges around food. The advice is tailored, so it takes into account preferences, culture, budget and what the person is able to prepare.\n\nDietitians complete specific university training, and many are Accredited Practising Dietitians through Dietitians Australia. Because the word nutritionist is used more loosely, it is worth asking about qualifications so you know what you are getting.",
        'choose' => [
            'Ask about the dietitian\'s qualifications and whether they are an Accredited Practising Dietitian.',
            'Find out whether they have experience with your condition or with disability.',
            'Ask whether they can visit you at home or work by video.',
            'Check how they work with your doctor and other therapists.',
            'Ask how progress will be reviewed and how often you will see them.',
        ],
        'start' => [
            'Talk to your doctor if you have concerns about eating, weight or a medical condition.',
            'Write down what you eat over a few days to bring to the first appointment.',
            'Book an assessment and ask what to prepare.',
            'Agree simple goals and a review date.',
        ],
        'faq' => [
            ['Do I need a referral to see a dietitian?', 'Not always. A referral from your doctor can be useful, and it is worth asking the practice what they need.'],
            ['Can a dietitian help with fussy eating?', 'Yes, especially for children and people with sensory difficulties. They can suggest ways to widen the diet safely.'],
            ['Will I have to follow a strict diet?', 'A good dietitian aims for changes you can manage in daily life, rather than a rigid plan.'],
        ],
        'src' => ['ahpra'],
    ],
    'Early Childhood Intervention' => [
        'cat' => 'Therapy services',
        'short' => 'Early childhood intervention is early support for young children with developmental delay or disability. Therapists and educators work with the child and family so learning carries into everyday life.',
        'overview' => "The early years are a time of rapid growth in movement, communication, play and learning. When a child is developing differently, early support can help them build skills and confidence and can give families the tools to support them at home and in the community.\n\nEarly childhood intervention usually involves a team, which may include a speech pathologist, occupational therapist, physiotherapist, psychologist and early childhood educator. Good teams work with the whole family, coaching parents and carers so that practice happens during daily routines such as meals, bath time and play, rather than only in appointments.\n\nFamilies often have questions about what to expect and where to start. A child's doctor, paediatrician or early childhood health nurse can give advice about concerns and about what supports may help, and providers can explain their approach and how they involve families.",
        'choose' => [
            'Ask how the provider involves parents and carers in sessions.',
            'Find out which professionals are on the team and how they work together.',
            'Ask whether support can take place at home, childcare or kindergarten.',
            'Check how goals are set and reviewed with the family.',
            'Ask how they help with the move to school when the time comes.',
        ],
        'start' => [
            'Talk to your child\'s doctor or health nurse about your concerns.',
            'Write down what you have noticed and what you would like to work on.',
            'Contact providers and ask about their approach.',
            'Agree goals with the team and plan regular reviews.',
        ],
        'faq' => [
            ['How do I know if my child needs support?', 'If you are worried about your child\'s development, speak to your doctor or child health nurse. They can talk through your concerns and suggest next steps.'],
            ['Will my child have to go to lots of appointments?', 'It depends on the approach. Many providers coach families to work on goals at home, so appointments are focused and practical.'],
            ['Can brothers and sisters take part in sessions?', 'Often yes. Ask the provider how they include siblings and the wider family.'],
        ],
    ],
    'Employment assessment and counselling' => [
        'cat' => 'Employment & education support',
        'short' => 'Employment assessment and counselling helps you work out what kind of work suits you and what support you need, followed by guidance on preparing for and finding a job.',
        'overview' => "For many people the first step towards work is understanding what is possible. An employment assessment looks at your interests, strengths, skills, experience and the supports you may need in a workplace. It can include conversations, activities and, if useful, trial tasks. The result is a clearer picture of the kind of work that might suit you.\n\nCounselling builds on that picture. A counsellor or employment specialist can talk through worries, explore options such as training, volunteering or work experience, and plan realistic next steps. This can be especially useful if you have never worked, have been out of work for a while or are changing direction.\n\nEmployment support is delivered through several different systems. Some support sits within an NDIS plan, and separate government employment programs are also available. It helps to ask providers and your planner or support coordinator how these fit together for you.",
        'choose' => [
            'Ask how the assessment works and how long it usually takes.',
            'Find out how the provider will involve you in decisions.',
            'Ask about their links with employers and training providers.',
            'Check whether they can support you after you start a job.',
            'Ask how they handle questions about telling an employer about your disability.',
        ],
        'start' => [
            'Think about the types of work, hours and settings that interest you.',
            'Speak to your planner or support coordinator about employment supports.',
            'Book an assessment and bring examples of past work, study or volunteering.',
            'Agree next steps and a plan for reviewing progress.',
        ],
        'faq' => [
            ['Do I have to tell an employer about my disability?', 'Generally you decide what you share. A good provider can talk with you about when it might help, for example to arrange adjustments, and when it may not.'],
            ['Can I use this if I have never worked?', 'Yes. Many people use employment assessment to explore work for the first time.'],
            ['Where can I find out about workplace adjustments?', 'Government services such as JobAccess give information about adjustments and support available in workplaces.'],
        ],
        'src' => ['jobaccess'],
    ],
    'Exercise physiology' => [
        'cat' => 'Therapy services',
        'short' => 'An exercise physiologist designs safe, tailored exercise programs to improve strength, movement, fitness and long-term health, including for people with chronic conditions or disability.',
        'overview' => "Exercise physiologists are university-trained health professionals who use exercise as a treatment. They work with people who have long-term conditions such as diabetes, heart disease, arthritis, chronic pain or neurological conditions, as well as people recovering from injury or living with disability. The aim is to improve function, strength and wellbeing safely.\n\nA program starts with an assessment of your health, abilities and goals. The exercise physiologist then designs exercises that suit your body, often adapting equipment or movements, and supervises you at the start so that you learn how to do them safely. Programs can be delivered in a clinic, gym, pool or at home.\n\nExercise physiology overlaps with physiotherapy. Physiotherapists tend to focus on assessing and treating injury and movement problems, while exercise physiologists focus on exercise as a tool for long-term health. Many people see both, and a good practice will communicate with your other health professionals.",
        'choose' => [
            'Ask about the exercise physiologist\'s qualifications and professional accreditation.',
            'Find out whether they have experience with your condition or disability.',
            'Ask where sessions take place and whether home visits are possible.',
            'Check how they adapt exercises and equipment for your needs.',
            'Ask how progress will be measured and how often the program will change.',
        ],
        'start' => [
            'Talk to your doctor about exercise and your health needs.',
            'Book an assessment with an exercise physiologist.',
            'Set simple goals for strength, mobility or fitness.',
            'Review your program regularly and keep moving between sessions.',
        ],
        'faq' => [
            ['Is exercise safe with my condition?', 'A qualified exercise physiologist plans exercise around your health conditions and checks with your doctor where needed.'],
            ['Do I have to go to a gym?', 'No. Programs can be designed for a clinic, home, pool or community setting, depending on what suits you.'],
            ['How is it different from a personal trainer?', 'Exercise physiologists have health training and work with medical conditions, while personal trainers usually focus on fitness. Ask trainers about their experience with your needs.'],
        ],
    ],
    'Financial and organisational skills' => [
        'cat' => 'Life skills',
        'short' => 'This support helps you build skills in managing money, paperwork and routines, such as budgeting, paying bills and keeping appointments organised.',
        'overview' => "Managing money and admin is a skill that many people need help to learn. Financial and organisational support works on the practical tasks: setting a budget, understanding bills, using banking safely, planning for larger costs, sorting mail and paperwork, and keeping track of appointments and deadlines.\n\nThe focus is on building your ability to make your own decisions. A support worker or coach might use tools such as budgeting apps, calendars or simple checklists, and work through real bills and statements with you so the learning is directly useful.\n\nThis support is different from having someone else manage your money. Where a person needs formal help with financial decisions, there are separate legal arrangements, and advice from a financial counsellor or advocate can be valuable. Ask providers how they protect your independence and privacy.",
        'choose' => [
            'Ask how the provider builds your skills instead of taking over tasks.',
            'Find out how they keep your financial information private and secure.',
            'Check that workers understand scams and can help you stay safe.',
            'Ask whether they can work with your bank, family or advocate if you wish.',
            'Find out how progress will be reviewed.',
        ],
        'start' => [
            'List the money and admin tasks you find hardest.',
            'Choose one or two to work on first.',
            'Agree how often you will meet and what tools you will use.',
            'Review after a few weeks and adjust the plan.',
        ],
        'faq' => [
            ['Can a support worker access my bank account?', 'You should stay in control of your accounts. Ask the provider about their policies and never share passwords or PINs unless you fully understand the arrangement.'],
            ['Where can I get free financial advice?', 'Financial counselling services offer free and confidential help with debt and money problems. A support coordinator can help you find one.'],
            ['Can this help me save for something?', 'Yes. Setting a savings goal and a plan is a common part of budgeting support.'],
        ],
    ],
    'Group / shared living support' => [
        'cat' => 'Housing (SDA & SIL)',
        'short' => 'Shared living support is help for people who live together in a shared home. It covers the everyday support each person needs, arranged around the household as well as each individual.',
        'overview' => "In a shared home, several people live together and receive support from a provider. The support might include help with personal care, meals, household tasks, medication and getting out into the community. Because people share staff, rosters and sometimes vehicles, the provider plans the day so that everyone gets the support they need.\n\nThe quality of a shared home depends heavily on how well people get on and how much say each person has. Good providers ask people about their preferences, involve them in decisions about the household and make sure people can choose how to spend their time, who visits and how their room is set up.\n\nShared living is one of several housing and support options. Others include living alone with support, living with family and specialist housing. It helps to compare the options and to ask questions about how the home is run, who else lives there and how staff are chosen and trained.",
        'choose' => [
            'Visit the home, if you can, and meet staff and housemates.',
            'Ask how the provider decides who lives together.',
            'Find out how you can personalise your room and make decisions about the household.',
            'Ask how staffing is arranged, including nights and weekends.',
            'Check how complaints are handled and how you can change arrangements later.',
        ],
        'start' => [
            'Think about the kind of home and housemates you would like.',
            'Talk to your planner or support coordinator about housing options.',
            'Visit a few homes and ask questions.',
            'Agree what support you will receive and how it will be reviewed.',
        ],
        'faq' => [
            ['How are housemates matched in a shared home?', 'You should have a say. Ask providers how they match housemates and what happens if things do not work out.'],
            ['Can I have visitors?', 'Ask how visitors are handled. You should be able to have people you care about visit, within reasonable household arrangements.'],
            ['What if I want to move out later?', 'Discuss how arrangements can change and what notice is needed before you agree to move in.'],
        ],
    ],
    'Group and centre-based activities' => [
        'cat' => 'Community access',
        'short' => 'Group and centre-based activities are planned programs at a centre or community venue, such as social sessions, skill-building and recreation, with support workers on hand to help.',
        'overview' => "Centre-based programs offer a regular place to go, people to see and things to do. Activities vary widely: cooking and craft, music, sport, computer classes, social outings and life skills sessions. Support workers help people take part and provide personal care when needed.\n\nThese programs can be a good fit for people who enjoy company and routine, or whose families need reliable daytime support. Others prefer to spend their time in the wider community, and for them one-to-one community access may suit better. Some people combine the two.\n\nThe best programs are built around what participants want to do, rather than a fixed timetable. Visiting, asking to try a session, and talking to people who attend can help you decide, and a good provider will welcome the chance to show you around.",
        'choose' => [
            'Visit and ask to try a session before committing.',
            'Look at the range of activities and whether participants have a say in choosing them.',
            'Ask about staff numbers, training and how they support people with different needs.',
            'Check how the centre supports personal care, medication and meals.',
            'Ask how transport to and from the centre is arranged.',
        ],
        'start' => [
            'Write down what you would like to do and who you would like to meet.',
            'Contact providers and arrange a visit.',
            'Try a session and see how it feels.',
            'Agree days, activities and a review date in a service agreement.',
        ],
        'faq' => [
            ['Can I go just a few days a week?', 'Often yes. Many people combine centre-based activities with other supports. Ask about flexible arrangements.'],
            ['What if I do not like the activities?', 'Talk to the staff. Good providers change what they offer based on what participants say.'],
            ['Is there a minimum notice for cancellations?', 'Check the service agreement, since rules differ between providers.'],
        ],
    ],
];
