<?php
/**
 * Editorial content for service posts, part 2 (titles F-P). See content-services-1.php for the shape.
 */
if (!defined('ABSPATH')) exit;

return [
    'Financial and organisational skills' => ['cb',
        'People who want to get better at managing money, paperwork and routines, such as budgeting, paying bills and keeping appointments organised.',
        [
            ['What does financial skills support cover?', 'Practical help with things like setting a budget, understanding bills, saving and using banking safely, along with organising paperwork and routines so everyday admin feels manageable.'],
            ['Will someone manage my money for me?', 'The aim is to build your skills so you can make your own decisions. Some people also need other arrangements, which are separate. Ask providers how they support your independence.'],
            ['Is this the same as plan management?', 'No. Plan management is about handling the payments and paperwork for an NDIS plan. Financial skills support helps you build your own money and organisation skills.'],
        ]],
    'Group / shared living support' => ['core',
        'People who live with others in a shared home and need everyday support as part of that household.',
        [
            ['What is shared living support?', 'Support for people who live together in a shared home. It covers the everyday help each person needs, arranged around the household as well as each individual.'],
            ['How is it different from Supported Independent Living?', 'They are closely related. Supported Independent Living is the name used for help with daily tasks in a shared home. Ask providers to explain exactly how they describe and deliver their service.'],
            ['Can I choose who I live with?', 'You should have a say. Ask providers how they match housemates and how decisions about the household are made, and check that the arrangement suits you.'],
        ]],
    'Group and centre-based activities' => ['core',
        'People who enjoy taking part in group programs at a centre or community venue, such as social sessions, skill-building and recreation.',
        [
            ['What happens at a centre-based activity?', 'People take part in planned activities with others, such as social groups, arts, cooking or skill-building sessions, with support workers on hand to help.'],
            ['How do I choose a good program?', 'Visit if you can, and look at the mix of activities, group sizes, staff and whether the program reflects what you want to do rather than a fixed timetable.'],
            ['Can I change my mind if it is not right for me?', 'Your service agreement should explain how to give notice or change the support. Check the terms before you start.'],
        ]],
    'Group skills development' => ['cb',
        'People who learn well alongside others and want to build skills such as communication, independence or social confidence in a group.',
        [
            ['Why learn skills in a group?', 'Practising with others can build confidence, offer chances to make friends and let people learn from one another. It can suit people who like a shared, structured setting.'],
            ['What kinds of skills are covered?', 'Examples include communication, cooking, money skills, travel training and social skills. Programs differ, so ask what a group covers and how progress is tracked.'],
            ['How big are the groups?', 'Group sizes vary. Ask how many participants and staff are usually involved, and whether the group is arranged by age, interest or support needs.'],
        ]],
    'Hearing equipment' => ['at',
        'People who are deaf or hard of hearing and use, or could benefit from, hearing aids, alerting devices or other assistive listening technology.',
        [
            ['What hearing equipment is available?', 'Options include hearing aids, personal amplifiers, alerting devices such as flashing smoke alarms or doorbells, and technology that connects to phones and televisions.'],
            ['Who fits and adjusts hearing devices?', 'An audiologist tests hearing, recommends devices and fits and adjusts them. Regular check-ups help make sure the devices keep working well as your hearing changes.'],
            ['How do I get used to hearing aids?', 'It takes time. Wearing them regularly, going back for adjustments and getting training in how to use them all help. Ask your audiologist what to expect.'],
        ]],
    'Hearing services and audiology' => ['general',
        'People who want their hearing tested, or who need advice, devices or ongoing care for hearing loss or related conditions.',
        [
            ['What does an audiologist do?', 'An audiologist tests hearing, explains the results, recommends and fits hearing devices and gives advice about managing hearing loss and related conditions such as tinnitus.'],
            ['How often should I have my hearing checked?', 'It depends on your situation. Your audiologist or doctor can suggest how often to review your hearing, especially if you notice changes.'],
            ['Do I need a referral for a hearing test?', 'Often not for a hearing test, though your doctor may recommend one. Ask the clinic what they need when you book.'],
        ]],
    'High-intensity personal care' => ['core',
        'People whose personal care involves complex health needs or extra risk, so that workers need additional training for specific tasks.',
        [
            ['What makes personal care "high intensity"?', 'It involves tasks that need additional skills, training or supervision, for example certain health-related tasks carried out under a health professional\'s guidance, alongside everyday personal care.'],
            ['How are workers trained for these tasks?', 'Workers should receive training specific to the person, usually from a nurse or other health professional, and their competence should be checked. Ask providers to describe how they do this.'],
            ['What should I ask about high-intensity personal care?', 'Ask about the training workers receive, who supervises them, how they respond to emergencies and how they keep records. Clear answers are a good sign.'],
        ]],
    'Higher education and training support' => ['cb',
        'People studying at university, TAFE or with another training provider who need support with organisation, access or study routines.',
        [
            ['What support can help me study?', 'Support may include help planning your week, staying organised, using assistive technology and building study skills, alongside adjustments arranged with your education provider.'],
            ['Does my university or TAFE also provide support?', 'Education providers have their own disability services and can arrange adjustments such as extra time or accessible materials. These work alongside, not instead of, other supports.'],
            ['When should I start arranging support?', 'As early as you can. Speak to your education provider\'s disability service and any support providers well before the term starts.'],
        ]],
    'Home enteral nutrition (HEN)' => ['general',
        'People who receive nutrition through a feeding tube at home, along with the formula, equipment and guidance they need.',
        [
            ['What is home enteral nutrition?', 'Nutrition delivered through a feeding tube at home. It includes the formula and supplies, along with training and guidance from health professionals.'],
            ['Who supports someone on tube feeding?', 'Usually a team: a doctor, a dietitian, sometimes a speech pathologist and nurses, plus family or support workers trained to help. Regular review keeps the plan suitable.'],
            ['How are supplies delivered?', 'Suppliers commonly deliver formula and equipment to your home on a schedule. Ask about ordering, delivery times and who to call if something goes wrong.'],
        ]],
    'House cleaning and household tasks' => ['core',
        'People who find it hard to keep on top of cleaning, laundry and other household jobs because of their disability.',
        [
            ['What household tasks can a support worker help with?', 'Common examples are cleaning, laundry, changing beds, tidying and keeping the home safe. The mix depends on what you need and what you agree with your provider.'],
            ['Can I do some tasks myself?', 'Yes. Many people share tasks with a worker or work towards doing more themselves. Tell your provider what matters to you.'],
            ['How do I get a reliable cleaner?', 'Ask about regular schedules, how workers are chosen and what happens if your regular worker is away. Reading the service agreement carefully helps avoid surprises.'],
        ]],
    'Household management' => ['core',
        'People who need help running a home, for example planning meals, shopping, paying bills and keeping things organised.',
        [
            ['What does household management involve?', 'Support with the wider running of a home, such as planning meals, shopping, organising bills and keeping routines on track.'],
            ['How is it different from cleaning?', 'Cleaning is one part of a household. Household management also covers planning and organising, which some people do with a support worker rather than have done for them.'],
            ['Can I work towards doing more myself?', 'Often, yes. Many people combine support with skill-building so they gradually take on more. Discuss your goals with your provider.'],
        ]],
    'Household task equipment' => ['at',
        'People who find kitchen and household tasks difficult and could use adapted tools or aids to make them easier or possible.',
        [
            ['What kinds of household equipment can help?', 'Examples include adapted kitchen tools, jar openers, reachers, trolleys and other aids designed to make cooking, cleaning and daily chores easier.'],
            ['How do I know what will suit me?', 'An occupational therapist can look at how you do tasks at home and suggest equipment. Trying items before you buy helps you avoid ones that do not work for you.'],
            ['Are simple aids worth it?', 'Often. Small, low-cost items can make a big difference to independence and safety, so they are worth asking about alongside larger equipment.'],
        ]],
    'Housing search and matching' => ['cb',
        'People who are looking for a suitable home and need help understanding their options and being matched with a place that fits.',
        [
            ['What does housing search support involve?', 'Help exploring housing options, understanding what each offers, finding places that fit your needs and preferences and making applications.'],
            ['Can it help me find accommodation with support?', 'It can help you understand options that include support, such as shared living or specialist housing, and how they compare. What is available varies by area.'],
            ['How long can it take?', 'It varies a lot, because suitable housing can be limited. Ask providers how they will support you through the wait and keep your options under review.'],
        ]],
    'Individualised Living Options (ILO)' => ['general',
        'People who want to design a living arrangement around their own goals and preferences, rather than choosing from existing housing models.',
        [
            ['What is an Individualised Living Option?', 'A way of designing where and how you live around your own goals, needs and preferences, rather than fitting into a set housing model. It can involve exploring options and setting up supports.'],
            ['Who helps set it up?', 'Providers or coordinators with experience in home and living supports can help you explore, design and put arrangements in place. Ask about their experience and approach.'],
            ['Is it the same as living in a group home?', 'No. The idea is that arrangements are built around the individual, which might mean living alone, with a housemate or with family, with supports designed to fit.'],
        ]],
    'Innovative community participation' => ['core',
        'People who want to take part in the community in new or creative ways that go beyond standard programs.',
        [
            ['What counts as innovative community participation?', 'Creative ways of taking part that suit what the person wants to do, for example a personalised project, a new group or an activity that a standard program does not offer.'],
            ['How is it different from ordinary community access?', 'It is designed around one person\'s interests rather than a set program, so the plan can be more flexible and individual.'],
            ['What should I ask about innovative community participation?', 'Ask about their experience with similar projects, how they will measure whether it is working and how the activity will be reviewed and changed over time.'],
        ]],
    'Interpreting and translation' => ['general',
        'People who communicate in a language other than English, or who use Auslan, and need an interpreter or translated information.',
        [
            ['What is the difference between interpreting and translation?', 'Interpreting deals with spoken or signed communication, for example during an appointment. Translation deals with written material such as letters and forms.'],
            ['Can I get an Auslan interpreter?', 'Auslan interpreters are available through interpreting services. Ask providers about qualifications, availability and how to book, especially for appointments at short notice.'],
            ['Why use a professional interpreter?', 'Professional interpreters are trained to be accurate and impartial, and to keep information confidential. That matters for health, legal and support decisions.'],
        ]],
    'Job coaching and workplace assistance' => ['cb',
        'People who have a job, or are starting one, and want on-the-job support to learn the role and settle into the workplace.',
        [
            ['What does a job coach do?', 'A job coach supports you at work, for example by helping you learn tasks, understand workplace routines and build relationships, and by working with your employer where you agree.'],
            ['Will my employer know?', 'That is your choice. A good provider talks with you about what you want to share and how support will work in the workplace before it starts.'],
            ['How long does the support last?', 'It varies. Often support is strongest at the start and reduces as you become confident, though some people need ongoing help.'],
        ]],
    'Life transition planning and mentoring' => ['cb',
        'People preparing for a big change, such as leaving school, moving out or starting work, who want planning and guidance.',
        [
            ['What is life transition planning?', 'Planning and mentoring to prepare for a major change, such as finishing school, moving out or starting work, so the change feels clearer and more manageable.'],
            ['Who provides mentoring?', 'Mentors may be experienced support workers, coaches or peers with similar life experience. Ask providers about their approach and background.'],
            ['When should I start planning?', 'The earlier the better. Starting well before a change gives time to explore options, build skills and set up the supports you will need.'],
        ]],
    'Low-cost assistive technology' => ['at',
        'People who could benefit from simple, lower-cost aids that support independence at home and in the community.',
        [
            ['What is low-cost assistive technology?', 'Simple, everyday items that make tasks easier, such as adapted utensils, grab rails, alarms, magnifiers and pill organisers.'],
            ['Do I need an assessment before buying simple aids?', 'Often not for simple items, though advice from an occupational therapist can help you choose well. Ask if you are unsure what will suit you.'],
            ['Where can I buy it?', 'From specialist suppliers, pharmacies and some general retailers. Check returns and warranty, and ask for advice if you are unsure.'],
        ]],
    'Meal preparation' => ['core',
        'People who find planning, preparing or cooking meals difficult and would like support with it.',
        [
            ['Does a support worker cook for me?', 'It depends on what you want. A worker can prepare meals for you or support you to prepare them yourself, depending on your goals and abilities.'],
            ['Can support include shopping and planning?', 'Often, yes. Many people get help with planning meals, shopping and kitchen safety as well as cooking.'],
            ['What about special diets?', 'Tell your provider about any dietary needs or allergies. A dietitian can give advice where needed, and workers should follow any plans they are given.'],
        ]],
    'Medication assistance' => ['core',
        'People who need support to take medication safely, for example reminders, prompting or help preparing doses.',
        [
            ['What does medication assistance involve?', 'Support to take medication as prescribed, such as reminders and prompting, or help preparing or giving doses. The level of help depends on the person and on health advice.'],
            ['Who decides what a worker can do?', 'Your doctor or pharmacist and the provider\'s policies set what is appropriate. Workers should be trained for the tasks they carry out and follow a written medication plan.'],
            ['What should I ask a provider about medication support?', 'Ask how workers are trained, how medication is recorded and what happens if a dose is missed. Clear procedures are important.'],
        ]],
    'Medium Term Accommodation (MTA)' => ['core',
        'People who need somewhere to live for a temporary period while a long-term home or modification is arranged.',
        [
            ['What is medium term accommodation?', 'Accommodation for a temporary period, for example while waiting for a long-term home to become available or for modifications to be completed.'],
            ['How is it different from respite?', 'Respite is a short break, usually with a return home. Medium term accommodation covers a longer period between one living situation and another.'],
            ['What should I check before moving in?', 'Ask about the type of home, the support available, how long you can stay, costs and how a move to your next home will be planned.'],
        ]],
    'Minor home modifications' => ['capital',
        'People who need smaller changes to make their home easier and safer to use, such as handrails, ramps or adjusted fixtures.',
        [
            ['What counts as a minor home modification?', 'Smaller jobs that do not involve major structural work, for example fitting handrails, a short ramp, a lever tap or adjusting a shower.'],
            ['Do I need an assessment?', 'A short assessment by an occupational therapist is common, and helps make sure the change suits you. Some simple jobs may need less.'],
            ['Who does the work?', 'Licensed tradespeople or specialist modification providers. Ask for a written quote and check that the person is qualified for the work.'],
        ]],
    'Mobility equipment' => ['at',
        'People who need help moving around, for example a wheelchair, walker, scooter or transfer aid.',
        [
            ['How do I choose a wheelchair or walker?', 'A physiotherapist or occupational therapist can assess your needs and recommend options. Trying equipment in your daily environment is the best way to check fit and comfort.'],
            ['Can mobility equipment be adjusted?', 'Usually, yes. Many items can be adjusted or customised, and it is worth having equipment checked as your needs change.'],
            ['Who maintains it?', 'The supplier or a repair service. Ask about warranty, servicing and what to do if something breaks, so you are not without equipment for long.'],
        ]],
    'Music therapy and art therapy' => ['cb',
        'People who express themselves or connect with others more easily through music or art than through words.',
        [
            ['What is music or art therapy?', 'Therapy that uses music-making or art to support communication, emotional expression, wellbeing and skill development, led by a qualified therapist.'],
            ['Do I need to be musical or artistic?', 'No. The focus is on the process, not on producing something polished. Therapists adapt activities to the person.'],
            ['How do I find a qualified therapist?', 'Look for therapists with recognised qualifications and membership of their professional association, and ask about their experience with people like you.'],
        ]],
    'Nursing training for support workers' => ['general',
        'Support workers and providers who need training from a nurse in specific health-related tasks for the person they support.',
        [
            ['Why do support workers need nursing training?', 'Some health-related tasks need specific skills. A nurse can train workers to carry them out safely for the person they support and check that they can do them competently.'],
            ['Who trains support workers in nursing tasks?', 'A registered nurse with relevant experience, often tailored to the individual person. Training is usually reviewed and updated when needs change.'],
            ['Is the training the same for every person?', 'No. Tasks and risks differ from person to person, so training is usually specific to the individual and their health plan.'],
        ]],
    'Occupational therapy' => ['cb',
        'People who want help with everyday activities, such as self-care, work, study or leisure, or who need advice on equipment or changes at home.',
        [
            ['What does an occupational therapist do?', 'An occupational therapist helps people do the everyday things that matter to them, by assessing needs, building skills, recommending equipment and suggesting changes to the environment.'],
            ['When would I see an occupational therapist?', 'Common reasons include difficulty with daily tasks, needing equipment or home changes, developmental concerns in children and returning to work or study after injury or illness.'],
            ['How do I choose one?', 'Look for someone registered with AHPRA who has experience with your situation, and ask how sessions work and how progress is measured.'],
        ]],
    'One-to-one community access' => ['core',
        'People who want a support worker with them, one-to-one, to take part in the community, such as shopping, appointments, hobbies or outings.',
        [
            ['What does one-to-one community access involve?', 'A support worker accompanies you and helps you do what you want in the community, for example going to a café, a class, a park or a medical appointment.'],
            ['Can I choose the activities?', 'You should be able to. Good providers plan with you and change activities as your interests change.'],
            ['What if I want a particular worker?', 'You can ask. Providers try to match workers to people, though availability differs. Ask how they handle worker changes.'],
        ]],
    'Overnight support' => ['core',
        'People who need help or supervision during the night, either with a worker awake or asleep on site.',
        [
            ['What is the difference between active and sleepover support?', 'With an active overnight shift the worker stays awake to help. In a sleepover, the worker is on site and sleeps but can be woken if needed. Which suits you depends on your needs.'],
            ['Why might someone need overnight support?', 'Reasons include needing help with repositioning, health monitoring, safety or reassurance during the night.'],
            ['What should I ask overnight support providers?', 'Ask how the overnight workers are trained, how they respond to emergencies and how they keep records. Also ask how the arrangement will be reviewed.'],
        ]],
    'Personal care' => ['core',
        'People who need help with everyday tasks such as showering, dressing, grooming, eating or getting around the home.',
        [
            ['What does personal care include?', 'Help with everyday personal tasks such as showering, dressing, grooming, toileting, eating and moving around, delivered with respect for your privacy and choices.'],
            ['Can I choose my support worker?', 'You can ask for preferences, such as gender or language, and providers will try to match them. Availability varies, so raise it early.'],
            ['What should be in a service agreement?', 'It should describe what support you get, when, how much it costs, how to change or end it and how to make a complaint. Read it carefully before you sign.'],
        ]],
    'Personal care and safety equipment' => ['at',
        'People who need equipment to wash, dress, use the toilet or stay safe at home, such as shower chairs, bed rails or personal alarms.',
        [
            ['What personal care equipment is available?', 'Examples include shower chairs and stools, commodes, toilet frames, bed rails, hoists and personal alarms. The right choice depends on your body, your home and your routine.'],
            ['Who can help me choose?', 'An occupational therapist can assess how you manage at home and recommend equipment, including how to set it up safely.'],
            ['How do I know it is safe?', 'Equipment should be installed and adjusted correctly, and used as designed. Ask the supplier for instructions, and have it reviewed if your needs change.'],
        ]],
    'Personal training' => ['general',
        'People who want a fitness trainer to work with them, at their own pace, to build strength, movement and confidence.',
        [
            ['How is personal training adapted for disability?', 'A good trainer adjusts exercises, equipment and pace to your abilities and goals, and works with your health professionals where needed.'],
            ['Is personal training the same as exercise physiology?', 'They overlap, but exercise physiologists are university-trained health professionals who often work with medical conditions. Ask a trainer about their experience with your needs.'],
            ['What should I ask a trainer?', 'Ask about their qualifications, their experience with people like you and how they will set and review goals.'],
        ]],
    'Physiotherapy' => ['cb',
        'People with pain, injury, or difficulty moving or with physical function, including people with long-term conditions or disability.',
        [
            ['What does a physiotherapist do?', 'A physiotherapist assesses and treats problems with movement and physical function, using exercise, manual therapy and education to improve mobility and reduce pain.'],
            ['Do I need a referral to see a physiotherapist?', 'Usually not. A referral can help if your doctor wants to share information, so it is worth asking the clinic what they prefer.'],
            ['How many sessions will I need?', 'It depends on your situation and goals. A good physiotherapist explains the plan and reviews progress with you.'],
        ]],
    'Plan management' => ['cb',
        'NDIS participants who want someone else to handle the payments and paperwork for their plan, so they can use the providers they choose.',
        [
            ['What does a plan manager do?', 'A plan manager pays your providers\' invoices from your NDIS funding, keeps track of your budget and gives you regular statements, so you do not have to handle payments yourself.'],
            ['Can I use providers who are not registered with the NDIS?', 'If your plan is managed by a plan manager or by you, yes. If it is managed by the NDIA, you generally must use registered providers.'],
            ['Does plan management reduce my support budget?', 'Plan management is usually funded separately from your other supports, so it should not use up your support budget. Check your plan or ask the plan manager to confirm.'],
        ]],
    'Podiatry' => ['cb',
        'People who have foot or lower-limb pain, injury or a condition such as diabetes that needs regular foot care.',
        [
            ['What does a podiatrist treat?', 'A podiatrist looks after the health of your feet and lower limbs. They treat pain and injury, manage conditions such as diabetes-related foot problems and advise on footwear.'],
            ['Why is foot care important for some people?', 'For people with conditions such as diabetes, small foot problems can become serious. Regular checks help find issues early.'],
            ['How do I find a podiatrist?', 'Look for someone registered with AHPRA, and ask about their experience with your condition and how often they recommend visits.'],
        ]],
    'Psychology' => ['cb',
        'People who would like assessment or therapy for mental health or behavioural concerns, or help building coping skills.',
        [
            ['What does a psychologist do?', 'A psychologist assesses and treats mental health and behavioural concerns using evidence-based therapies, and can help you build skills and manage emotions.'],
            ['How is a psychologist different from a counsellor?', 'Psychologists have university training in psychology and are registered with AHPRA. Counsellors may have different qualifications. Both can help, and the best fit depends on your needs.'],
            ['How do I choose a psychologist?', 'Check their registration, ask about their experience with your concerns and consider whether you feel comfortable with them.'],
        ]],
    'Psychosocial Recovery Coaching' => ['cb',
        'People with psychosocial disability who want a coach to help them set goals, build skills and take part in daily life and the community.',
        [
            ['What is a psychosocial recovery coach?', 'A recovery coach supports people with psychosocial disability to set goals, build skills, connect with services and take part in daily life on their own terms.'],
            ['What is psychosocial disability?', 'A disability that can arise from a mental health condition. It affects how a person manages everyday activities, relationships and participation in the community.'],
            ['How is recovery coaching different from support coordination?', 'The two overlap. A recovery coach focuses on your recovery goals and building your capacity, and also helps you connect with supports. Ask providers how they describe their role.'],
        ]],
];
