<?php
/**
 * Deeper guide content for service posts, batch 4 (companion to content-long-4.php).
 * Same shape as content-deep-1.php. Plain, general guidance only: no prices, no timeframes, no promises about who qualifies.
 */
if (!defined('ABSPATH')) exit;

return [
    "Innovative community participation" => [
        "day" => "Innovative community participation is built around something new or different that fits what you want to do, rather than a standard program. It might be a group project, a mentored activity, a volunteering role, a creative idea or a course that connects you with people who share your interests. The support is designed with you, and it may look different from anything else on offer.\n\nA worker or coordinator helps you get started, sorts out practical details and keeps in touch about how it is going. Where possible, the aim is to build natural connections in the community so you can keep going without paid support, for example by joining a local club or getting to know neighbours who share your interest.",
        "who" => "Support might come from providers with a flexible approach, community organisations, mentors and support workers. Because the idea is tailored, the most useful person is often someone who listens carefully, is creative about options and knows the local community. Ask providers to describe similar things they have helped people do, and how they keep the person in charge of the idea.",
        "fit" => "This kind of support links with community access, social activities and skill-building, and it can grow out of any of them. It suits people who have a clear interest or goal, but it also works for those who are still finding out what they enjoy. It is good to plan how the activity will continue over time and how success will be judged, so it does not fade once the initial support ends.",
        "ask" => [
            "How will you help me turn my idea into a real activity?",
            "Have you supported similar projects, and what did they involve?",
            "How will you help me connect with others in the community, not just other participants?",
            "How will the activity continue if the support reduces?",
            "How will we know whether it is working for me?",
            "What happens if we find the idea needs to change?",
        ],
        "mistakes" => [
            "Choosing an activity to please others instead of yourself.",
            "Making the plan so rigid that there is no room to change it.",
            "Relying only on paid support and not building natural connections.",
            "Not thinking about transport and other practical barriers.",
            "Not reviewing whether the activity is still what you want.",
        ],
        "faq" => [
            ["What makes a community activity innovative?", "It is tailored to the individual and often goes beyond standard programs, for example by starting a new group, learning an unusual skill or contributing in a way that reflects a person's interests."],
            ["Do I need a fixed idea before I start?", "No. Many people begin with a general interest, and a worker helps to explore options and try things out until something feels right."],
            ["Can family and friends be part of the activity?", "Often yes, and their involvement can help it last. Talk about who you would like to include and how."],
        ],
    ],
    "Interpreting and translation" => [
        "day" => "Interpreting is live: an interpreter helps you and another person understand each other during an appointment, meeting or conversation, in person, by phone or by video. They convey what is said accurately and neutrally, without adding opinions or leaving things out. Sign language interpreters work in a similar way for people who are Deaf or hard of hearing.\n\nTranslation deals with written material, such as letters, forms, reports and information sheets. A translator converts the text into your preferred language or format, keeping the meaning clear. Some services also produce documents in Easy Read, large print or other accessible formats.",
        "who" => "Interpreters and translators may be accredited by the national body for the profession, and services often specify the accreditation level of their staff. For sign language, Auslan interpreters have their own training and accreditation. Ask whether the person is accredited, whether they have experience in the setting, such as health or legal matters, and how they maintain confidentiality.",
        "fit" => "Interpreting and translation support access to all other services, since understanding and being understood underpins every appointment and decision. It is worth arranging interpreters ahead of time for important meetings, and asking providers to book them, rather than relying on family or friends, who may not be neutral or trained in the terminology.",
        "ask" => [
            "Are your interpreters and translators accredited, and at what level?",
            "Can you provide someone with experience in the setting, such as a medical appointment?",
            "Is interpreting available in person, by phone and by video?",
            "How much notice do you need to arrange an interpreter?",
            "How do you protect confidentiality?",
            "Can documents be translated and produced in accessible formats such as Easy Read?",
        ],
        "mistakes" => [
            "Relying on family members or children to interpret in serious situations.",
            "Not booking an interpreter far enough ahead.",
            "Not checking that the interpreter speaks the right dialect or uses the right sign language.",
            "Assuming a translated document will make sense without checking with the person.",
            "Not telling a provider that you need an interpreter, so they do not arrange one.",
        ],
        "faq" => [
            ["Can my family interpret for me instead of a professional?", "It can feel convenient, but family members may not know the terms used and it can be uncomfortable to discuss sensitive matters through them. For important appointments, a professional interpreter is generally best."],
            ["When would I need a translator rather than an interpreter?", "Interpreting is spoken or signed and happens in real time. Translation is written and converts documents from one language to another."],
            ["Can I ask a provider to arrange an interpreter?", "Yes. Many providers are expected to arrange one when you need it, so tell them your preferred language or communication method when you book."],
        ],
    ],
    "Job coaching and workplace assistance" => [
        "day" => "A job coach works with you at the workplace, or on the way to and from it, to help you learn the job and settle in. In the early days they may be present for much of your shift, showing you tasks, helping with the routine and answering questions. They also work with your supervisor and colleagues to make sure everyone understands how to support you.\n\nAs you gain confidence, the coach steps back and checks in less often. They continue to be available for new tasks, changes at work or anything that comes up. Their aim is for you to do the job as independently as possible, with adjustments that suit you.",
        "who" => "Job coaches are usually employed by disability employment providers or specialist services. Good coaches are patient, understand the workplace and treat you as a valued employee, not a client. Ask about their experience with your type of job, how they involve the employer and how they plan to reduce support over time.",
        "fit" => "Job coaching is often part of a package with employment assessment, training and workplace adjustments. It supports the transition from finding a job to keeping it. Employers may also have access to advice and funding for workplace changes, so it helps to ask the coach what else is available.",
        "ask" => [
            "How will you help me learn the job and fit into the team?",
            "How will you work with my employer and supervisor?",
            "How will you reduce the support as I become more confident?",
            "What can be done to adjust the workplace or the tasks so the job works for me?",
            "Who do I call if a problem comes up after the coaching has reduced?",
            "How will we review whether the job is right for me?",
        ],
        "mistakes" => [
            "Accepting a job without discussing what adjustments would help.",
            "Not involving the employer early, which can lead to misunderstanding.",
            "Depending on the coach rather than building relationships with colleagues.",
            "Stopping support too early, before you feel settled.",
            "Not raising concerns until they become big problems.",
        ],
        "faq" => [
            ["Does the employer have to know about my job coach?", "Generally the coach works with the employer's agreement, so the employer will know. A coach can help you and the employer talk about what is needed."],
            ["What kinds of workplace adjustments are common?", "Examples include flexible hours, modified tasks, equipment, changes to the workspace and clear written instructions. The right ones depend on your needs and the job."],
            ["What happens when the coach stops coming?", "The aim is to reach a point where you can do the job with only the support that naturally exists in the workplace. Ongoing check-ins can continue at a lighter level if needed."],
        ],
    ],
    "Life transition planning and mentoring" => [
        "day" => "Transitions are big changes such as leaving school, moving out, starting work, changing services or entering a new stage of life. A planner or mentor works with you to think about what you want, what is coming and what needs to be in place. Sessions may involve mapping goals, visiting new places, meeting people and practising skills you will need.\n\nMentoring adds the value of a person who has been there, or who knows the path well. A mentor can share their own experience, offer encouragement and help you work through worries. Over time the planning becomes more concrete, with steps, dates and who is responsible for what.",
        "who" => "Transition planning may be provided by support coordinators, therapists, teachers, case managers and community organisations. Mentors may be paid workers or peers with lived experience of disability. Choose someone who takes the time to know you, involves your family and friends as you wish, and is realistic about the steps.",
        "fit" => "Transition planning connects with almost every other support, since the changes involve housing, education, employment, community life and health. It helps to start early, particularly for big transitions such as leaving school, because it can take time to arrange the supports and opportunities you want.",
        "ask" => [
            "How will you find out what I want for my life after the transition?",
            "How will you involve my family and the people I choose?",
            "How will you help me prepare practically, for example by visiting or trying new things?",
            "Can I meet a mentor who has been through something similar?",
            "How will you work with the school, service or employer involved?",
            "How will you check that the plan is working after the change?",
        ],
        "mistakes" => [
            "Leaving planning until the change is about to happen.",
            "Making a plan for the person rather than with them.",
            "Overlooking practical details such as transport and daily routines.",
            "Not building relationships before the move, so the person arrives knowing no one.",
            "Not reviewing the plan after the transition to see what needs adjusting.",
        ],
        "faq" => [
            ["When should transition planning start?", "As early as you can. Big changes usually involve several people and organisations, and starting early gives everyone time to prepare."],
            ["What is the role of a mentor?", "A mentor offers guidance, encouragement and perspective, often from personal experience. They are not a therapist or a support worker, but a trusted person who helps you find your way."],
            ["Can transition planning help when leaving school?", "Yes. Planning for life after school can include work, study, community activities and where and how you live, and it often begins in the last years of school."],
        ],
    ],
    "Low-cost assistive technology" => [
        "day" => "Low-cost assistive technology covers everyday items that make tasks easier, such as adapted cutlery, phone stands, simple communication aids, timers, pill organisers, non-slip mats, magnifiers and basic mobility aids. Choosing something usually involves talking about the tasks you find hard, trying a few options and deciding what works.\n\nBecause these items are simple, it is easy to start using them right away. A therapist, supplier or support worker can show you how to set them up, and it helps to keep the ones that help and change or drop the ones that do not. Small items can make a big difference to comfort, safety and independence.",
        "who" => "You can often choose low-cost items yourself, and occupational therapists, suppliers, pharmacists and support workers can help with advice. A therapist is useful if you are not sure what is best or if the task is complex. Retailers that specialise in disability equipment usually have staff who can explain how items work.",
        "fit" => "Low-cost items complement more complex equipment and therapy. Sometimes a simple item solves a problem that would otherwise need more help, and at other times it works alongside larger supports. It is worth reviewing what you use every so often, since needs and available products change.",
        "ask" => [
            "Which tasks are hardest for me, and what simple items could help?",
            "Can I try the item before buying it?",
            "Is it safe and easy to use, and how do I look after it?",
            "Is there an alternative that would work better for my needs?",
            "Where can I get replacements or repairs?",
            "Do I need advice from a therapist before choosing?",
        ],
        "mistakes" => [
            "Buying items without checking that they suit your grip, strength or vision.",
            "Assuming a cheap item is not worth trying.",
            "Not asking a therapist when a problem persists.",
            "Choosing an item that is awkward and ends up unused.",
            "Not replacing worn items that have become unsafe.",
        ],
        "faq" => [
            ["Do I need a professional to recommend low-cost equipment?", "Not for simple items, but advice from an occupational therapist is useful when you are unsure or the task is complex or risky."],
            ["Where can I find low-cost assistive technology?", "Pharmacies, disability equipment retailers, larger stores and online suppliers stock a range. A therapist or your provider can suggest what to look for."],
            ["Are cheap items less reliable?", "Not necessarily, but check quality and safety, particularly for items that bear weight or affect your health."],
        ],
    ],
    "Meal preparation" => [
        "day" => "A meal preparation session may involve planning what to eat, shopping for ingredients, cooking, serving and cleaning up. Depending on your goals, the worker might cook for you, cook with you or teach you to cook yourself. They follow your preferences, dietary needs and any advice from a dietitian or speech pathologist.\n\nThe atmosphere matters. Cooking together can be a pleasant part of the day and a chance to learn, and a worker who is respectful of your tastes and culture makes the food more enjoyable. Where you need it, the worker also pays attention to kitchen safety, hygiene and food storage.",
        "who" => "Meal preparation is provided by support workers, domestic assistance workers and, for some people, home care services. Occupational therapists can help with kitchen setup and safe ways of cooking, and dietitians advise on nutrition. Ask whether the worker has food safety training and experience with your dietary needs.",
        "fit" => "Meal preparation links with nutrition, household management, shopping and independent living. For some people it is about health, and for others it is about learning skills and independence. Meals may be prepared on the day or made in batches, and delivery services and ready-made meals are also options to consider.",
        "ask" => [
            "How will you take my preferences, culture and dietary needs into account?",
            "Will you cook for me or with me, and can we change that over time?",
            "How do you handle food safety and hygiene?",
            "Do you have experience with special diets or texture-modified food?",
            "Who does the shopping, and how are money and receipts handled?",
            "How will you help me learn to prepare meals myself if I want to?",
        ],
        "mistakes" => [
            "Not telling the worker about allergies, swallowing difficulties or health advice.",
            "Not agreeing how shopping money is handled.",
            "Relying on the same few meals because planning is hard.",
            "Overlooking kitchen safety, such as hot surfaces and knives.",
            "Not asking for help to build your own skills when you want them.",
        ],
        "faq" => [
            ["Can a worker prepare meals that suit a special diet?", "Often yes, if they have been given clear information and the right training. A dietitian can write down the requirements so that the worker can follow them."],
            ["Can I learn to cook with the support of a worker?", "Yes. Many people work with a worker on cooking skills, starting with simple recipes and building confidence."],
            ["Are ready-made or delivered meals an option?", "For some people, yes. They can be a good backup or main option, so ask the provider or your dietitian about what would suit you."],
        ],
    ],
    "Medication assistance" => [
        "day" => "Medication assistance means help with taking medicines safely and on time. Depending on your needs, this could be a reminder, help opening packaging, preparing or handing you your medicines, or recording that they have been taken. It never means changing the dose or type of medicine, which only a doctor or pharmacist can do.\n\nA worker follows the medication plan from your doctor or pharmacist and keeps a record of what was given. They watch for side effects or changes, and let you, your family or your doctor know if something seems wrong. Reviews with a doctor or pharmacist keep your medicines up to date.",
        "who" => "Support workers can assist with medication when they have been trained and the arrangement follows the provider's policy and your health professionals' advice. Nurses manage more complex or clinical medication tasks. Pharmacists can provide packing services such as dose administration aids and can review your medicines. Ask about the training workers have and how the provider manages medication safely.",
        "fit" => "Medication support works with your GP, pharmacist, community nurse and support workers. Keeping an up-to-date list of your medicines and sharing it with everyone involved helps prevent errors. It also links with daily routines, since medicines are often taken at set times of day.",
        "ask" => [
            "What training do your workers have in assisting with medication?",
            "How do you follow the instructions from my doctor or pharmacist?",
            "How do you record when medication is given?",
            "What happens if a dose is missed or a mistake is made?",
            "How do you keep my medicines stored safely?",
            "How will you tell my doctor if I have side effects or changes in health?",
        ],
        "mistakes" => [
            "Not keeping a current list of medicines that everyone can see.",
            "Having untrained workers handle medication.",
            "Not recording doses, which makes it hard to tell what has happened.",
            "Ignoring side effects instead of reporting them.",
            "Not reviewing medicines regularly with your doctor or pharmacist.",
        ],
        "faq" => [
            ["Can a support worker give me my medication?", "In many cases they can help, provided they have been trained and follow your health professionals' instructions and the provider's policy. More complex tasks may need a nurse."],
            ["What is a dose administration aid?", "It is a pack, often prepared by a pharmacist, that holds medicines organised by day and time so they are easier to take correctly."],
            ["What should I do if a dose is missed?", "Check the advice from your pharmacist or doctor, since it varies from medicine to medicine. Do not double up unless you have been told to."],
        ],
    ],
    "Medium Term Accommodation (MTA)" => [
        "day" => "Medium term accommodation is a place to live for a period while you wait for a permanent home or while arrangements are sorted out. A typical stay involves moving into a furnished home or unit, with support workers helping with daily tasks depending on your needs. It is intended as a bridge, not a final arrangement.\n\nWhile you are there, work continues on finding a longer-term home and setting up the supports you will need. A coordinator may help with viewing properties, submitting applications and preparing to move. Life in the meantime carries on, with support to maintain routines such as work, study, appointments and time with friends and family.",
        "who" => "Medium term accommodation is offered by housing and disability support providers, often with support coordinators helping you find and arrange it. Support in the home is provided by workers who understand the purpose of the stay and who can help with the next step. Ask about how the stay is arranged, how long it is likely to last and what happens if your permanent home is not ready.",
        "fit" => "MTA sits between crisis or short-term accommodation and long-term housing, and it works alongside housing search, support coordination and daily living support. It is a chance to try different arrangements and learn what suits you, so it makes sense to use the time to explore options and to plan the move.",
        "ask" => [
            "How long is a stay likely to last, and what happens if my permanent home is not ready?",
            "What support is provided in the home, and who is there at different times?",
            "How will you help me plan and organise my move to a long-term home?",
            "What do I need to bring, and what is provided?",
            "What are the house rules and how are shared spaces managed?",
            "How will you keep me connected with my routines and community?",
        ],
        "mistakes" => [
            "Treating the stay as permanent and not working on the next step.",
            "Not clarifying what happens if the stay needs to be extended.",
            "Not checking accessibility of the home for your needs.",
            "Leaving practical arrangements, such as mail and utilities, unresolved.",
            "Not using the stay to trial the supports you will need long term.",
        ],
        "faq" => [
            ["What is the difference between medium term and short term accommodation?", "Short term accommodation is generally for a break or emergency, while medium term accommodation is a longer stay to bridge the gap until a permanent home is available."],
            ["Can I stay in medium term accommodation while I wait for my own home?", "That is its purpose. The details, including how long you can stay, depend on the arrangement, so confirm them with the provider and your coordinator."],
            ["Will I have my own space?", "Many homes offer a private bedroom with shared living areas, but arrangements vary. Ask to see the home and what is provided before agreeing."],
        ],
    ],
    "Minor home modifications" => [
        "day" => "Minor home modifications are small changes that make a home safer and easier to use, such as grab rails, ramps for a step, handheld showers, lever taps, better lighting or non-slip surfaces. A therapist or installer visits, looks at how you move around the home, and recommends the changes that will make the biggest difference.\n\nThe work is usually done in a short time by a licensed tradesperson or installer. After installation, it is worth checking that everything works as you expected and that you feel confident using it. Keeping any warranty or installation paperwork will help if there are problems later.",
        "who" => "An occupational therapist can assess your needs and recommend modifications, and a builder, handyperson or specialist installer carries out the work. Some providers offer both assessment and installation. Ask whether the installer is licensed and insured, has experience with accessible fittings and will check the work with you at the end.",
        "fit" => "Minor modifications are often part of falls prevention and independence at home, and they work alongside equipment and personal care. They are quicker and less disruptive than major building work. If your needs are likely to increase, it is worth thinking about whether a bigger change might make sense in the long run.",
        "ask" => [
            "Can an occupational therapist assess how I use my home before we choose changes?",
            "Is the installer licensed and insured, and have they done similar work?",
            "What will the work involve, and how long will it disrupt my home?",
            "Is there a warranty, and who do I contact if something goes wrong?",
            "If I rent, do I need permission, and who arranges it?",
            "Would a different solution work better or last longer?",
        ],
        "mistakes" => [
            "Installing rails or ramps in the wrong place because no one checked how you move.",
            "Using a tradesperson without the right licence or insurance.",
            "Not getting the landlord's permission when renting.",
            "Ignoring how your needs might change.",
            "Not testing the modification once it is installed.",
        ],
        "faq" => [
            ["What is the difference between minor and complex modifications?", "Minor modifications are small, low-risk changes such as rails, small ramps and taps. Complex modifications involve significant structural work, such as widening doors or rebuilding a bathroom."],
            ["Do I need a therapist to recommend modifications?", "For anything beyond simple fixtures it is a good idea, because a therapist can make sure the change suits your body, your home and your routine."],
            ["Can I take modifications with me if I move?", "Some can be removed and reinstalled, and others are fixed to the building. Ask the installer about what is possible before the work starts."],
        ],
    ],
    "Mobility equipment" => [
        "day" => "Choosing mobility equipment usually starts with an assessment by a physiotherapist or occupational therapist who looks at how you move, where you go and what you want to do. They may recommend walking frames, wheelchairs, scooters or other aids and arrange for you to try them. Fitting and adjustment are important, since a poorly fitted item can cause pain or injury.\n\nOnce you have the equipment, training helps you use it safely in your home and community. Regular servicing and reviews keep it working well, and your therapist can check whether it still suits you as your needs change.",
        "who" => "Physiotherapists and occupational therapists usually assess mobility needs and prescribe equipment, and specialist suppliers provide, fit and maintain it. For complex wheelchairs or seating, look for a therapist and supplier with specific experience. Ask about trial options, servicing arrangements and what support is available if the equipment fails.",
        "fit" => "Mobility equipment works with home modifications, transport and therapy. Where you use the equipment matters, so consider doors, ramps, vehicles and the places you like to go. Good planning includes maintenance, replacement and what to do when the equipment breaks down.",
        "ask" => [
            "Can a therapist assess how I move and where I use the equipment?",
            "Can I trial different types before I decide?",
            "How will the equipment be fitted and adjusted for me?",
            "What training will I get to use it safely?",
            "How is servicing arranged, and what happens if it breaks?",
            "How will we check that it still suits me as my needs change?",
        ],
        "mistakes" => [
            "Buying equipment without a proper assessment or trial.",
            "Not checking that it fits through doors, in the car and in the places you go.",
            "Skipping training on safe use, including on slopes and kerbs.",
            "Neglecting servicing until something fails.",
            "Not reviewing the equipment as your needs change.",
        ],
        "faq" => [
            ["How do I know which mobility aid is right for me?", "A physiotherapist or occupational therapist can assess how you move and recommend options. Trying different aids in real situations helps you decide."],
            ["How often should mobility equipment be serviced?", "It depends on the item and how much you use it. The supplier can tell you the recommended schedule, and it is wise to check brakes, tyres and joints regularly."],
            ["What if my needs change?", "Contact your therapist for a review. Equipment can often be adjusted, or replaced with something more suitable."],
        ],
    ],
    "Music therapy and art therapy" => [
        "day" => "A music or art therapy session takes place in a safe, private space, either one to one or in a small group. The therapist invites you to make or listen to music, or to draw, paint, sculpt or work with other materials. You do not need any skill or experience, because the focus is on the process, not the result.\n\nAfter the activity, you may talk about what you made or how it felt, or you may simply reflect quietly. The therapist observes and responds, and over time helps you work on goals such as communication, emotional expression, confidence, movement or relationships. Sessions are often adapted to suit a person's abilities and sensory needs.",
        "who" => "Registered music therapists and art therapists have specialist postgraduate training and belong to professional associations that set standards. Ask about their qualifications, registration with the relevant association and experience with your age group and needs. These therapies are different from music lessons or art classes, though some people enjoy both.",
        "fit" => "Creative therapies often work alongside other therapies, counselling and community activities. They can be especially helpful for people who find it hard to express themselves in words, and for children and young people. Many people use them to build confidence and connection, which helps in other parts of life.",
        "ask" => [
            "What qualifications and professional registration do you hold?",
            "Do you have experience with my age group and needs?",
            "How will sessions be tailored to my abilities and interests?",
            "How will we set goals and measure progress?",
            "Can family or carers be involved?",
            "How is what I create kept private?",
        ],
        "mistakes" => [
            "Expecting a music or art lesson when the aim is therapy.",
            "Not checking the therapist's qualifications and registration.",
            "Feeling that you must be good at the activity, when the process matters most.",
            "Not setting goals, so it is hard to see whether it is helping.",
            "Stopping after one session before you have had a chance to settle in.",
        ],
        "faq" => [
            ["Do I need to be musical or artistic to try these therapies?", "No. The activities are designed for people of all abilities, and the focus is on expression and connection, not skill."],
            ["How is music therapy different from music lessons?", "Music therapy uses music to work on goals such as communication, emotion and movement, guided by a trained therapist. Lessons teach how to play or sing."],
            ["Can these therapies help children?", "Yes. They are widely used with children because they can be playful and do not rely on words, and they can help with communication, social skills and emotional expression."],
        ],
    ],
];
