<?php
/** Long-form guide content, batch 3. See content-long-1.php for the shape. */
if (!defined('ABSPATH')) exit;

return [
    'Group skills development' => [
        'cat' => 'Life skills',
        'short' => 'Group skills development is skill-building delivered in a group, where people learn and practise together. Topics include communication, independence and social confidence.',
        'overview' => "Learning alongside others can make new skills feel less daunting. In a group, people see how others tackle the same challenge, practise together and give and receive encouragement. Programs are usually led by a support worker, therapist or trainer, and run over a series of sessions with a clear focus.\n\nCommon topics include communication and social skills, cooking, managing money, travelling independently, health and wellbeing, and preparing for work or study. Some programs are for a particular age group or interest, such as young adults leaving school, which makes the content more relevant.\n\nA good group balances structure with flexibility. Leaders explain what will be covered, set activities at different levels and check how each person is going, so no one is left behind or held back. It is worth asking how progress is tracked and what happens once the program finishes.",
        'choose' => [
            'Ask how the group is put together and how many people take part.',
            'Find out what qualifications and experience the leaders have.',
            'Check how the program adapts to different abilities and learning styles.',
            'Ask how progress is measured and shared with you.',
            'Find out what happens after the program ends.',
        ],
        'start' => [
            'Decide which skills you want to build.',
            'Look for a group that matches your goals and age.',
            'Ask to visit or speak to the leader before joining.',
            'Set a personal goal and review it at the end of the program.',
        ],
        'faq' => [
            ['What if I feel shy in a group?', 'That is common. Good leaders start gently, let you take part at your own pace and create a friendly atmosphere.'],
            ['Are groups better than one-to-one support?', 'It depends on the person and the goal. Groups suit people who enjoy company and practising with others, while one-to-one suits people who want focused attention.'],
            ['Can I join part-way through?', 'Sometimes. Ask the provider when new groups start and whether you can join an existing one.'],
        ],
    ],
    'Hearing equipment' => [
        'cat' => 'Assistive technology & equipment',
        'short' => 'Hearing equipment helps people who are deaf or hard of hearing, and includes hearing aids, alerting devices and other assistive listening technology.',
        'overview' => "Hearing technology ranges from hearing aids worn in or behind the ear to devices that amplify a television or phone, and alerting systems that use flashing lights or vibrations to signal a doorbell, alarm or baby monitor. Some people use cochlear implants, which are a different kind of technology that a specialist team assesses and provides.\n\nAn audiologist tests your hearing, explains the results and recommends devices that suit your hearing loss, lifestyle and budget. Fitting is a process: devices are programmed to your hearing and adjusted over time as you get used to them and as your needs change.\n\nGetting used to hearing devices takes patience. Wearing them regularly, going back for adjustments and learning how to clean and care for them all help. Ask about follow-up appointments and support, and whether family and workplaces can be shown how to communicate in ways that help you.",
        'choose' => [
            'Ask about the audiologist\'s qualifications and whether they are independent or tied to a brand.',
            'Find out how many devices they can offer and how they choose between them.',
            'Ask about trial periods, warranty and repairs.',
            'Check what follow-up and adjustments are included.',
            'Ask about accessories such as remote microphones and alerting devices.',
        ],
        'start' => [
            'Book a hearing test with an audiologist.',
            'Talk through your situations and priorities, such as work, family or television.',
            'Trial the devices recommended.',
            'Return for adjustments and reviews as you settle in.',
        ],
        'faq' => [
            ['How long does it take to get used to hearing aids?', 'It varies from person to person. Regular wear and follow-up adjustments help, and your audiologist can advise what to expect.'],
            ['Are hearing aids waterproof?', 'Some are more water-resistant than others. Ask your audiologist about care, especially if you swim or work outdoors.'],
            ['Can children use hearing devices?', 'Yes. Children are assessed by audiologists with paediatric experience, and devices are adjusted as they grow.'],
        ],
    ],
    'Hearing services and audiology' => [
        'cat' => 'Therapy services',
        'short' => 'Audiologists test hearing, recommend and fit hearing devices, and give advice on managing hearing loss and related conditions such as tinnitus.',
        'overview' => "An audiologist is a health professional who specialises in hearing and balance. A hearing assessment measures how well you hear sounds at different pitches and volumes and how well you understand speech. The results guide advice about management, which might include devices, communication strategies, protection from noise or referral to a doctor or specialist.\n\nAudiologists also help with related conditions, including tinnitus, which is hearing a sound that is not there, and some balance problems. Children can have their hearing tested from a very young age, and early detection helps with speech and learning.\n\nHearing changes over time, so regular check-ups make sense, especially if you notice changes, use hearing devices or are exposed to loud noise. Ask the clinic what to expect at your first visit and how they explain results in plain language.",
        'choose' => [
            'Check that the audiologist is appropriately qualified and a member of a professional body.',
            'Ask whether the clinic is independent or works with particular brands.',
            'Find out how the results will be explained to you and to family.',
            'Ask whether they can test children and people with additional needs.',
            'Check what follow-up care is offered.',
        ],
        'start' => [
            'Book a hearing test and let the clinic know about any access needs.',
            'Bring a list of questions and a family member if you wish.',
            'Discuss the results and options.',
            'Arrange follow-up and regular reviews.',
        ],
        'faq' => [
            ['What is tinnitus?', 'Tinnitus is hearing a sound, such as ringing or buzzing, when no external sound is present. An audiologist can help you understand and manage it.'],
            ['Can hearing tests be done for babies?', 'Yes. There are tests designed for infants and young children, done by audiologists with the right experience.'],
            ['Is a hearing test painful?', 'No. Most tests are simple and comfortable, involving listening for sounds or responding to speech.'],
        ],
    ],
    'High-intensity personal care' => [
        'cat' => 'Personal care',
        'short' => 'High-intensity personal care involves tasks that need extra skills or training because of complex health needs or added risk. Workers are trained for specific tasks, often under a health professional\'s guidance.',
        'overview' => "Some personal care goes beyond everyday help with showering and dressing. Examples include supporting someone with a tracheostomy, managing certain types of feeding or bowel care, or responding to seizures. These tasks carry more risk if they are not done properly, so workers need specific training and, often, sign-off from a health professional.\n\nTraining is usually tailored to the person. A nurse or other health professional teaches the worker how to carry out the task for that individual, watches them do it and confirms they are competent. The worker follows a written plan, and there is a process for emergencies and for reviewing the plan when the person's health changes.\n\nBecause the stakes are higher, the provider you choose matters. Ask how they train and supervise workers, how they keep records and how they make sure a trained person is always available, including when your regular worker is away.",
        'choose' => [
            'Ask exactly how workers are trained for the tasks you need and who checks their competence.',
            'Find out how often training is refreshed.',
            'Ask what happens if the trained worker is unavailable.',
            'Check their emergency procedures and how they contact your health professionals.',
            'Ask how they keep records and how you can see them.',
        ],
        'start' => [
            'Ask your health professional to write down the tasks and how they should be done.',
            'Share this with providers and ask how they will train staff.',
            'Agree who is trained and how backup is arranged.',
            'Set a date to review the plan and the training.',
        ],
        'faq' => [
            ['Can any support worker do these tasks?', 'No. Workers need specific training for the tasks, and providers should make sure they are competent before they work alone.'],
            ['What if my health changes?', 'Tell your provider and your health professional straight away so the plan and training can be updated.'],
            ['Can family members train the workers?', 'Family often have valuable knowledge, but formal training by a health professional is usually needed. Ask the provider how they combine the two.'],
        ],
    ],
    'Higher education and training support' => [
        'cat' => 'Employment & education support',
        'short' => 'This support helps people studying at university, TAFE or with another training provider, including help with organisation, access needs and study routines.',
        'overview' => "Studying with a disability often involves extra planning. Support might include help with time management, breaking assignments into steps, using assistive technology, getting to campus and building routines that make it easier to keep up. It works alongside the adjustments that your education provider can arrange.\n\nUniversities and TAFEs have disability services that arrange things such as extra time in exams, note-taking, accessible materials and assistive technology. Registering early gives them time to put these in place. Personal support from a provider covers what the institution does not, such as help at home or with getting to and from classes.\n\nIt can be worth thinking about the whole picture: the course, the timetable, travel, living arrangements and finances. A support coordinator or education adviser can help you map it out, and starting early leaves room to fix problems before the semester begins.",
        'choose' => [
            'Ask whether the provider has experience supporting students.',
            'Check how flexible they can be around timetables, exams and placements.',
            'Ask how they will work with your education provider\'s disability service.',
            'Find out how they support the use of assistive technology.',
            'Ask how support can change during busy periods such as assessments.',
        ],
        'start' => [
            'Contact your education provider\'s disability service early.',
            'List the supports you think you will need at home, on campus and online.',
            'Speak to your planner or support coordinator about study supports.',
            'Review how things are going after the first few weeks.',
        ],
        'faq' => [
            ['Who arranges adjustments such as extra exam time?', 'Your education provider does. Register with their disability service and provide documentation about your needs.'],
            ['Can I get support for online study?', 'Yes. Support can help you set up study routines, use assistive technology and stay in touch with your teachers.'],
            ['What if I need to change my course?', 'Talk to your education provider and your support team. Changes can be made, and plans adjusted to match.'],
        ],
    ],
    'Home enteral nutrition (HEN)' => [
        'cat' => 'Nursing',
        'short' => 'Home enteral nutrition is nutrition delivered through a feeding tube at home. It includes the formula and supplies, along with training and guidance from health professionals.',
        'overview' => "Some people cannot eat or drink enough by mouth, or cannot do so safely, and receive nutrition through a tube that goes into the stomach or small intestine. Doing this at home means having the right formula, equipment such as pumps and syringes, and the skills to use it confidently and safely.\n\nA team usually looks after tube feeding. A doctor oversees the medical side, a dietitian works out the formula and routine, a speech pathologist may assess swallowing, and nurses help with tube care and troubleshooting. Family members or support workers are trained to help with day-to-day feeds.\n\nSupplies are commonly delivered to the home, and it is important to know how to reorder, what to do if something runs low or a piece of equipment fails, and who to call out of hours. Regular reviews help make sure the plan still suits the person as their needs change.",
        'choose' => [
            'Ask who will train you and any support workers, and how often the training is refreshed.',
            'Find out how supplies are ordered and delivered and what happens if you run short.',
            'Ask who to call if there is a problem, including out of hours.',
            'Check how the dietitian and other health professionals stay in touch.',
            'Ask about cleaning and storage of equipment.',
        ],
        'start' => [
            'Talk to your doctor and dietitian about the feeding plan.',
            'Arrange training for everyone who will help with feeds.',
            'Set up a supply and delivery arrangement.',
            'Keep a contact list for emergencies and schedule regular reviews.',
        ],
        'faq' => [
            ['Can a person on tube feeding also eat by mouth?', 'Sometimes. It depends on their swallowing and health, so follow the advice of the speech pathologist and doctor.'],
            ['What if the tube comes out?', 'Your health team will give you an emergency plan. Keep the number of who to call and follow their instructions.'],
            ['Can I go out or travel?', 'Many people do. Plan supplies and equipment ahead, and speak to your team about travelling.'],
        ],
    ],
    'House cleaning and household tasks' => [
        'cat' => 'Domestic assistance',
        'short' => 'This support helps with regular cleaning and other household jobs such as laundry, tidying and keeping the home safe and comfortable.',
        'overview' => "A clean, organised home matters for health, safety and wellbeing, yet cleaning and other household jobs can be hard when you have a disability or health condition. A support worker can help with vacuuming, mopping, bathroom and kitchen cleaning, laundry, changing beds and tidying.\n\nYou decide how involved you want to be. Some people prefer tasks to be done for them, while others like to work alongside a worker and keep doing what they can. Being clear about your priorities, such as what must be cleaned and how you like things arranged, helps the worker do the job the way you want.\n\nBecause a worker will be in your home regularly, trust and reliability are important. Ask providers about how they choose and train workers, what checks they carry out and what to do if you are not happy with the standard of work.",
        'choose' => [
            'Ask how often workers visit and how you can change the schedule.',
            'Find out how they choose and vet workers who come into your home.',
            'Check who supplies the cleaning products and equipment.',
            'Ask how they handle allergies and preferences for products.',
            'Find out what happens if your regular worker is away.',
        ],
        'start' => [
            'Write down the tasks you want help with and how often.',
            'Contact providers and ask for availability in your area.',
            'Agree what is included and what is not in your service agreement.',
            'Review after a few visits and adjust the tasks.',
        ],
        'faq' => [
            ['Can I do some of the cleaning myself?', 'Yes. Many people share tasks with a worker or work towards doing more themselves.'],
            ['What if something is damaged?', 'Ask the provider about insurance and how they handle damage. Report anything promptly.'],
            ['Can the worker use my own cleaning products?', 'Usually yes. Tell the worker what you prefer, especially if you have allergies.'],
        ],
    ],
    'Household management' => [
        'cat' => 'Domestic assistance',
        'short' => 'Household management is help with running a home, such as planning meals, shopping, organising bills and keeping routines on track.',
        'overview' => "Running a home involves far more than cleaning. There is meal planning and shopping, keeping on top of bills and mail, arranging repairs, remembering appointments and keeping the household routines working. For some people, the mental load of organising all this is the hardest part.\n\nSupport can be practical, such as going shopping together, or focused on organisation, such as setting up a calendar, a meal plan or a system for paperwork. Some people want a worker to take on tasks, while others want to build their own skills and gradually do more.\n\nHouseholds differ, so the support should reflect yours. If you share with family or housemates, it can help to agree who does what, and to include them in planning so everyone understands how the support will work.",
        'choose' => [
            'Ask whether the provider can support planning and organisation, not only physical tasks.',
            'Check how they handle shopping, including what is done for you and what is done with you.',
            'Find out how they will respect your routines and preferences.',
            'Ask how they keep your information private.',
            'Check how flexible the support is when your needs change.',
        ],
        'start' => [
            'List the household tasks that take the most energy or time.',
            'Decide which you want done for you and which you want to learn.',
            'Agree a simple weekly routine with your provider.',
            'Review regularly and adjust as you settle in.',
        ],
        'faq' => [
            ['Can a worker do my shopping?', 'Often yes, either with you or for you. Discuss how you would like it done and how payments and receipts are handled.'],
            ['Can this include meal planning?', 'Yes. Support can include planning meals, making lists and preparing food.'],
            ['What if my household is busy?', 'Tell your provider how many people live in your home and their routines so support can fit in.'],
        ],
    ],
    'Household task equipment' => [
        'cat' => 'Assistive technology & equipment',
        'short' => 'Household task equipment includes adapted tools and aids that make cooking, cleaning and daily chores easier or possible.',
        'overview' => "Small aids can make a big difference to independence at home. Adapted kitchen equipment, such as easy-grip knives, one-handed chopping boards, jar openers and kettle tippers, helps people cook and prepare food. Reachers, long-handled tools and trolleys help with picking things up, carrying and cleaning.\n\nAn occupational therapist can look at how you do tasks at home and suggest equipment or different ways of working. Sometimes a change of technique or layout does as much as a new gadget, so an assessment can save money and frustration.\n\nWhen buying, try items where you can. What suits one person can be awkward for another, and comfort, weight and grip all matter. Ask about returns, and think about safety, especially with sharp objects, hot liquids and electrical appliances.",
        'choose' => [
            'Ask whether you can try items before buying.',
            'Check the weight, grip and how easy the item is to clean.',
            'Ask about returns and warranty.',
            'Consider safety, especially for hot, sharp or electrical items.',
            'Ask an occupational therapist about layout changes that could help.',
        ],
        'start' => [
            'Identify the tasks you find hardest.',
            'Speak to an occupational therapist about options.',
            'Try a few items and choose what works best.',
            'Review after a few weeks and ask for adjustments if needed.',
        ],
        'faq' => [
            ['Where can I buy adapted household items?', 'Specialist suppliers, pharmacies and some general retailers. An occupational therapist can suggest reliable sources.'],
            ['Are adapted tools expensive?', 'It varies. Some items are inexpensive, and a therapist can help you weigh cost against benefit.'],
            ['Can equipment help me stay safe in the kitchen?', 'Yes. Items such as stable chopping boards and kettle tippers can reduce risks. Ask a therapist for a kitchen safety check.'],
        ],
    ],
    'Housing search and matching' => [
        'cat' => 'Housing (SDA & SIL)',
        'short' => 'Housing search and matching helps you look for a suitable home, understand your options and be matched with a place that fits your needs and preferences.',
        'overview' => "Finding a home that works for you can be a long and confusing process. Housing search support helps you work out what you need, such as location, accessibility, support and cost, and then find places that match. It can include exploring options, applying for properties and understanding what each type of housing offers.\n\nThere is a range of housing types, from private rentals and community housing to shared homes with support and specialised accessible housing. Each has different eligibility rules, waiting lists and costs. A housing support worker can explain how they work and where you might fit.\n\nSuitable housing can be limited, particularly accessible housing in some areas, so patience and flexibility are often needed. Good support keeps your options open, helps you prepare applications and documents and stays in touch while you wait.",
        'choose' => [
            'Ask how the provider finds and assesses housing options.',
            'Check whether they know the local rental and community housing market.',
            'Find out how they help with applications and paperwork.',
            'Ask how they will keep supporting you if the search takes time.',
            'Check how they involve you in decisions.',
        ],
        'start' => [
            'Write down what matters most in a home, such as location, access and support.',
            'Gather documents you may need for applications.',
            'Talk to providers about the housing options in your area.',
            'Agree a plan for searching and staying in touch.',
        ],
        'faq' => [
            ['How long does it take to find housing?', 'It varies a lot, and accessible housing can have long waits. Ask providers to be honest about what is realistic in your area.'],
            ['Can this help me find housing with support?', 'It can help you understand options that include support and how to apply for them.'],
            ['What if I cannot afford the rent?', 'A housing support worker or financial counsellor can talk to you about assistance and options that may be available.'],
        ],
    ],
    'Individualised Living Options (ILO)' => [
        'cat' => 'Housing (SDA & SIL)',
        'short' => 'An Individualised Living Option is a way of designing where and how you live around your own goals and preferences, instead of choosing from existing housing models.',
        'overview' => "Most people think of housing as a choice between living at home with family and moving into a shared home run by a provider. Individualised Living Options open up other possibilities, such as living in your own place with tailored support, sharing with a housemate you choose or living alongside family in a way that gives everyone more freedom.\n\nThe process usually has stages. First there is exploration, where you think about what you want your life to look like and who is important to you. Then comes design, where a provider or coordinator helps you shape a living arrangement and the supports that will make it work. Finally, the arrangement is set up and reviewed as you settle in.\n\nBecause ILO is a newer and more personal approach, it helps to ask providers about their experience and how they involve you. A good provider listens, explains options in plain language and moves at a pace that suits you and your family.",
        'choose' => [
            'Ask about the provider\'s experience with individualised living arrangements.',
            'Find out how they help you explore and design options.',
            'Ask how they involve family, friends and other supporters.',
            'Check how they handle changes if the arrangement is not working.',
            'Ask how the arrangement will be reviewed over time.',
        ],
        'start' => [
            'Think about the kind of home and life you want.',
            'Talk to your planner or support coordinator about home and living supports.',
            'Speak to providers who work in this area.',
            'Agree a step-by-step plan for exploring and setting up your arrangement.',
        ],
        'faq' => [
            ['Do I have to live alone?', 'No. The idea is to design something that suits you, which might mean living with a housemate, family or others.'],
            ['Who helps me design my living arrangement?', 'A provider or coordinator with experience in home and living supports, working with you and your family.'],
            ['Is it available everywhere?', 'Availability varies by area. Ask your planner and local providers what is possible near you.'],
        ],
    ],
];
