<?php
/**
 * Deeper guide content for service posts, batch 7 (companion to content-long-7.php).
 * Same shape as content-deep-1.php. Plain, general guidance only: no prices, no timeframes, no promises about who qualifies.
 */
if (!defined('ABSPATH')) exit;

return [
    "Specialised driver training" => [
        "day" => "Specialised driver training helps people with disability learn to drive, or return to driving, in a way that suits their body and needs. It usually begins with an assessment, often by an occupational therapist who is also a driver rehabilitation specialist. They look at vision, reaction, movement, thinking and health, and advise whether driving is safe and what adaptations might help.\n\nLessons then take place in a suitable vehicle with a qualified instructor, often with modifications such as hand controls or a steering aid. The instructor builds skills step by step, first in quiet areas and then in traffic. Progress is reviewed with the therapist, and licensing requirements are explained along the way.",
        "who" => "Driver rehabilitation specialists are usually occupational therapists with additional training, working with driving instructors experienced in adapted vehicles. Ask about their qualifications, the vehicles they use and how they work with your doctor and the licensing authority. You may also need medical clearance, and the process varies between states.",
        "fit" => "Driver training is linked to vehicle modifications, transport supports and independence. If you are considering driving, it is worth thinking about how you will manage the vehicle, any modifications needed and the cost of running a car. Some people decide after an assessment that other transport options suit them better, and that is a legitimate outcome.",
        "ask" => [
            "Are you an occupational therapist with driver rehabilitation training?",
            "What will the assessment involve, and what will it tell me?",
            "What vehicles and adaptations do you use in lessons?",
            "How will you work with my doctor and the licensing authority?",
            "What happens if the assessment finds that driving is not safe for me?",
            "How will you help me plan for a vehicle and any modifications?",
        ],
        "mistakes" => [
            "Buying or modifying a vehicle before an assessment.",
            "Not checking the licensing and medical requirements in your state.",
            "Assuming any driving instructor can teach with adaptations.",
            "Rushing into traffic before skills are solid.",
            "Not exploring other transport options if driving turns out not to be right.",
        ],
        "faq" => [
            ["Do I need an assessment before driver training?", "In most cases yes. It checks whether driving is safe for you and what adaptations you might need, and it is often a requirement for licensing."],
            ["Can I use hand controls in any car?", "Hand controls need to be fitted and approved for the vehicle, so speak to a specialist before buying a car or having modifications done."],
            ["What if I am told I cannot drive?", "You can discuss other transport options, and in some cases a review later on may lead to a different result. The therapist can explain what can be done."],
        ],
    ],
    "Specialised transport" => [
        "day" => "Specialised transport takes people to and from school, work, appointments and activities when regular transport does not meet their needs. A typical trip starts with a driver or attendant collecting you at the door, helping you into a vehicle that suits your mobility needs and making sure you are safely secured.\n\nDuring the trip, staff are attentive to your comfort, and they can help with communication, behaviour or health needs. They take you to the door of the destination and, where needed, help you inside. Services often run on a regular timetable for school and work, with flexible bookings for appointments.",
        "who" => "Specialised transport is provided by disability transport services, community transport organisations and some schools and workplaces. Drivers and attendants should hold the right licences, screening and training, and vehicles need to be maintained and suitable for wheelchairs or other equipment. Ask about safety standards and what to do if a trip is delayed.",
        "fit" => "Specialised transport works alongside other transport supports such as allowances and activity-based transport. It suits people who cannot use public transport safely or who need equipment or help during the trip. Reliability is important, so it helps to know how a provider handles delays, cancellations and changes.",
        "ask" => [
            "Is the vehicle suitable for my wheelchair or other equipment, and how is it secured?",
            "What training and screening do drivers and attendants have?",
            "How are bookings made, and how much notice is needed?",
            "What happens if the vehicle is late or a driver is unavailable?",
            "Can you support communication or behaviour needs during the trip?",
            "How do you handle cancellations and changes?",
        ],
        "mistakes" => [
            "Not checking that the vehicle is suitable for your equipment.",
            "Booking too late for regular school or work trips.",
            "Not agreeing what happens if a trip is delayed or cancelled.",
            "Not asking about training in safe handling and securing equipment.",
            "Relying on one service with no back-up plan.",
        ],
        "faq" => [
            ["Can specialised transport take me to work or school?", "Many services do, and some run regular routes. Ask about timetables and how a place is reserved."],
            ["Does someone help me get from the door to the vehicle?", "Usually, and it is worth confirming what help is provided before you book."],
            ["What if I feel unwell during the trip?", "Drivers and attendants should be trained to respond and know what to do. Share any health information with the service beforehand."],
        ],
    ],
    "Specialist Disability Accommodation (SDA)" => [
        "day" => "Specialist Disability Accommodation is housing built or modified for people with very high support needs or extreme functional impairment. The home itself is designed to be accessible and to support the delivery of care, with features such as wide doorways, accessible bathrooms, robust construction, assistive technology and space for equipment or support staff.\n\nDaily life is like any home: you live in it, decorate it and have your own space. Personal supports are provided separately by the support providers you choose, so the housing and the support are usually different arrangements. Some homes are shared with others, and some are for one person or a couple.",
        "who" => "SDA housing is offered by registered housing providers, who own or manage the homes. Support in the home is provided by separate support providers, and a support coordinator often helps you find both. Ask about how the home is designed, what tenancy protections apply and how support arrangements work.",
        "fit" => "SDA is one part of a person's housing and support arrangement, and it relates to supported independent living, home modifications and support coordination. It suits only a small group of people with very high needs, so it helps to get advice on whether it is a good option and what other options are available.",
        "ask" => [
            "How is the home designed to support my needs, and can I see it before deciding?",
            "Who owns and manages the property, and what is the tenancy agreement?",
            "How are housemates chosen, if the home is shared?",
            "Can I choose my own support provider, and can I change provider later?",
            "How are repairs and maintenance handled?",
            "What are my rights if I want to move?",
        ],
        "mistakes" => [
            "Assuming SDA is the right option without exploring alternatives.",
            "Not visiting the home or meeting housemates.",
            "Confusing the housing agreement with the support agreement.",
            "Not checking that you can choose and change your support provider.",
            "Not understanding your tenancy rights.",
        ],
        "faq" => [
            ["Who can live in specialist disability accommodation?", "It is intended for people with very high support needs or extreme functional impairment, and eligibility is assessed. Talk to your planner or coordinator about whether it might apply."],
            ["Do I have to use the housing provider's support services?", "You should be able to choose your support provider separately, and that is an important point to check before agreeing to anything."],
            ["Does having SDA mean I also get supported independent living?", "No. SDA is about the building, and supported independent living is about the support provided in the home. They can be used together but are separate."],
        ],
    ],
    "Specialist Positive Behaviour Support" => [
        "day" => "A specialist behaviour support practitioner begins by getting to know the person, their history, their communication and the situations in which behaviours of concern occur. They observe, talk with the person and people who know them well, and gather information about what may be triggering or maintaining the behaviour.\n\nFrom this they write a positive behaviour support plan, which explains the reasons for the behaviour and sets out strategies to prevent it, teach new skills and respond safely. They also train the people who support the person and review the plan regularly. Where restrictive practices are involved, they must follow legal requirements and be reported.",
        "who" => "Behaviour support practitioners need to meet the standards set by the NDIS Quality and Safeguards Commission. They often have backgrounds in psychology, occupational therapy, speech pathology or social work. Ask about their registration status, their experience with your situation and how they involve the person and family.",
        "fit" => "The plan is put into practice by support workers and family, so it connects closely with behaviour support implementation. It also relates to therapy, communication supports and environmental changes, since many behaviours are a response to unmet needs. Regular reviews make sure the plan keeps pace with the person's changing needs.",
        "ask" => [
            "Are you a registered behaviour support practitioner?",
            "How do you find out why the behaviour is happening?",
            "How will the person and their family be involved?",
            "How will the plan be shared and taught to those who support the person?",
            "How do you approach restrictive practices, and how are they reported?",
            "How often will the plan be reviewed?",
        ],
        "mistakes" => [
            "Looking for a quick fix rather than understanding the reasons for the behaviour.",
            "Not involving the person in the plan.",
            "Leaving the plan on a shelf without training the people who support the person.",
            "Using restrictive practices without proper authorisation.",
            "Not reviewing the plan when things change.",
        ],
        "faq" => [
            ["What does positive behaviour support aim to achieve?", "It is an approach that tries to understand why a behaviour happens and to build skills, environments and responses that improve the person's quality of life and reduce the need for the behaviour."],
            ["What is a restrictive practice?", "It is any action that restricts a person's rights or freedom of movement, such as physical restraint or locking a door. There are strict rules about when they can be used and how they are reported."],
            ["Who should see the behaviour support plan?", "The person, their family and the workers who support them need to know the plan and be trained in it. Sharing it is essential for consistency."],
        ],
    ],
    "Specialist Support Coordination (Level 3)" => [
        "day" => "A specialist support coordinator works with people who have complex needs or face significant barriers, such as being at risk of homelessness, in a hospital or in an unsafe situation. Contact may be frequent and involve several people and agencies, so the coordinator keeps a close watch on how things are progressing.\n\nTypical tasks include assessing risks, bringing together the professionals involved, organising urgent supports, solving problems as they arise and building the person's capacity to manage on their own. The work is intensive at first, and the coordinator focuses on stabilising the situation and then on setting up a sustainable arrangement.",
        "who" => "Specialist support coordinators are experienced professionals, often with backgrounds in social work, psychology, occupational therapy or community services. Ask about their experience with people in similar situations, their availability and how they work with other agencies. They should also explain how they will support you to build your own skills.",
        "fit" => "This support sits above the other coordination levels and is used for complex situations. It works with housing services, health services, mental health teams and providers. When the situation is more stable, the arrangement may move to a lower level of coordination, so it helps to agree what success looks like and what the next stage will be.",
        "ask" => [
            "What experience do you have with situations as complex as mine?",
            "How often will we be in contact, and how quickly can you respond?",
            "How will you work with the other services and agencies involved?",
            "What is the plan for stabilising things and then reducing intensive support?",
            "How will you help me build my own skills and confidence?",
            "How do you handle crises or urgent problems?",
        ],
        "mistakes" => [
            "Not agreeing on clear goals for the intensive period.",
            "Leaving other agencies out of the loop.",
            "Not planning for what happens when the coordination reduces.",
            "Assuming the coordinator will do everything for you rather than working with you.",
            "Not being clear about how to contact the coordinator urgently.",
        ],
        "faq" => [
            ["How is specialist support coordination different from ordinary coordination?", "It is for people with more complex needs and higher risks, and involves more intensive work, including bringing together several agencies and resolving urgent problems."],
            ["Will I need this support forever?", "Usually not. The aim is to stabilise the situation and then move to less intensive support as things improve."],
            ["Who decides if I need specialist coordination?", "It is usually decided in the planning process, based on the person's needs and circumstances. Your planner or current coordinator can explain."],
        ],
    ],
    "Speech pathology" => [
        "day" => "A speech pathology session starts with an assessment or a review of progress. The speech pathologist may play, talk, use pictures or apps, or watch you eat and drink, depending on your needs. They assess how you speak, understand language, communicate with others or swallow, and explain what they find.\n\nTherapy is practical and often fun, particularly for children. It might involve exercises for speech sounds, strategies for understanding and using language, work on voice or fluency, or training in using a communication device. For swallowing difficulties, the speech pathologist gives advice on safe ways of eating and drinking. Home practice is a large part of progress.",
        "who" => "Speech pathologists have university degrees and are members of Speech Pathology Australia, which sets standards for practice. Many specialise in areas such as child language, stuttering, voice, swallowing or augmentative communication. Ask about experience in your area of need, and whether they can work in your home, school or workplace.",
        "fit" => "Speech pathology works with occupational therapists, psychologists, teachers, dietitians and doctors. For communication difficulties, it links with communication equipment and training for family and support workers. For swallowing difficulties, it works with dietitians and nurses. Keeping everyone informed of the strategies helps the person use them everywhere.",
        "ask" => [
            "What experience do you have with my area of need or with my age group?",
            "What will the assessment involve, and what will happen afterwards?",
            "How will you involve family, teachers or support workers?",
            "What home practice will be involved?",
            "Can you see me at home, school or work?",
            "How will we measure progress?",
        ],
        "mistakes" => [
            "Waiting to see whether a child will grow out of a speech or language difficulty.",
            "Not doing the practice between sessions.",
            "Ignoring signs of swallowing problems such as coughing when eating.",
            "Not sharing strategies with the people around the person.",
            "Not asking about communication devices when speech is very hard.",
        ],
        "faq" => [
            ["What does a speech pathologist treat?", "They treat difficulties with speech, language, voice, fluency, communication and swallowing, in both children and adults."],
            ["When should I take my child to a speech pathologist?", "If you are concerned about your child's speech or language, or if others do not understand them, an assessment is a good idea. Early support often makes a difference."],
            ["Can speech pathology help with swallowing problems?", "Yes. Speech pathologists assess swallowing and advise on safer ways to eat and drink, often in partnership with doctors and dietitians."],
        ],
    ],
    "Study and learning skills" => [
        "day" => "A study skills session focuses on how you learn and what gets in the way. A tutor or therapist helps you work out methods for reading, note-taking, planning assignments, managing time and preparing for exams. They try different approaches with you and keep the ones that work.\n\nSessions are often practical, using real coursework or tasks so that what you learn can be applied straight away. A good tutor helps you understand the reasons behind the methods, so that you can adapt them yourself, and encourages you to seek adjustments from your school or university when needed.",
        "who" => "Study support is provided by tutors, learning support specialists, occupational therapists and psychologists. Some education providers also have learning support services. Look for someone who has experience with your kind of learning needs and who respects your strengths.",
        "fit" => "This support works alongside school or university disability services, higher education support and assistive technology. Learning skills also help in work and everyday life. It helps to keep the education provider informed so that adjustments and support are consistent.",
        "ask" => [
            "How will you work out what gets in the way of my learning?",
            "Will you use my actual coursework and assignments?",
            "How will you help me plan and manage my time?",
            "Can you help me find and use assistive technology?",
            "How will you work with my school or university?",
            "How will we measure progress?",
        ],
        "mistakes" => [
            "Using the same study methods that have not worked before.",
            "Leaving assignments and revision until the last minute.",
            "Not asking the education provider for adjustments.",
            "Not using assistive technology that could help.",
            "Not building skills that last beyond the current course.",
        ],
        "faq" => [
            ["Can study skills support help with exams?", "Yes. Tutors can help you plan revision, practise exam techniques and arrange adjustments such as extra time."],
            ["Do I need a diagnosis to get study support?", "Not always, but some adjustments from schools and universities require documentation. The disability service can explain what they need."],
            ["Is this only for university students?", "No. It is useful at school, in vocational training and in university."],
        ],
    ],
    "Support Connection (Level 1)" => [
        "day" => "Support connection is the entry level of coordination. A connector helps you understand your plan and find the providers and community supports you want to use. Early meetings focus on your goals, what you want to try, and how to turn your budget into services.\n\nThey may help you compare providers, arrange first meetings and make sense of service agreements. The aim is for you to gain the confidence and knowledge to manage your own supports. Contact is lighter than higher levels of coordination, and the connector encourages you to take the lead.",
        "who" => "Support connectors are often part of local organisations or coordination teams, and may have backgrounds in community services or disability support. Ask about their local knowledge and how they help people make informed choices. It is best to work with someone who explains the system in plain language.",
        "fit" => "Connection sits at the start of the coordination path, and some people later move to a higher level if their needs are more complex. It works with plan management, providers and community services. It is useful to be clear about what you want to achieve in the period, so you can tell when it has worked.",
        "ask" => [
            "How will you help me understand my plan and what I can use it for?",
            "How do you help me find and compare providers?",
            "How will you build my skills and confidence to manage on my own?",
            "How do you keep in touch, and how quickly do you respond?",
            "What happens if my needs turn out to be more complex than expected?",
            "How will we know when the support has done its job?",
        ],
        "mistakes" => [
            "Expecting the connector to do everything instead of building your own skills.",
            "Not being clear about your goals.",
            "Choosing providers without comparing options.",
            "Not asking about how the connector is paid, or about conflicts of interest.",
            "Not moving to a higher level of support when it is needed.",
        ],
        "faq" => [
            ["What is the difference between support connection and support coordination?", "Connection is the lighter level and focuses on helping you understand your plan and find supports. Coordination goes further, with more help in managing supports and resolving problems."],
            ["Does a connector choose my providers?", "No. They help you find and compare providers, but the choice is yours."],
            ["Will I still need help after this stage?", "That depends on how you go. Some people are ready to manage on their own, while others continue with coordination."],
        ],
    ],
    "Support Coordination (Level 2)" => [
        "day" => "A support coordinator helps you to put your plan into action. They talk with you about your goals, help you find and choose providers, set up service agreements and check that supports are being delivered. They make phone calls, arrange meetings and keep an eye on your budget.\n\nContact is regular, and the coordinator is a person to turn to if something is not working. They help resolve problems with providers, prepare for plan reviews and gather evidence about how supports are helping. Over time they help you build your capacity to manage your own supports.",
        "who" => "Support coordinators come from a range of backgrounds and work in organisations of different sizes. They should be knowledgeable about the local area, listen to your goals and act in your interests. Ask about conflicts of interest, since some coordinators work for organisations that also provide services, and be sure you know that you can choose freely.",
        "fit" => "Coordination works with plan management, therapy, housing, community access and almost everything else in your plan. It is a bridge between you and the services you use. Having a coordinator you trust makes a big difference, so it is worth asking to meet more than one before choosing.",
        "ask" => [
            "How will you find out what I want and turn it into a plan?",
            "Do you or your organisation provide other services, and how do you avoid conflicts of interest?",
            "How often will we be in touch, and how quickly do you respond?",
            "How will you help me if a provider is not delivering?",
            "How will you prepare me for my plan review?",
            "How will you help me build my own skills?",
        ],
        "mistakes" => [
            "Not asking about conflicts of interest.",
            "Being unclear about your goals, so the coordinator guesses.",
            "Leaving problems with providers to build up.",
            "Not keeping records of what has been agreed.",
            "Staying with a coordinator who is not responsive.",
        ],
        "faq" => [
            ["What should I look for when choosing a support coordinator?", "Meet a few if you can, ask about their experience, how they communicate and any conflicts of interest, and choose someone you trust and feel comfortable with."],
            ["Can I change my support coordinator?", "Yes, you can change if the arrangement is not working, and the process is usually straightforward. Check any notice requirements in your agreement."],
            ["What if my coordinator also provides services?", "It is not necessarily wrong, but you should be told about it and be free to choose other providers. Ask how they manage the situation."],
        ],
    ],
    "Supported Independent Living (SIL)" => [
        "day" => "In supported independent living, workers help you live in your own home, often a shared house, by providing help with daily tasks. A typical day may include help getting up, personal care, preparing meals, taking medication, going to work or activities and relaxing at home. Support is arranged around your routines and preferences, and workers are present at agreed times.\n\nA good service treats the house as your home, not a facility. You choose how to decorate your room, who visits and how you spend your time. Staff work in teams and record what happens, and a manager keeps in touch with you and your family to make sure the arrangement is working.",
        "who" => "SIL is provided by registered disability providers who employ teams of support workers and coordinators. The provider is responsible for staffing, training and rosters, and the housing may be arranged separately with a landlord or housing provider. Ask about staff turnover, training and how the provider gets to know each person.",
        "fit" => "SIL relates to housing options such as SDA and to daily living supports, therapy and community access. Because it is such a large part of your life, it is worth being clear about who provides the housing and who provides the support, and how the arrangements can be changed. Regular reviews are important as needs change.",
        "ask" => [
            "How are staff rostered, and how do you keep the team consistent?",
            "How do you decide on housemates, and can I meet them first?",
            "How can I have a say in the running of the house?",
            "What is the tenancy arrangement, and how is it separate from the support agreement?",
            "How do you handle disagreements and complaints?",
            "What happens if I want to change provider or move?",
        ],
        "mistakes" => [
            "Choosing a home without meeting the housemates and staff.",
            "Not understanding the difference between the tenancy and the support agreement.",
            "Not asking about staffing levels and turnover.",
            "Accepting house rules that limit your choices without question.",
            "Not knowing how to make a complaint.",
        ],
        "faq" => [
            ["How does SIL relate to specialist disability accommodation?", "SIL is the support provided in the home, and SDA is specially designed housing. Someone might have one, both or neither."],
            ["Can I live alone with SIL?", "SIL is often used in shared homes, but individual arrangements are possible in some cases. Discuss options with your coordinator."],
            ["Can I choose my own support workers?", "You should have a say. Ask the provider how workers are matched and how you can request changes."],
        ],
    ],
    "Supported employment" => [
        "day" => "Supported employment provides paid work in a setting designed to accommodate different levels of support. This might be a business that employs people with disability, or a role in a regular workplace with ongoing help. Workers do real jobs, such as packing, cleaning, gardening, hospitality or office work, and receive support to do them well.\n\nA supervisor or coach is available throughout the working day to help with tasks, communication and problems that come up. Roles are matched to the person's skills and interests, and there is often room to build skills and move into other roles. Work is paid and comes with the rights and conditions of any employee.",
        "who" => "Supported employment is provided by disability enterprises and specialised employment providers. Some are large organisations and others are small businesses with a social purpose. Ask about wages, conditions, the type of work and how people are supported to progress to other jobs if they wish.",
        "fit" => "Supported employment works with training, job coaching and community participation. Some people work in supported employment as a long-term career, while others use it as a stepping stone to open employment. It is worth talking with the provider about your goals and how they help people move on if that is what you want.",
        "ask" => [
            "What types of work do you offer, and how are people matched to roles?",
            "How is pay decided, and what rights and conditions do employees have?",
            "How much support is available on the job?",
            "Can people move to other jobs or open employment if they choose?",
            "How is safety managed in the workplace?",
            "How do you involve employees in decisions?",
        ],
        "mistakes" => [
            "Accepting a role without understanding the pay and conditions.",
            "Not asking about opportunities for growth.",
            "Not visiting the workplace first.",
            "Not raising concerns about safety or treatment.",
            "Assuming supported employment is the only option.",
        ],
        "faq" => [
            ["Is supported employment real paid work?", "Yes. Employees receive wages and have workplace rights, though pay arrangements vary. Ask the provider to explain how wages are set."],
            ["Can I move from supported employment to open employment?", "Many people do, and providers may help with the transition. Tell the provider if this is your goal."],
            ["What kinds of jobs are available?", "They vary by provider and can include manufacturing, packing, gardening, cleaning, hospitality and office work."],
        ],
    ],
];
