<?php
/**
 * Deeper guide content for service posts, batch 6 (companion to content-long-6.php).
 * Same shape as content-deep-1.php. Plain, general guidance only: no prices, no timeframes, no promises about who qualifies.
 */
if (!defined('ABSPATH')) exit;

return [
    "Psychosocial Recovery Coaching" => [
        "day" => "A recovery coach works alongside you to build the life you want while living with a psychosocial disability. Meetings might happen at home, in a cafe or on a walk, and they focus on what matters to you, such as routines, relationships, work, study or managing difficult days. The coach listens first and helps you set goals in your own words.\n\nSupport is practical and strengths-based. A coach might help you plan the week, prepare for an appointment, try something new or work out what to do when things get hard. They also help you connect with services and community groups, and encourage you to make your own decisions, even when the path is not straight.",
        "who" => "Recovery coaches often have training in mental health, community services or lived experience of recovery. Some are peer workers who have their own experience of mental health challenges. Ask about their approach, how they work with your other supports, and whether they have experience with your particular situation.",
        "fit" => "Recovery coaching works with your doctor, psychologist, support coordinator and community supports. It is one part of a broader effort to help you live well, alongside treatment and everyday support. Because recovery is personal and often not linear, the plan should be flexible and reviewed as your needs and goals change.",
        "ask" => [
            "How do you work with me to set goals and decide what to focus on?",
            "What training or lived experience do you have?",
            "How do you support me on difficult days?",
            "How will you work with my doctor, psychologist and other supports?",
            "What happens if I am in crisis or feel unsafe?",
            "How will we review whether the coaching is helping?",
        ],
        "mistakes" => [
            "Expecting a straight line of progress, when setbacks are a normal part of recovery.",
            "Setting goals that come from others rather than from you.",
            "Not telling the coach about a crisis plan or what helps when you are unwell.",
            "Keeping supports separate, so no one has the full picture.",
            "Stopping support at the first good stretch, before routines are secure.",
        ],
        "faq" => [
            ["What is psychosocial recovery coaching?", "It is support that helps people living with a psychosocial disability work toward their own goals, build skills and connect with community. The focus is on recovery as defined by the person."],
            ["Is a recovery coach the same as a therapist?", "No. A coach helps with everyday life and goals, while a therapist provides treatment. They can work together."],
            ["What if I am in crisis?", "A coach can help you use your crisis plan and contact the right services, but they are not an emergency service. In an emergency, call the appropriate emergency number or go to a hospital."],
        ],
    ],
    "Recreation equipment" => [
        "day" => "Choosing recreation equipment starts with a conversation about what you love to do or want to try, such as swimming, cycling, fishing, sport, gardening or music. A therapist or specialist supplier can then suggest equipment that makes it possible, such as adapted bikes, hand cycles, beach wheelchairs, adapted fishing gear or modified controllers.\n\nMost people benefit from trying equipment before committing, often through a trial, a demonstration day or a club that lends items. Once you have it, someone shows you how to use it safely, and you can practise in a supportive setting. Joining a group or club that uses similar equipment can make a big difference.",
        "who" => "Occupational therapists, physiotherapists and specialist suppliers advise on recreation equipment. Sports and recreation organisations often have expertise, and many run programs for people with disability. Ask about experience with your activity and whether the equipment can be trialled.",
        "fit" => "Recreation equipment supports community participation and health, and it works alongside group programs, community access and therapy. It is worth thinking about where you will use it, how you will transport and store it and whether a club or program can help you get started.",
        "ask" => [
            "What equipment would make my chosen activity possible and enjoyable?",
            "Can I try it before I decide?",
            "How will I learn to use it safely?",
            "How will I transport and store it?",
            "Are there clubs or programs that could help me get started?",
            "How is the equipment maintained and repaired?",
        ],
        "mistakes" => [
            "Buying expensive equipment without trying it.",
            "Not thinking about transport and storage.",
            "Skipping safety training or protective gear.",
            "Doing the activity alone before you feel confident.",
            "Not connecting with a group or club that could support you.",
        ],
        "faq" => [
            ["Where can I try recreation equipment?", "Some sporting organisations, disability groups and specialist suppliers run trial days or lend equipment. A therapist can help you find them."],
            ["Can adapted equipment be used for competitive sport?", "Often yes, and there are adaptive sports for many activities. Local clubs and state sporting bodies can tell you what is available."],
            ["Does recreation equipment need servicing?", "Many items do, especially those that move or bear weight. Ask the supplier about maintenance."],
        ],
    ],
    "Recurring transport allowance" => [
        "day" => "A recurring transport allowance helps with the ongoing costs of getting around when disability affects how you travel to work, study or community activities. It is not a service delivered by a worker, but a regular contribution toward transport costs. You use it for the kinds of travel it is intended for, and keep records as needed.\n\nDay to day, this might mean using the allowance for taxis, ride-share, a vehicle you are able to use or other approved options, depending on your circumstances and how it is set up. It is worth checking with your planner or coordinator what you can use it for and what records you need to keep.",
        "who" => "There is no provider in the usual sense. Your planner, support coordinator or plan manager can explain how the allowance works in your plan and how to use it. If you are unsure whether a particular trip qualifies, ask before you rely on it.",
        "fit" => "The allowance sits alongside other transport supports such as activity-based transport, specialised transport and driver training. It helps to think about how these fit together. For example, you may use the allowance for regular trips to work and a transport service for community activities.",
        "ask" => [
            "What kinds of travel can I use the allowance for?",
            "What records do I need to keep?",
            "How does it work with other transport supports in my plan?",
            "Who can I ask if I am unsure whether a trip is covered?",
            "What happens if my travel needs change?",
            "How can I review whether the allowance is meeting my needs?",
        ],
        "mistakes" => [
            "Using the allowance for travel it was not designed to cover.",
            "Not keeping records of how it is used.",
            "Assuming it will cover all transport costs without checking.",
            "Not raising a change in travel needs before a review.",
            "Overlooking other transport supports that may suit some trips better.",
        ],
        "faq" => [
            ["Is the transport allowance the same as a transport service?", "No. An allowance is a regular contribution toward your own transport costs, while a transport service is a provider taking you where you need to go."],
            ["Which records should I keep when I use the allowance?", "Keeping records is sensible, and your planner or plan manager can tell you what is needed."],
            ["Can I use it to buy a car?", "It is not designed for that. If you need a vehicle or modifications, ask your planner or therapist about the supports that cover vehicles."],
        ],
    ],
    "School Leaver Employment Supports (SLES)" => [
        "day" => "School leaver employment supports help young people move from school into work. A typical program might begin in the final years of school with work experience, trying different jobs and learning about workplace expectations. After school, the focus turns to finding a job that suits, with help for the young person to build skills, confidence and connections.\n\nSupport may include exploring interests, practising interviews, travelling to a workplace, learning on the job with a coach and talking with an employer about adjustments. Families are often closely involved, and the program works with the school, so that the move from school to work feels planned and not sudden.",
        "who" => "SLES is delivered by employment providers and specialist services with experience helping young people. Look for staff who understand both education and employment, take the young person's ideas seriously and involve the family respectfully. Ask how they work with schools and local employers.",
        "fit" => "This support works alongside school transition planning, job coaching, training and community participation. Because the goal is a real job or a route into work, it is worth asking about the employers and industries the provider works with and how they help people stay in work after they start.",
        "ask" => [
            "How do you help young people work out what kind of job suits them?",
            "How do you work with the school and family before and after leaving?",
            "What kinds of employers and jobs have you helped people find?",
            "How is support provided in the workplace, and how does it reduce over time?",
            "What happens if the first job does not work out?",
            "How will we review progress and adjust the plan?",
        ],
        "mistakes" => [
            "Waiting until the final term of school to start planning.",
            "Choosing a job because it is available rather than because it suits.",
            "Not involving the young person in decisions.",
            "Overlooking practical issues such as transport to work.",
            "Ending support too soon after the young person starts a job.",
        ],
        "faq" => [
            ["When should planning for life after school begin?", "The earlier the better. Work experience and conversations about goals can begin in the final years of school, so that plans are ready when school ends."],
            ["Is this only for people who want full-time work?", "No. The aim is a pathway that suits the young person, which might include part-time work, further training or a mix of activities."],
            ["How can families help?", "Families can share what they know about the young person's strengths, help with travel and routines and stay in touch with the provider and school."],
        ],
    ],
    "Self-management training" => [
        "day" => "Self-management training helps you take charge of your own supports and plan. Sessions cover practical things such as understanding your budget, choosing and directing providers, writing shift instructions, handling invoices and knowing your rights. A trainer or coach explains the ideas, uses real examples and helps you practise with your own situation.\n\nThe pace is yours. Some people want to manage every detail, while others prefer to manage some things and have help with others. The training aims to build the confidence to decide what you want to do and to ask for help where you need it, without feeling that you have to do everything alone.",
        "who" => "Training is provided by coaches, support coordinators, peer mentors and specialist organisations. Peers who manage their own supports can be especially helpful because they know the practical realities. Ask about the trainer's experience and whether the training can be tailored to your situation.",
        "fit" => "Self-management training fits with support coordination and plan management, since many people combine training with a coordinator or plan manager who handles some tasks. It also links with financial skills and daily living skills. Knowing how to manage supports helps you keep control when things change.",
        "ask" => [
            "What will the training cover, and can it be tailored to my situation?",
            "Will I be shown how to use real forms, systems and records?",
            "Can I speak with someone who manages their own supports?",
            "What help is available if I get stuck later on?",
            "How does self-management work alongside a plan manager or coordinator?",
            "How will I know when I feel ready to take on more?",
        ],
        "mistakes" => [
            "Taking on all the tasks at once instead of building up gradually.",
            "Not keeping records of agreements and invoices.",
            "Not learning what your rights and responsibilities are.",
            "Not having a back-up plan when you are unwell.",
            "Not asking for help early when something becomes confusing.",
        ],
        "faq" => [
            ["What does managing my own supports actually involve day to day?", "It means you make the decisions about your supports and manage aspects such as choosing providers, agreeing services and dealing with invoices. The details depend on how your plan is managed."],
            ["Can I combine self-management with help?", "Yes. Many people manage some parts themselves and use a plan manager or coordinator for others."],
            ["Is training only for people who manage their own funds?", "No. It can help anyone who wants to feel more in control of their supports, whichever way their plan is managed."],
        ],
    ],
    "Short Term Accommodation (STA) / respite" => [
        "day" => "A short stay gives you a break in a different setting, or gives your family or carers a break. It might be a few nights in an accommodation house, a stay in a supported holiday home or a planned weekend away. Staff help with daily needs, and you can take part in activities, relax or try new things.\n\nA good stay is planned ahead. You meet the staff or visit before you go, share information about your routines and needs, and pack familiar items. During the stay, workers follow your care plan, and afterwards they share how it went with you and your family. For many people, a positive experience makes it easier to plan more breaks.",
        "who" => "Short term accommodation is provided by disability service providers with staff trained to support guests with different needs. Ask about staff ratios, training and experience with your needs, and whether the same staff are usually there. It helps if the provider can offer a visit or a trial stay first.",
        "fit" => "Respite works with the ongoing support you already have, and it gives the people around you a break as well. It can be planned as part of a regular routine, or used for particular times such as when a carer is unwell. Thinking ahead about transport, medication and communication makes stays easier.",
        "ask" => [
            "Can I visit or meet staff before a stay?",
            "How do you learn about my needs, routines and preferences?",
            "What training do staff have for my particular needs?",
            "How do you manage medication, meals and personal care during the stay?",
            "What is your emergency procedure, and how do you contact my family?",
            "How do you share how the stay went afterwards?",
        ],
        "mistakes" => [
            "Going into a first stay without a visit or any preparation.",
            "Not sharing enough about routines and communication needs.",
            "Overlooking medication and health information.",
            "Booking too late, when places are hard to find.",
            "Not asking about how the person will feel and how they will be supported to settle in.",
        ],
        "faq" => [
            ["How can I prepare for a first stay?", "Visit beforehand if you can, pack familiar items, share a written summary of routines and needs and start with a short stay so you can see how it goes."],
            ["Can a stay be booked in an emergency?", "Some providers can, but availability varies. It helps to know who to call, and to have information ready in advance."],
            ["Is short term accommodation the same as respite?", "The terms overlap. Respite means a planned break for the person or their carers, and short term accommodation is one way of providing it."],
        ],
    ],
    "Skill-building camps and classes" => [
        "day" => "A camp or class brings people together for a period of learning and activity. A camp may run over several days and include outdoor activities, teamwork, cooking and independence skills. A class is usually a regular session focused on a particular skill, such as art, cooking, computers, money or sport.\n\nFacilitators guide people through the activities, adapt tasks to different abilities and make sure everyone can take part. There is usually a mix of learning and fun, and the social side can be as valuable as the skills. Participants often leave with new friends, more confidence and ideas they can use at home.",
        "who" => "Camps and classes are run by disability service providers, community organisations, sporting groups and educators. Staff should be trained and screened, and there should be enough of them to support everyone safely. Ask about the mix of participants, how needs such as medication and personal care are handled, and what the program includes.",
        "fit" => "Camps and classes complement one-to-one support, giving people a chance to practise skills in a group and meet others. They link with social activities, life skills programs and community access. It is worth asking how the skills learned will be carried over into everyday life.",
        "ask" => [
            "What will the camp or class cover, and who is it designed for?",
            "How many participants and staff are there?",
            "How do you manage personal care, medication and health needs?",
            "How do you support people who feel nervous or homesick?",
            "How will the skills be carried over into daily life?",
            "What is your safety and emergency procedure?",
        ],
        "mistakes" => [
            "Choosing a camp that does not suit the person's age or interests.",
            "Not checking staff ratios and training.",
            "Not sharing health and support needs in advance.",
            "Not planning how skills will be practised afterwards.",
            "Not preparing the person for what to expect.",
        ],
        "faq" => [
            ["What if I feel nervous about going to a camp?", "That is understandable. Ask about visiting first, talk with staff about your concerns and start with a shorter program if you can."],
            ["Are camps only for young people?", "No. There are camps and classes for different ages, so ask the provider who the program is designed for."],
            ["What should I pack for a camp?", "The provider will give you a list, but usually it includes medication, comfortable clothes, any equipment you use and a few familiar items."],
        ],
    ],
    "Skill-building community access" => [
        "day" => "In this kind of support, a worker helps you learn skills while you are out in the community, such as catching a bus, ordering at a cafe, using an ATM, shopping for groceries or joining a class. The worker first shows you how, then does it alongside you, then steps back and lets you try on your own.\n\nEach outing has a goal. You and the worker agree what you want to be able to do, keep a note of how it went and build up from simple to more challenging tasks. Over time, the aim is that you need less support and can do more independently or with the help of people naturally in your community.",
        "who" => "Skill-building community access is provided by support workers with experience in teaching skills, and often guided by an occupational therapist or another professional. Choose a worker who is patient, encouraging and takes a teaching approach rather than doing things for you.",
        "fit" => "This support connects with daily living skills, transport, community participation and employment preparation. It suits people who want to become more independent in community settings. Reviewing progress regularly helps you see how far you have come and choose the next goals.",
        "ask" => [
            "How will we choose which skills to work on?",
            "How will you teach me, and how will you reduce your support over time?",
            "How will we record and review my progress?",
            "What will you do if I find something too hard?",
            "How do you help me practise skills between outings?",
            "How will you help me use these skills without a support worker?",
        ],
        "mistakes" => [
            "Having the worker do tasks for you instead of teaching you.",
            "Setting goals that are too big to reach.",
            "Not practising between sessions.",
            "Not recording progress, so it feels like nothing is changing.",
            "Not linking the skills to something you want, such as work or study.",
        ],
        "faq" => [
            ["What is the difference between community access and skill-building community access?", "Community access is about taking part in activities. Skill-building access has a focus on learning specific skills while you are out and about, with the aim of increasing independence."],
            ["How long will I need a worker for each skill?", "It depends on the skill and how quickly you learn. The aim is for support to gradually reduce."],
            ["Can we practise skills in the places I actually use?", "Yes, and it is best to do so. Practising where you will use the skill helps it stick."],
        ],
    ],
    "Social and recreation activities" => [
        "day" => "Social and recreation activities are the fun part of life: a movie night, a sports team, a walking group, a craft class, a trip to the beach or a meal with friends. A worker or group leader helps to make it possible, by organising the activity, providing transport or helping with communication and personal care.\n\nSome activities are run for groups of people with disability, and others are in mainstream community groups with a support worker helping you take part. Either way, the focus is on enjoyment, friendship and trying things. Most people find that regular contact with others makes them feel more connected.",
        "who" => "Activities are organised by disability providers, community groups, clubs and councils. Support workers help people take part in mainstream activities, and coordinators help find activities that fit your interests. Ask about the range of activities and whether you can try one before signing up.",
        "fit" => "Social and recreation activities link with community access, transport, group programs and recreation equipment. Being part of a group can also lead to friendships and roles in the community. It is worth thinking about your interests, and whether a mix of group and individual activities would suit you.",
        "ask" => [
            "What activities are on offer, and can I suggest my own?",
            "Can I try an activity before committing?",
            "How does the group support people with different needs?",
            "How does transport work for getting there and back?",
            "How do you help people make friends?",
            "How much notice do you need for changes or cancellations?",
        ],
        "mistakes" => [
            "Joining only because a friend did, without checking that you like the activity.",
            "Not asking about the costs of activities, such as tickets and food.",
            "Overlooking transport.",
            "Giving up after the first session because it feels awkward.",
            "Sticking to the same group when you want something new.",
        ],
        "faq" => [
            ["Can I join an ordinary community group with a support worker?", "Yes, and many people do. A worker helps you take part, and over time you may need less support as you get to know others."],
            ["What if I do not know what I like?", "Try a few different things. A coordinator or worker can suggest options and help you try them out."],
            ["Who pays for the activity itself?", "Usually the person pays for tickets, fees and food, while the support pays for the help you receive. Check with the provider so it is clear."],
        ],
    ],
    "Social skills and relationship development" => [
        "day" => "Sessions focus on the skills that help people connect, such as starting conversations, listening, reading body language, managing feelings, making and keeping friends and understanding boundaries. A therapist or facilitator uses role play, discussion, practice and real-life outings to help people try things in a safe setting.\n\nWork can be one to one or in a group. Groups let people practise with others and see that they are not alone, while one-to-one sessions allow more tailored attention. Families and carers may be invited to learn what is being taught so they can encourage skills at home.",
        "who" => "Social skills support is provided by psychologists, occupational therapists, speech pathologists, social workers and trained facilitators. For some people, a specialist with experience of autism, intellectual disability or mental health is particularly helpful. Ask about their approach, their experience with your age group and how they involve family.",
        "fit" => "This support links with counselling, group activities, communication therapy and community participation. It is most useful when the skills learned are practised in real life, so it helps to plan how to use them at school, work and in the community. Relationship skills also include safety, consent and boundaries, which are important topics for everyone.",
        "ask" => [
            "How will you find out what I want to work on?",
            "Will the work be one to one, in a group, or both?",
            "How will you help me practise in real situations?",
            "How do you cover topics such as boundaries, consent and staying safe?",
            "How will you involve my family or carers?",
            "How will we know whether it is helping?",
        ],
        "mistakes" => [
            "Expecting a group to fix things without any practice in real life.",
            "Making the person feel there is something wrong with them, instead of building on their strengths.",
            "Not covering safety, consent and boundaries.",
            "Not involving people who can encourage the skills at home.",
            "Stopping too soon, before skills are used naturally.",
        ],
        "faq" => [
            ["Is social skills support only for children?", "No. Programs exist for children, teenagers and adults, and the content is tailored to the stage of life."],
            ["Is one-to-one or group support better?", "Each has advantages. Groups offer practice with others, and one-to-one offers personalised attention. Many people use both."],
            ["Can this help with dating and relationships?", "Yes, many programs cover friendships, dating, respect, consent and safety. It helps to choose a provider who addresses these topics openly and respectfully."],
        ],
    ],
    "Social work" => [
        "day" => "A social work appointment usually starts with listening to your situation and what matters to you. The social worker asks about your circumstances, relationships, housing, money, health and supports, and looks for ways to improve things. They may help you understand your options, connect you with services and speak up for you when you need it.\n\nSupport can involve practical steps, such as completing applications, arranging services or organising a family meeting, as well as emotional support in difficult times. Social workers also work with families and carers, and can help with complex situations that involve several agencies.",
        "who" => "Social workers hold a recognised university qualification and many are members of the Australian Association of Social Workers. Some specialise in areas such as health, mental health, child protection, aged care or disability. Ask about experience with your situation, and how they work with other professionals and services.",
        "fit" => "Social work supports work alongside support coordination, counselling, health services and advocacy. Because a social worker takes a broad view of a person's life, they can be helpful when several problems overlap. It is useful to be clear about what you want them to help with and how they will keep you informed.",
        "ask" => [
            "What qualifications do you have, and are you a member of the professional association?",
            "Do you have experience with situations like mine?",
            "How will you help me understand my options and make my own decisions?",
            "How do you work with other services and professionals?",
            "How is my privacy protected?",
            "How will we review whether the support is helping?",
        ],
        "mistakes" => [
            "Waiting until a situation becomes a crisis before asking for help.",
            "Expecting the social worker to make decisions for you.",
            "Not sharing the full picture, so help misses the real problem.",
            "Not checking qualifications and professional membership.",
            "Not asking who will follow up on the actions agreed.",
        ],
        "faq" => [
            ["What is the difference between a social worker and a support coordinator?", "A social worker takes a broad view of a person's circumstances and can provide counselling and advocacy. A support coordinator focuses on helping you use your plan and connect with providers."],
            ["Can a social worker help my family?", "Yes. Social workers often work with families and carers, especially when there are complex needs or several services involved."],
            ["Is what I tell a social worker confidential?", "Generally yes, with limited exceptions where safety is at serious risk. The social worker will explain this at the start."],
        ],
    ],
];
