<?php
/** Long-form guide content, batch 8. See content-long-1.php for the shape. */
if (!defined('ABSPATH')) exit;

return [
    'Supported holidays and camps' => [
        'cat' => 'Community access',
        'short' => 'Supported holidays and camps give you a holiday or camp experience with the support you need to take part, whether in a group or with one-to-one help.',
        'overview' => "Holidays are a chance to rest, explore and make memories. For people who need support to travel or take part, planning can be a barrier. Supported holidays remove it: a provider organises the trip, including accommodation, transport, activities and the workers who provide personal support.\n\nSome providers run group holidays with a set itinerary, while others help individuals plan a trip to a place of their choice. Camps focus on activities and friendship, and are often organised around themes such as outdoor recreation, arts or sport.\n\nWhen choosing, look at what is included, how much support there is and how the trip is run. Ask about staff-to-participant ratios, accessibility, how medications and health needs are managed and what happens if something goes wrong or you want to come home early.",
        'choose' => [
            'Ask what is included and what costs extra.',
            'Check the ratio of staff to participants and how support is organised.',
            'Ask about accessibility of accommodation and activities.',
            'Find out how health needs and medication are managed.',
            'Ask what happens if you want to leave early or become unwell.',
        ],
        'start' => [
            'Decide where you would like to go and with whom.',
            'Contact providers and ask about upcoming holidays or custom trips.',
            'Discuss your support needs and any health requirements.',
            'Plan ahead for packing, medication and travel.',
        ],
        'faq' => [
            ['Can family or friends join my supported holiday?', 'Often. Some providers support individuals or small groups. Ask what is possible.'],
            ['Can I choose the destination?', 'On tailored holidays yes. Group holidays usually have set destinations.'],
            ['What if I have never travelled without family?', 'Many providers offer shorter first trips. Ask how they help first-time travellers feel comfortable.'],
        ],
    ],
    'Tenancy and accommodation assistance' => [
        'cat' => 'Housing (SDA & SIL)',
        'short' => 'Tenancy and accommodation assistance helps you find, apply for and keep a rental or other accommodation, including understanding a lease and dealing with a landlord.',
        'overview' => "Finding and keeping a home involves paperwork, deadlines and rules that are not always easy to follow. Tenancy assistance helps with searching for properties, preparing applications, understanding a lease, arranging bond and moving, and communicating with a landlord or agent.\n\nIt can also help if problems arise, such as repairs that are not being done, a rent increase or a notice. Understanding your rights and responsibilities as a tenant helps you deal with these issues early, before they become bigger.\n\nTenancy laws differ between states and territories, and free tenancy advice services in each state can explain your rights. A support worker or housing worker can help you contact them and work through what to do. Acting early is almost always better than waiting.",
        'choose' => [
            'Ask whether the provider knows local tenancy rules and services.',
            'Find out how they help with applications and paperwork.',
            'Check whether they can help you communicate with landlords and agents.',
            'Ask how they help if there is a problem with your tenancy.',
            'Ask how they will support you to keep your home over time.',
        ],
        'start' => [
            'Gather documents such as identification and proof of income.',
            'Talk to providers about the kind of home you want.',
            'Read any lease carefully and ask questions before signing.',
            'Save contact details for local tenancy advice services.',
        ],
        'faq' => [
            ['Where can I get free tenancy advice?', 'Each state and territory has tenants\' advice services that offer free information.'],
            ['What if I get a notice from my landlord?', 'Seek advice quickly. Time limits often apply.'],
            ['Can a worker come to inspections with me?', 'Often yes, if you would like the support. Ask your provider, and tell the agent in advance.'],
        ],
    ],
    'Tenancy skills and sustainment' => [
        'cat' => 'Life skills',
        'short' => 'This support builds the skills to keep a tenancy going, such as paying rent on time, looking after a home and communicating with a landlord or agent.',
        'overview' => "Keeping a home takes many small skills. You need to budget for rent and bills, keep the place clean and safe, report repairs, understand a lease and get on with neighbours. If any of these are difficult, a support worker or coach can help you learn and practise.\n\nSupport is practical and tailored. A worker might help you set up a rent payment plan, learn a cleaning routine, practise talking to an agent or understand what to do if something breaks. Over time the aim is to do more yourself and to feel confident in your home.\n\nSustaining a tenancy is also about relationships and wellbeing. Feeling connected to your neighbourhood and having people to turn to reduce the risk of problems. Ask providers about how they support the whole picture, and how they help you get through hard times without losing your home.",
        'choose' => [
            'Ask how they build your skills rather than doing things for you.',
            'Find out how they help with budgeting and paying rent.',
            'Check how they help you communicate with landlords and agents.',
            'Ask how they respond when a problem arises.',
            'Ask how they help you connect with your neighbourhood.',
        ],
        'start' => [
            'List the parts of keeping a home that are hardest.',
            'Talk to providers about how they can help.',
            'Set up simple routines for rent, cleaning and repairs.',
            'Review after a few months.',
        ],
        'faq' => [
            ['Is this only for people at risk of losing their home?', 'No. It also helps people who are starting a tenancy and want to feel confident.'],
            ['Can it help with neighbours?', 'Yes. Support can include ways to communicate and resolve issues.'],
            ['What if I fall behind with rent?', 'Speak to your landlord or agent early and seek advice. A support worker can help.'],
        ],
    ],
    'Therapy assistants' => [
        'cat' => 'Therapy services',
        'short' => 'Therapy assistants work under a qualified therapist\'s guidance to carry out parts of a therapy program, such as practising exercises or activities between sessions.',
        'overview' => "Therapy works best with regular practice, and a therapist cannot always be present. A therapy assistant helps by carrying out parts of the program the therapist has designed. That might be practising exercises, running a group, supporting a child with communication activities or helping with daily routines that build skills.\n\nThe therapist stays responsible. They assess, design the program and review progress, and the assistant delivers it and reports back. Regular contact between the two is important so that the program stays on track and changes when needed.\n\nHaving an assistant can allow more frequent practice and free the therapist to focus on assessment and planning. Ask providers about the training and supervision the assistant receives and how the therapist and assistant communicate.",
        'choose' => [
            'Ask about the assistant\'s training and how they are supervised.',
            'Find out how often the therapist reviews the program.',
            'Check how the assistant reports progress and concerns.',
            'Ask which parts of the program the assistant carries out.',
            'Ask how family are involved and updated.',
        ],
        'start' => [
            'Ask your therapist whether an assistant could help.',
            'Agree what the assistant will do and how it will be supervised.',
            'Meet the assistant and see a session.',
            'Review progress regularly with the therapist.',
        ],
        'faq' => [
            ['Does the therapist still see me?', 'Yes. The therapist assesses and reviews, and the assistant supports the program.'],
            ['Is a therapy assistant qualified?', 'Assistants have training suited to the role and work under a therapist. Ask about their background.'],
            ['Can my child have a therapy assistant?', 'Yes. Therapy assistants commonly work with children.'],
        ],
    ],
    'Training for carers and parents' => [
        'cat' => '',
        'short' => 'Training for carers and parents helps family members understand a person\'s needs and learn practical ways to support them.',
        'overview' => "Family and carers provide much of the support people receive, often without formal training. Learning about a condition, communication, behaviour, health tasks and how to look after yourself makes caring more sustainable and helps the person you care for.\n\nTraining comes in many forms: courses, workshops, coaching from a therapist, hands-on demonstrations and peer groups where carers share experiences. A therapist or nurse can show you specific techniques, such as safe lifting, feeding or communication strategies for the person you care for.\n\nCarers also need support for themselves. Carer organisations and helplines provide information, counselling and connection, and your support coordinator may know about local options. Looking after your own health and taking breaks are part of caring well.",
        'choose' => [
            'Ask what topics the training covers and whether it suits your situation.',
            'Find out whether it includes hands-on practice.',
            'Check whether it is one-to-one, in a group or online.',
            'Ask whether there is follow-up support.',
            'Look for training that also addresses carer wellbeing.',
        ],
        'start' => [
            'Write down the situations where you would like more skills or confidence.',
            'Ask the person\'s therapist or coordinator about training.',
            'Look into carer organisations in your area.',
            'Plan time for your own rest and support.',
        ],
        'faq' => [
            ['Where can carers get support?', 'Carer organisations and national helplines offer information, counselling and peer support.'],
            ['Can siblings take part?', 'Often. Ask organisers about resources for siblings.'],
            ['Is training available online?', 'Yes, in many cases. Ask providers.'],
        ],
    ],
    'Transition to further education' => [
        'cat' => 'Employment & education support',
        'short' => 'This support helps people finishing school to plan and settle into further study, such as choosing a course, enrolling and getting the right supports in place.',
        'overview' => "Moving from school to TAFE or university is a big change. There are many choices, applications to make and new environments to learn. Transition support helps by exploring options, working out which course suits your interests and abilities, and making a plan.\n\nOnce a course is chosen, help with enrolment and with contacting the education provider's disability service makes sure adjustments are in place from the start. Visiting the campus, learning the route and meeting staff before classes begin can reduce anxiety.\n\nStarting early makes a difference. Beginning in the year before leaving school leaves time to explore, apply and prepare. Ask providers how they involve the student and family, how they work with schools and what support continues once study begins.",
        'choose' => [
            'Ask how the provider helps explore course options.',
            'Find out how they support applications and enrolment.',
            'Check how they work with the education provider\'s disability service.',
            'Ask whether they offer campus visits and practice travel.',
            'Ask what ongoing support is available once study begins.',
        ],
        'start' => [
            'Talk about study goals early with the student and school.',
            'Research courses and entry requirements.',
            'Contact the disability service at the education provider.',
            'Visit the campus and practise the journey.',
        ],
        'faq' => [
            ['When should we start?', 'The year before leaving school, if possible.'],
            ['What if the student is not sure what to study?', 'Support includes exploring interests, taster courses and work experience.'],
            ['Can support continue during study?', 'Yes. Ask providers how support can change once classes begin.'],
        ],
    ],
    'Transport to activities and appointments' => [
        'cat' => 'Transport',
        'short' => 'This support helps you get to and from activities and appointments, either with a support worker travelling with you or through arranged transport.',
        'overview' => "Getting to appointments on time can be stressful if you cannot drive or use public transport. Transport support provides a way to get there, whether that is a worker driving you, a booked car or accessible vehicle, or a worker travelling with you on a bus or train.\n\nHaving a support worker present can be helpful for more than the journey. They can help you find your way, keep track of information from a medical appointment and provide personal care if needed. If you want someone with you in an appointment, tell your provider and check with the service.\n\nPlan ahead for regular trips. Discuss how bookings are made, how much notice is needed for changes and what happens if an appointment runs over. Check that the vehicle suits your equipment and that the driver is trained and screened.",
        'choose' => [
            'Ask whether the vehicle suits your equipment.',
            'Find out how drivers are trained and screened.',
            'Check how bookings and changes are made.',
            'Ask what happens if an appointment runs late.',
            'Ask whether a worker can go into the appointment with you.',
        ],
        'start' => [
            'List your regular appointments and activities.',
            'Contact providers and ask about availability.',
            'Agree how trips will be booked.',
            'Review after a few weeks and adjust.',
        ],
        'faq' => [
            ['Can a worker attend medical appointments with me?', 'Often yes, if you want them to. Tell the provider and the clinic.'],
            ['What if I need transport at short notice?', 'Ask the provider about their policy for urgent trips.'],
            ['Can I use public transport with support?', 'Yes. A worker can travel with you and help you build confidence.'],
        ],
    ],
    'Vehicle modifications' => [
        'cat' => '',
        'short' => 'Vehicle modifications are changes to a vehicle so a person can drive it or travel in it, such as hand controls, a hoist or a wheelchair-accessible conversion.',
        'overview' => "A modified vehicle can open up independence, work and community life. Modifications range from simple changes such as hand controls, steering aids and swivel seats, to larger conversions such as lowering the floor, adding a ramp or lift, or fitting wheelchair restraints.\n\nThe process usually starts with an assessment by an occupational therapist who looks at how you move and what you need. A specialist modifier then designs and carries out the work, and it must meet standards and be approved. Some changes also require approval from the relevant authority and may affect registration and insurance.\n\nThink about the whole picture: the vehicle you will modify or buy, how it will be used, who else uses it and how long you plan to keep it. Ask about the process, timeframe, warranty and what happens if the modification needs adjustment.",
        'choose' => [
            'Choose an occupational therapist with driver or vehicle assessment experience.',
            'Check that the modifier is qualified and that work meets standards.',
            'Ask about approvals and how modifications affect registration and insurance.',
            'Get more than one quote and check what is included.',
            'Ask about warranty, servicing and what happens when you change vehicles.',
        ],
        'start' => [
            'Talk to a therapist about your needs.',
            'Choose or confirm the vehicle before modifying it.',
            'Get quotes and check approvals.',
            'Arrange training to use the modifications.',
        ],
        'faq' => [
            ['Do I need to tell my insurer?', 'Yes. Modifications should be disclosed to your insurer and the relevant authority.'],
            ['Can modifications be moved to another vehicle?', 'Some can be moved, and others are fitted to one vehicle. Ask the modifier before you decide.'],
            ['Should I buy the vehicle first?', 'Ask your therapist and modifier before buying, since not every vehicle can be modified.'],
        ],
    ],
    'Vision and orientation & mobility' => [
        'cat' => 'Therapy services',
        'short' => 'Support for people who are blind or have low vision, including orientation and mobility training to travel safely and independently, and skills for everyday life.',
        'overview' => "Orientation and mobility instructors teach people who are blind or have low vision how to understand where they are and move safely. Training might cover using a long cane, learning routes, crossing roads, using public transport and using technology such as navigation apps.\n\nSupport goes beyond travel. Vision-related supports can include everyday living skills such as cooking, organising your home, using assistive technology, reading and writing in different formats and building confidence to do things independently.\n\nThe right support depends on your vision, your goals and your environment. Instructors work with you in the places you use, such as your home, neighbourhood, school or workplace. Ask about their qualifications, experience with your situation and how they measure progress.",
        'choose' => [
            'Ask about the instructor\'s qualifications and experience.',
            'Check whether they can train you in your own neighbourhood or workplace.',
            'Find out how they teach the use of technology and other aids.',
            'Ask how goals are set and reviewed.',
            'Ask how they involve family and friends.',
        ],
        'start' => [
            'Think about the places and journeys you want to manage independently.',
            'Contact instructors and describe your vision and goals.',
            'Book an assessment.',
            'Practise between sessions and review progress.',
        ],
        'faq' => [
            ['Do I need to be totally blind to benefit?', 'No. Support suits people with a range of vision loss, including low vision.'],
            ['Can children receive orientation and mobility training?', 'Yes. Instructors work with children as well as adults.'],
            ['Is training available in regional areas?', 'It varies. Ask providers about visiting services.'],
        ],
    ],
    'Vision equipment' => [
        'cat' => 'Assistive technology & equipment',
        'short' => 'Vision equipment supports people who are blind or have low vision, such as magnifiers, screen readers, braille devices and adapted technology.',
        'overview' => "There is a wide range of equipment to help with reading, writing, using computers and phones, and everyday tasks. Options include hand and electronic magnifiers, video magnifiers, screen readers that read text aloud, braille displays and notetakers, large-print or talking devices, and cameras that read text and identify objects.\n\nA low vision service, occupational therapist or vision specialist can assess your needs and arrange trials. What works depends on your vision, your goals and where you use the equipment. Trying it in real situations shows whether it really helps.\n\nTraining matters. Learning to use technology such as a screen reader takes time and practice, so it is worth asking about training and follow-up support. Also ask about updates, repairs and what happens when the technology changes.",
        'choose' => [
            'Ask for a trial in your own environment.',
            'Check what training and follow-up are included.',
            'Ask about updates, repairs and warranty.',
            'Consider how the equipment works with your other devices.',
            'Ask a specialist to check that it suits your vision.',
        ],
        'start' => [
            'Write down the tasks you would like to do more easily.',
            'Book an assessment with a vision specialist.',
            'Trial the recommended equipment.',
            'Arrange training and set up.',
        ],
        'faq' => [
            ['What is a screen reader?', 'Software that reads out what is on a screen, so people can use computers and phones without seeing the display.'],
            ['Can I try equipment before buying?', 'Often yes. Ask suppliers and low vision services.'],
            ['Will my equipment work with a smartphone?', 'Many do. Ask the supplier about compatibility.'],
        ],
    ],
    'Volunteering and community groups' => [
        'cat' => 'Community access',
        'short' => 'This support helps you take part in volunteering or join community groups, so you can build connections and contribute to your community.',
        'overview' => "Volunteering is a way to meet people, learn skills and make a difference. Community groups, from sporting clubs to gardening groups to book clubs, offer belonging and friendship. With the right support, people with disability can enjoy these opportunities like anyone else.\n\nA support worker can help you find opportunities that match your interests, contact the organisation, get there and settle in. They can also talk with the organisation about any adjustments and explain how you like to be supported. Over time, support often reduces as you become part of the group.\n\nThink about what you would like to get out of it. Some people want to build work skills, others want friendship or to contribute to a cause they care about. Volunteering organisations and local councils list opportunities, and a provider can help you explore options.",
        'choose' => [
            'Ask how they help you find opportunities that match your interests.',
            'Find out how they work with the host organisation.',
            'Check how they help you get there and settle in.',
            'Ask how support will reduce over time.',
            'Ask how they review whether it is working for you.',
        ],
        'start' => [
            'List your interests and what you would like to get out of volunteering.',
            'Search local volunteering organisations and community groups.',
            'Visit or contact a group with your support worker.',
            'Try it for a few weeks and review.',
        ],
        'faq' => [
            ['Do I need experience to volunteer?', 'Often not. Many organisations provide training.'],
            ['Can volunteering lead to paid work?', 'It can help you build skills and experience, and some people move on to paid work.'],
            ['Is there an age limit?', 'Requirements vary by organisation. Ask when you enquire.'],
        ],
    ],
    'Yard maintenance and gardening' => [
        'cat' => 'Domestic assistance',
        'short' => 'Yard maintenance and gardening support helps keep a yard or garden safe and tidy, such as mowing, weeding and clearing, for people who cannot do it themselves.',
        'overview' => "An overgrown or untidy yard can be a safety hazard and a source of stress. Support with yard work might include mowing lawns, trimming hedges, weeding, clearing leaves and removing hazards such as overhanging branches. Regular attention keeps your yard safe and your home welcoming.\n\nYou decide how much you want to be involved. Some people prefer a worker to do the tasks, while others enjoy gardening and want help with the heavy or awkward parts. A worker can also help you set up raised garden beds or easy-care plantings that are simpler to manage.\n\nBefore starting, agree what is included, how often visits will happen and who provides equipment. Ask about insurance and how the provider handles safety, especially with machinery and chemicals.",
        'choose' => [
            'Ask what tasks are included and how often visits happen.',
            'Find out who provides tools and equipment.',
            'Check insurance and safety practices.',
            'Ask whether they can work alongside you if you enjoy gardening.',
            'Check how they handle green waste.',
        ],
        'start' => [
            'Walk around your yard and list what needs doing.',
            'Contact providers and ask for a quote or plan.',
            'Agree tasks, frequency and payment.',
            'Review after a few visits and adjust.',
        ],
        'faq' => [
            ['Can a worker help me garden rather than do it for me?', 'Yes. Many people garden together with a worker.'],
            ['Who provides equipment?', 'It varies. Ask before you start.'],
            ['Can this include removing hazards?', 'Often yes, such as clearing paths. Ask the provider what they can do safely.'],
        ],
    ],
];
