<?php
/**
 * Deeper guide content for service posts, batch 8 (companion to content-long-8.php).
 * Same shape as content-deep-1.php. Plain, general guidance only: no prices, no timeframes, no promises about who qualifies.
 */
if (!defined('ABSPATH')) exit;

return [
    "Supported holidays and camps" => [
        "day" => "A supported holiday is a trip with the support you need to enjoy it, whether that is a weekend away, a beach stay, a cruise or an overseas trip. A worker or group leader helps with travel, accommodation, personal care, medication and communication, so you can focus on being on holiday.\n\nBefore you go, the provider works with you to plan the destination, activities, accessibility and what to pack. During the holiday, staff are on hand for anything you need, and there is time for relaxation and fun. Some holidays are in groups organised for people with similar interests, while others are individual trips with a support worker.",
        "who" => "Supported holidays are organised by disability service providers, specialist travel companies and community groups. Staff should be trained, screened and experienced in the kind of support needed, including for travel. Ask about the ratio of staff to guests, how health needs and emergencies are handled and what accommodation and transport are used.",
        "fit" => "Holidays connect with respite, community access and social activities. For families and carers, they can provide a valuable break. It is worth thinking about how the support works away from home, including medication, equipment, accessible accommodation and what happens if someone becomes ill.",
        "ask" => [
            "How do you plan the trip and take my needs into account?",
            "What is the ratio of staff to guests, and what training do staff have?",
            "How is accessible transport and accommodation arranged?",
            "How are medication, health needs and emergencies managed?",
            "What travel insurance and cancellation arrangements are in place?",
            "Who is responsible for what costs, and how is it explained in writing?",
        ],
        "mistakes" => [
            "Not checking that accommodation is truly accessible.",
            "Not organising medication and equipment ahead of the trip.",
            "Forgetting travel insurance and cancellation terms.",
            "Not clarifying which costs are covered and which are yours.",
            "Not asking how emergencies are handled away from home.",
        ],
        "faq" => [
            ["Can I go on holiday with my own support worker?", "Often yes, and it can be arranged with the worker and provider. Costs and conditions need to be agreed in advance."],
            ["Are supported holidays only for groups?", "No. There are group trips and individual holidays, so ask which suits you."],
            ["What should I check before booking?", "Check accessibility, staffing, health support, insurance and what is included in the price. Ask for details in writing."],
        ],
    ],
    "Tenancy and accommodation assistance" => [
        "day" => "This support helps you find, secure and keep a place to live. A worker might help you search listings, prepare rental applications, gather documents and references, attend inspections and understand what you are signing. They may also help you speak with landlords or agents and understand your rights.\n\nOnce you have a home, they can help with practical matters such as setting up utilities, arranging repairs and understanding your responsibilities as a tenant. If something goes wrong, they can help you work out what to do and who to talk to, such as a tenants' advice service.",
        "who" => "Tenancy support is provided by housing workers, support coordinators, community legal centres and tenants' advocacy services. Ask about their knowledge of local rental rules and whether they are independent of landlords and agents. It is best to work with someone who explains your rights clearly and helps you speak for yourself.",
        "fit" => "Tenancy assistance links with housing search, tenancy skills and support coordination. It also relates to home modifications, since rental homes may need changes to become accessible. It helps to think about how long you want to stay, and to plan supports that make it easier to keep the tenancy going.",
        "ask" => [
            "How do you help with searching for and applying for rentals?",
            "How do you explain my rights and responsibilities as a tenant?",
            "Can you speak to landlords or agents with me?",
            "What help is available if there is a dispute or a repair problem?",
            "How do you help with setting up utilities and moving in?",
            "Who can I contact if I am at risk of losing my home?",
        ],
        "mistakes" => [
            "Signing a lease without understanding it.",
            "Not documenting the condition of the property at the start.",
            "Letting rent or repair problems build up.",
            "Not knowing where to get advice if a dispute occurs.",
            "Not asking about permission for modifications before moving in.",
        ],
        "faq" => [
            ["Where can I get free advice about tenancy problems?", "Each state has tenants' advice services and community legal centres that offer free advice. A worker can help you find them."],
            ["Can a support worker attend an inspection with me?", "Yes, they can help you view the property and ask questions, though you make the decision."],
            ["What should I do if my home needs repairs?", "Tell the landlord or agent in writing, keep a copy and follow up. If it is not fixed, seek advice about your options."],
        ],
    ],
    "Tenancy skills and sustainment" => [
        "day" => "Tenancy skills support helps you understand and manage the everyday responsibilities of renting. A worker or trainer teaches things like paying rent on time, reading a lease, communicating with a landlord, caring for the property, understanding notices and being a good neighbour.\n\nSessions usually use real examples, such as your own lease or a repair request, and build practical routines. When a problem arises, such as arrears or a complaint from a neighbour, the worker helps you respond early, before it becomes a threat to the tenancy. Over time you gain confidence in managing your home.",
        "who" => "This support is provided by housing support workers, tenancy coaches and support coordinators. Look for someone who knows local tenancy rules and treats you with respect. It helps if the worker can link you to tenants' advice services and financial counselling when needed.",
        "fit" => "Tenancy skills sit alongside housing search, daily living and financial skills. Staying in a stable home helps with every other part of life, so it is worth investing in these skills. Reviewing the support regularly shows whether you are ready for less help or need something different.",
        "ask" => [
            "How will you teach me the skills I need as a tenant?",
            "Will you use my own lease and situation as examples?",
            "How will you help if I fall behind on rent or have a dispute?",
            "How do you help me communicate with my landlord or agent?",
            "How do you link me to advice and financial counselling?",
            "How will we know when I need less support?",
        ],
        "mistakes" => [
            "Ignoring letters and notices from the landlord or agent.",
            "Falling behind on rent without speaking to anyone.",
            "Not reporting repairs in writing.",
            "Not knowing your rights when a landlord wants to enter or end the lease.",
            "Not asking for help until a problem becomes serious.",
        ],
        "faq" => [
            ["What should I do if I cannot pay my rent on time?", "Contact your landlord or agent early and seek advice from a financial counsellor or tenants' service. Acting early gives you more options."],
            ["Can a support worker talk to my landlord for me?", "They can support you and help you communicate, but it is usually best that you remain in charge of decisions."],
            ["How can I learn about my tenancy rights?", "Tenants' advice services publish information and can answer questions. A worker can help you find them."],
        ],
    ],
    "Therapy assistants" => [
        "day" => "A therapy assistant carries out parts of a therapy program under the direction of a therapist. For example, they may lead exercises, practise communication strategies, support a child in play-based activities or help someone practise daily living tasks. The therapist plans the program and the assistant carries it out regularly, which allows more practice than a therapist could provide alone.\n\nAssistants keep notes about how sessions go and report to the therapist, who reviews progress and adjusts the plan. They do not replace the therapist's assessments or clinical decisions, but they play an important role in helping the person practise and use skills in real life.",
        "who" => "Therapy assistants usually have training in allied health or disability support, and work under the supervision of a physiotherapist, occupational therapist, speech pathologist or psychologist. Ask who supervises the assistant, how often the therapist reviews progress and what training the assistant has for your type of therapy.",
        "fit" => "Assistants extend the reach of therapy, especially where more frequent practice would help. They work with families, teachers and support workers so that everyone uses the same strategies. It is worth confirming that a qualified therapist remains involved, and that there are regular reviews.",
        "ask" => [
            "Which therapist supervises the assistant, and how often do they review progress?",
            "What training does the assistant have?",
            "What tasks will the assistant carry out, and what stays with the therapist?",
            "How will progress be recorded and shared with us?",
            "How does the assistant work with family, school or support workers?",
            "What happens if the program needs to change?",
        ],
        "mistakes" => [
            "Assuming an assistant can replace the therapist's assessment and planning.",
            "Not knowing who supervises the assistant.",
            "Not sharing the program with others who support the person.",
            "Not asking for regular reviews.",
            "Leaving the program unchanged when the person's needs change.",
        ],
        "faq" => [
            ["What is the difference between a therapist and a therapy assistant?", "A therapist assesses, plans and reviews the program. An assistant carries out parts of the program under the therapist's direction."],
            ["Can a therapy assistant see my child at school?", "Often yes, if the school agrees. This can help skills carry over into the classroom. Discuss it with the therapist and the school."],
            ["How often does the therapist see me if I work with an assistant?", "The therapist reviews progress regularly, and how often varies. Ask the provider at the start."],
        ],
    ],
    "Training for carers and parents" => [
        "day" => "Training for carers and parents helps the people who support a person with disability to do so with skill and confidence. It may be a workshop, a series of sessions or one-to-one coaching, and covers topics such as understanding the disability, communication, managing behaviour, safe handling, medication, navigating services and looking after your own wellbeing.\n\nSessions are practical, drawing on real situations, and there is often time to talk with others in a similar position. Trainers may be therapists, nurses, psychologists or experienced parents, and they help you build skills you can use at home right away.",
        "who" => "Training is delivered by health professionals, community organisations and peer support groups. Parent and carer organisations often provide sessions from a lived experience perspective. Ask about the trainer's background, whether the content can be tailored to your situation and what follow-up is available.",
        "fit" => "Carer and parent training complements therapy, respite and counselling. It helps the whole family work in the same direction and can reduce stress. It is worth thinking about your own needs as well, since looking after yourself is essential to being able to keep caring.",
        "ask" => [
            "What topics will the training cover, and can it be tailored to our situation?",
            "Who delivers it, and what is their background?",
            "Will there be practice and time to ask questions?",
            "Is there follow-up support if we need it?",
            "Can other family members attend?",
            "Is there support for carers' own wellbeing?",
        ],
        "mistakes" => [
            "Trying to cope alone rather than seeking training and support.",
            "Choosing training that is too general for your situation.",
            "Not involving other family members.",
            "Neglecting your own health and rest.",
            "Not practising new skills after the session.",
        ],
        "faq" => [
            ["Is training for carers only for parents of children?", "No. Carers of adults and older people can also benefit from training in areas such as safe handling, communication and managing health needs."],
            ["Can training help with my own stress?", "Many programs include support for wellbeing, and meeting other carers can help you feel less alone."],
            ["How do I find training in my area?", "Carer organisations, therapists and your support coordinator can suggest options."],
        ],
    ],
    "Transition to further education" => [
        "day" => "This support helps people move from school or work into further study, such as TAFE or university. A worker or mentor helps you to choose a course, understand entry requirements, complete applications and visit campuses. They also help you connect with the disability service at the institution to arrange adjustments.\n\nPreparation might include practising travel to campus, learning how online systems work, meeting teaching staff and planning study routines. In the first weeks of study, the worker checks in regularly and helps solve problems early, such as timetable clashes or missing supports.",
        "who" => "Transition support may come from support coordinators, education specialists, mentors and the disability service at the institution. Choose someone with knowledge of the study options and experience working with people with similar needs. It helps if they can work with your school or employer as well.",
        "fit" => "Transition to further education links with higher education support, study skills, transport and life skills. It is also worth thinking about what you want to do afterwards, including employment, so that the course leads somewhere. Early planning makes it easier to arrange supports and adjustments in time.",
        "ask" => [
            "How will you help me choose a course that suits my goals?",
            "How will you help me with applications and getting adjustments in place?",
            "Can we visit the campus and practise the journey beforehand?",
            "How will you work with the disability service at the institution?",
            "How will you support me in the first weeks of study?",
            "How will we review whether the course is working for me?",
        ],
        "mistakes" => [
            "Applying for a course without checking that it leads to what you want to do.",
            "Not contacting the disability service before the course starts.",
            "Not practising the journey and the online systems in advance.",
            "Leaving problems until exams approach.",
            "Not planning for what comes after the course.",
        ],
        "faq" => [
            ["When should I start planning to move into further study?", "As early as possible, since applications and adjustments can take time to arrange."],
            ["Can I get help with the application process?", "Yes, a worker or mentor can help with choosing courses, completing forms and preparing for interviews."],
            ["What if the course turns out not to suit me?", "Talk to your worker and the institution early. There may be options to change courses, adjust the load or take a break."],
        ],
    ],
    "Transport to activities and appointments" => [
        "day" => "Transport to activities and appointments helps people get to the places they need to be. A driver or support worker collects you, takes you to the destination, and, if needed, helps you inside. For medical appointments, they may wait or return to collect you, and can help with communication or remembering what was said.\n\nDepending on your needs, the trip might use a car, a wheelchair-accessible vehicle or public transport with a worker. Reliability matters most, so it helps to agree on times, routes and what happens if something changes, and to keep a record of appointments.",
        "who" => "Transport is provided by disability providers, community transport organisations, support workers and taxi or ride services with accessible vehicles. Ask about vehicle suitability, driver screening and training, insurance and what happens if a driver is late or cancels.",
        "fit" => "This support works with other transport options such as allowances and specialised transport, and with the activities and appointments themselves. Thinking ahead about regular trips, such as therapy or work, and occasional ones, such as specialist appointments, helps you choose the right mix.",
        "ask" => [
            "Is the vehicle suitable for my mobility equipment, and is it insured?",
            "What screening and training do drivers have?",
            "Can the worker go into the appointment or activity with me?",
            "How are bookings made, and how much notice is needed?",
            "What happens if the driver is late or cancels?",
            "How are the costs of the trip worked out and explained?",
        ],
        "mistakes" => [
            "Booking too late for important appointments.",
            "Not checking that the vehicle is suitable.",
            "Not agreeing on who waits and who returns.",
            "Not having a back-up plan for missed trips.",
            "Not clarifying how costs are charged before you start.",
        ],
        "faq" => [
            ["Can a support worker come into my medical appointment?", "If you want them to, and the practitioner agrees, they can help you communicate and remember what was said. It is your choice."],
            ["What if I need to change or cancel a trip?", "Check the provider's policy on notice and charges. Giving as much notice as possible helps."],
            ["Can transport be arranged for regular appointments?", "Yes, many providers set up regular trips, so you do not have to book each time."],
        ],
    ],
    "Vehicle modifications" => [
        "day" => "Vehicle modifications change a car or van so a person with disability can drive it or travel in it. Common examples include hand controls, steering aids, wheelchair hoists and ramps, lowered floors, swivel seats and secure fittings for wheelchairs. The process starts with an assessment by an occupational therapist, who recommends what is needed.\n\nA specialist workshop then designs and installs the modifications, and the vehicle must meet safety and legal requirements. After the work is done, you practise using the modifications and have the fitting checked. Servicing and repairs are part of ongoing use, and the vehicle may need to be inspected or approved.",
        "who" => "An occupational therapist, often with driver rehabilitation experience, assesses what is needed, and an accredited vehicle modification workshop carries out the work. Choose a workshop that follows the relevant standards and provides warranties. Ask about the approvals needed and who takes responsibility for them.",
        "fit" => "Vehicle modifications connect with driver training, transport allowances and mobility equipment. Because they can be a major investment, it is worth exploring all your transport options first, and thinking about how the vehicle will be used, where it will be stored and how it fits with your equipment.",
        "ask" => [
            "Can an occupational therapist assess me and recommend what I need?",
            "Is the workshop accredited, and does it follow the relevant standards?",
            "What approvals or inspections are required?",
            "What warranty and servicing arrangements are there?",
            "Will I be able to practise with the modifications before I drive alone?",
            "What happens to the modifications if I change vehicles?",
        ],
        "mistakes" => [
            "Buying a vehicle before finding out whether it can be modified.",
            "Using a workshop that is not accredited.",
            "Not getting the assessment done first.",
            "Skipping practice with new controls.",
            "Not planning for servicing and repairs.",
        ],
        "faq" => [
            ["Can any car be modified?", "Not always. Some vehicles are better suited than others, so get advice before you buy."],
            ["Do modifications have to be approved?", "Requirements vary between states, and modified vehicles often need to be inspected or approved. The workshop should explain what is required."],
            ["Will my modifications work in a different vehicle?", "Some can, depending on the type of modification and the vehicles. Ask the workshop."],
        ],
    ],
    "Vision and orientation & mobility" => [
        "day" => "An orientation and mobility specialist helps people who are blind or have low vision to move safely and independently. In a session, they may teach you how to use a white cane, how to find your way around your home or neighbourhood, how to cross roads, use public transport and travel to new places.\n\nSessions take place where you will be travelling, so you practise real routes and situations. The specialist starts with simple tasks and builds up, giving you techniques such as using landmarks, sounds and touch. They also advise on lighting, contrast and safety at home and at work.",
        "who" => "Orientation and mobility specialists are trained professionals, and there are vision organisations that provide these services. Other professionals, such as occupational therapists and low vision specialists, also help with vision needs. Ask about experience with your kind of vision loss and whether they can work in the places you need to travel.",
        "fit" => "This support links with vision equipment, transport, community access and independent living skills. It is also helpful to work with other people who are blind or have low vision, through peer groups and organisations. Reviews are useful when your vision or your travel needs change.",
        "ask" => [
            "What experience do you have with my kind of vision loss?",
            "Can you teach me in the places where I need to travel?",
            "How will you help me learn to use public transport?",
            "Can you advise on lighting and safety at home and work?",
            "How do you work with my other supports?",
            "How will we check my progress and update the plan?",
        ],
        "mistakes" => [
            "Waiting until an accident before getting mobility training.",
            "Not practising routes you use every day.",
            "Not adjusting lighting and contrast at home.",
            "Not returning for a review when vision changes.",
            "Not connecting with peer support that could help.",
        ],
        "faq" => [
            ["What will I learn in orientation and mobility sessions?", "It teaches people who are blind or have low vision how to know where they are and how to travel safely, using skills such as cane use and route planning."],
            ["Can I get training in my own neighbourhood?", "Yes, and it is best done where you actually travel. Ask the specialist to visit your area."],
            ["Do I need to be completely blind to receive this support?", "No. People with a range of vision loss can benefit, including those with low vision."],
        ],
    ],
    "Vision equipment" => [
        "day" => "Choosing vision equipment starts with an assessment by a low vision specialist or occupational therapist, who asks about what you find hard to see and what you want to do. They may try magnifiers, telescopes, electronic readers, screen magnification software, screen readers, talking devices or adjusted lighting.\n\nOnce you have chosen equipment, training helps you use it well, in your own home, workplace or school. Follow-up checks whether it is working and whether your needs have changed. Keeping the equipment charged, clean and up to date is part of using it well.",
        "who" => "Low vision clinics, vision organisations, occupational therapists and specialist suppliers provide assessment, equipment and training. Ask about experience with your condition, whether you can trial equipment before buying and what training and support are included.",
        "fit" => "Vision equipment works with orientation and mobility training, communication equipment and study or work supports. It also depends on medical care of your eyes, so keep your eye specialist informed. Thinking about what you want to do, such as reading, working on a computer, cooking or watching television, helps to choose what suits you.",
        "ask" => [
            "Can I try different equipment before deciding?",
            "How will you match the equipment to my eye condition and my daily activities?",
            "What training and follow-up are included?",
            "How is the equipment maintained and repaired?",
            "How will it work with my computer, phone or other devices?",
            "How do we check that it continues to suit me?",
        ],
        "mistakes" => [
            "Buying equipment without a trial or assessment.",
            "Not getting training on how to use all the features.",
            "Not keeping software and devices updated.",
            "Not telling your eye specialist about changes in your vision.",
            "Not considering lighting and contrast alongside equipment.",
        ],
        "faq" => [
            ["What is the difference between low vision aids and blindness aids?", "Low vision aids make the most of remaining sight, for example through magnification, while blindness aids use senses such as hearing and touch, for example through screen readers."],
            ["Can I use my smartphone as a vision aid?", "Many phones have built-in features such as magnification, text reading and voice control. A specialist can show you what is available."],
            ["How often should I get my vision assessed?", "It depends on your condition, and your eye specialist can advise. Tell them about any changes."],
        ],
    ],
    "Volunteering and community groups" => [
        "day" => "Volunteering and community groups give you a chance to contribute, meet people and try new things. A worker or coordinator helps you find a group or role that matches your interests, whether that is a community garden, an animal shelter, a sports club, a choir or a charity shop. They may go with you the first few times and help you settle in.\n\nOnce you have a regular role, support reduces as you become part of the group. The worker stays in touch with you and the organisation, so that any problems can be solved early. Many people find that volunteering builds confidence, skills and friendships, and can lead to paid work.",
        "who" => "Support may come from community connectors, support workers, volunteer centres and the organisations themselves. Some volunteer centres have staff who specialise in including people with disability. Ask about how the organisation welcomes volunteers, what training is provided and how adjustments are made.",
        "fit" => "Volunteering links with community access, social activities and employment preparation. It suits people who want to contribute and build skills. It is worth choosing something you really care about, since you are more likely to stay involved and enjoy it.",
        "ask" => [
            "How can you help me find a volunteering role that fits my interests?",
            "Can you go with me at first and then step back?",
            "What training and support does the organisation provide?",
            "How are adjustments made for my needs?",
            "How can I try a role before committing?",
            "Can volunteering lead to paid work or study?",
        ],
        "mistakes" => [
            "Choosing a role because it is convenient rather than interesting.",
            "Not talking with the organisation about adjustments.",
            "Relying on a worker to stay, and not building connections with others.",
            "Taking on too much at once.",
            "Not asking for feedback or recognition of your contribution.",
        ],
        "faq" => [
            ["Can I volunteer if I have never done it before?", "Usually not. Many organisations offer training, and they value enthusiasm and reliability."],
            ["Can volunteering help me get a job?", "It can build skills, experience and contacts, and some people move into paid work through it."],
            ["What if the role does not suit me?", "You can talk to the organisation about changes or try something else. Volunteering is meant to be positive for you as well."],
        ],
    ],
    "Yard maintenance and gardening" => [
        "day" => "A yard maintenance visit covers the outdoor jobs that keep a home safe and tidy, such as mowing, edging, weeding, pruning, clearing paths and removing rubbish. The worker arrives with the right tools, does the agreed tasks and leaves the yard tidy. Some visits are regular, and others happen seasonally or as needed.\n\nFor people who love gardening, the support can be more collaborative, with a worker doing the heavy parts while you plan and do the parts you enjoy. Raised beds, easy-grip tools and paths can make gardening more accessible. A good worker respects your garden and your wishes.",
        "who" => "Yard maintenance is provided by gardening services, handypeople, lawn-mowing businesses and support workers. Choose someone reliable, insured and comfortable working around your home. Ask about the equipment used and who is responsible for rubbish removal and any damage.",
        "fit" => "Yard work links with household tasks, home maintenance and safety at home. An overgrown yard can create trip hazards and fire risks, so it is worth keeping on top of it. It also helps to think about whether changes such as low-maintenance planting or paving could reduce the work over time.",
        "ask" => [
            "What tasks are included in a visit, and what is charged separately?",
            "Are you insured, and who is responsible for any damage?",
            "How often will you visit, and can I change the schedule?",
            "Can you take away green waste and rubbish?",
            "Can you help me continue gardening as a hobby?",
            "Can the garden be made easier to look after?",
        ],
        "mistakes" => [
            "Not agreeing on what is included.",
            "Not checking insurance.",
            "Letting the yard become overgrown before asking for help.",
            "Not asking about waste removal.",
            "Not thinking about low-maintenance options.",
        ],
        "faq" => [
            ["Can a support worker do my gardening?", "Sometimes, if the task is part of your support and they are able to do it safely. Otherwise a gardening service may be a better choice."],
            ["Can I keep gardening as a hobby with support?", "Yes. Adaptations such as raised beds and easy-grip tools, along with help with heavy work, can make it possible."],
            ["What should I do about an overgrown yard?", "Get it assessed and cleared by a reliable service, then set up a regular maintenance plan so it does not build up again."],
        ],
    ],
];
