<?php
/** Long-form guide content, batch 5. See content-long-1.php for the shape. */
if (!defined('ABSPATH')) exit;

return [
    'Nursing training for support workers' => [
        'cat' => 'Nursing',
        'short' => 'Nursing training teaches support workers how to carry out specific health-related tasks safely for the person they support. It is delivered by a nurse and is usually tailored to the individual.',
        'overview' => "Some tasks that support workers help with have a health element, such as managing certain medications, assisting with feeding tubes, using suction or responding to seizures. Doing these tasks safely needs specific skills, which is why training from a nurse is important.\n\nTraining is usually individual. A nurse looks at the person's health plan, teaches the worker how to carry out each task for that person, watches them do it and confirms they are competent. The worker follows a written plan, and there is a process for emergencies and for updating the training when the person's health changes.\n\nProviders should keep records of who has been trained, in what and when, and arrange refreshers. If you are choosing a provider, ask how they make sure workers are competent for the tasks you need and what happens if a trained worker is not available.",
        'choose' => [
            'Ask who delivers the training and what their qualifications are.',
            'Find out how the provider checks that workers are competent.',
            'Ask how often training is refreshed and when the plan is updated.',
            'Check how records are kept.',
            'Ask what happens if the trained worker is away.',
        ],
        'start' => [
            'Ask your nurse or doctor to write down the tasks and how they are done.',
            'Arrange training for each worker who will carry them out.',
            'Keep written plans where workers can find them.',
            'Review the training whenever your health or the plan changes.',
        ],
        'faq' => [
            ['Do workers need training for every task?', 'They need training for tasks that carry health risks. A nurse can advise which tasks need it.'],
            ['Can family also be trained?', 'Yes. Family members often receive the same training so they can help safely.'],
            ['How do I know a worker is trained?', 'Ask the provider for confirmation and check that training is recorded.'],
        ],
        'src' => ['ahpra'],
    ],
    'Occupational therapy' => [
        'cat' => 'Therapy services',
        'short' => 'Occupational therapists help people do the everyday activities that matter to them, by assessing needs, building skills, recommending equipment and suggesting changes to the environment.',
        'overview' => "Occupational therapy is about participation: doing the things you need and want to do, such as getting dressed, cooking, working, studying, playing or caring for others. An occupational therapist looks at what gets in the way and works with you to find solutions, which might be practising a skill, using a different technique, getting equipment or changing your environment.\n\nOccupational therapists work with people of all ages. With children they may support handwriting, play and self-care, while with adults they might help someone return to work after an injury or adapt their home after a diagnosis. Many also complete assessments for equipment and home modifications.\n\nOccupational therapists in Australia are registered with the Australian Health Practitioner Regulation Agency. Ask about their experience with your situation and how sessions work, including whether they can visit your home, school or workplace.",
        'choose' => [
            'Check that the therapist is registered and ask about their experience with your needs.',
            'Ask whether they can work in your home, school or workplace.',
            'Find out how goals are set and how often they are reviewed.',
            'Ask whether they write reports for equipment or modifications.',
            'Check how they work with your other professionals.',
        ],
        'start' => [
            'Think about the activities you find difficult.',
            'Contact therapists and describe your situation.',
            'Book an assessment and bring your questions.',
            'Agree goals and a plan for reviewing progress.',
        ],
        'faq' => [
            ['Do I need a referral to see an occupational therapist?', 'Not always. A referral from your doctor can help, and the practice will tell you what they need.'],
            ['Can an occupational therapist see my child at school?', 'Many can visit schools or childcare, depending on the arrangement. Ask providers.'],
            ['What is the difference between occupational therapy and physiotherapy?', 'Occupational therapy focuses on everyday activities, while physiotherapy focuses on movement and physical function. They often work together.'],
        ],
        'src' => ['ahpra'],
    ],
    'One-to-one community access' => [
        'cat' => 'Community access',
        'short' => 'One-to-one community access means a support worker goes with you to take part in the community, for example shopping, appointments, hobbies or outings.',
        'overview' => "Many people prefer to spend time in the community with someone who knows them well and can support them individually. A support worker might accompany you to a café, a class, a park, the library or a medical appointment, providing the help you need, from personal care to communication to getting around.\n\nThe activities are your choice. Good providers plan with you and change what you do as your interests change. The aim is to help you do what you want to do, meet people and feel part of your community, rather than to fill time.\n\nMatching matters. A worker who shares your interests and whose style you like will make the support more enjoyable. Ask providers how they match workers and what happens if the match is not right, and let them know if you would like a worker of a certain gender, language or background.",
        'choose' => [
            'Ask how workers are matched to participants.',
            'Find out whether you can meet the worker first.',
            'Check how the provider arranges transport and costs on outings.',
            'Ask how they plan activities with you.',
            'Find out what happens if your worker is away or you want a change.',
        ],
        'start' => [
            'Write down what you want to do and where you want to go.',
            'Contact providers and ask about availability.',
            'Meet the worker if you can, and agree a first plan.',
            'Review after a few outings and change activities as you like.',
        ],
        'faq' => [
            ['Can a friend come along?', 'Often yes. Ask the provider how it works.'],
            ['Who pays for activities?', 'Usually the cost of the activity itself is separate from the support. Ask the provider what is included.'],
            ['Can a worker join me at a medical appointment?', 'Often yes. Check with your provider about what they cover.'],
        ],
    ],
    'Overnight support' => [
        'cat' => 'Personal care',
        'short' => 'Overnight support is help or supervision during the night, either with a worker who stays awake or one who sleeps on site.',
        'overview' => "Some people need support during the night: help with repositioning, toileting, medication, health monitoring or reassurance and safety. Overnight support can be delivered as an active shift, where the worker stays awake, or as a sleepover, where the worker is on site and can be woken if needed.\n\nWhich model suits depends on your needs. If you need help several times a night or need regular checks, an active shift is likely needed. If you need help only occasionally, a sleepover may be enough. A health professional or your provider can help you work out what is right.\n\nBecause the worker is in your home at night, trust and safety matter. Ask providers about screening, training, emergency procedures and how they handle records. Also ask how arrangements will be reviewed, since needs change over time.",
        'choose' => [
            'Ask how the provider decides between active and sleepover support.',
            'Find out how workers are screened and trained.',
            'Check their emergency procedures and how they contact you or your family.',
            'Ask how they record what happens overnight.',
            'Ask how the arrangement will be reviewed.',
        ],
        'start' => [
            'Write down what help you need at night and how often.',
            'Discuss it with your doctor or therapist.',
            'Ask providers about their overnight options.',
            'Agree a trial period and a review.',
        ],
        'faq' => [
            ['Where does the worker sleep?', 'Ask the provider about arrangements. A room or space for the worker may be needed.'],
            ['Can I have the same worker each night?', 'You can ask. Providers try to keep consistent workers, but availability varies.'],
            ['What if I need help but the worker is asleep?', 'In a sleepover model workers are woken when needed. Discuss how you will call them.'],
        ],
    ],
    'Personal care' => [
        'cat' => 'Personal care',
        'short' => 'Personal care is help with everyday tasks such as showering, dressing, grooming, eating and getting around the home, delivered with respect for your privacy and choices.',
        'overview' => "Personal care support helps you with the daily tasks of looking after your body. That includes washing and showering, dressing, toileting, grooming, eating and drinking, and moving around the home. The help you need might be a little reminder or physical assistance, and it can change from day to day.\n\nWho provides your care is very important. You should be treated with dignity and be able to say how you want things done. You can ask for a worker of a certain gender, and providers will do what they can to match your preferences. Consistency also helps, because familiar workers get to know your routine.\n\nBefore starting, read your service agreement carefully. It should explain what support you will get, when, how it can change, how to make a complaint and what happens if you or the worker cannot make a visit. Ask for a plain-language copy if you need one.",
        'choose' => [
            'Ask how workers are trained and how they are supervised.',
            'Find out how the provider matches workers and handles gender preferences.',
            'Check how they respect your privacy and choices.',
            'Ask how they handle missed visits and changes to the roster.',
            'Read the service agreement and ask about complaint procedures.',
        ],
        'start' => [
            'Write down the help you need at each time of day.',
            'Contact providers and ask about availability.',
            'Meet the worker if possible and agree how you like things done.',
            'Review after a few weeks and adjust.',
        ],
        'faq' => [
            ['Can I choose the gender of my support worker?', 'You can request a preference and providers will try to accommodate it, depending on availability.'],
            ['What if I do not feel comfortable with a worker?', 'Tell the provider. You are entitled to ask for a change.'],
            ['Can personal care be provided at night?', 'Some providers offer it. Ask about overnight support.'],
        ],
    ],
    'Personal care and safety equipment' => [
        'cat' => 'Assistive technology & equipment',
        'short' => 'Personal care and safety equipment includes shower chairs, bed rails, toilet aids and personal alarms. It helps you wash, dress, use the toilet and stay safe at home.',
        'overview' => "The bathroom and bedroom are where many accidents happen, and where independence matters most. Equipment such as shower chairs and stools, bath boards, toilet frames and raised seats, bed rails, hoists and personal alarms can make daily routines safer and more comfortable.\n\nChoosing the right item depends on your body, your home and your routine. An occupational therapist can assess how you manage and recommend equipment, including where to place it and how to use it. Poorly chosen or installed equipment can create new risks.\n\nOnce equipment is in place, check it regularly. Parts wear, fixings loosen and needs change. Ask the supplier about maintenance, and make sure you and anyone who helps you know how to use it correctly.",
        'choose' => [
            'Ask an occupational therapist to assess your needs before buying.',
            'Check that equipment is installed by someone qualified.',
            'Ask about weight limits and safety standards.',
            'Find out about warranty and servicing.',
            'Make sure you and your carers are shown how to use it.',
        ],
        'start' => [
            'Identify where you have difficulty or feel unsafe.',
            'Speak to a therapist about suitable equipment.',
            'Arrange installation and training.',
            'Check and review equipment regularly.',
        ],
        'faq' => [
            ['Do I need professional installation?', 'For fixed items such as rails, yes, so they are secure. Ask the supplier.'],
            ['Can personal alarms call for help automatically?', 'Some do. Ask about features such as fall detection and how alerts are monitored.'],
            ['How often should I check equipment?', 'Regularly, and whenever something feels loose or worn. Follow the maker\'s advice.'],
        ],
    ],
    'Personal training' => [
        'cat' => '',
        'short' => 'Personal training is one-to-one fitness coaching tailored to your abilities and goals, to build strength, movement and confidence.',
        'overview' => "Regular physical activity supports health and wellbeing for everyone. A personal trainer designs a program around your goals, whether that is building strength, improving fitness, losing weight or feeling more confident. For people with disability, a good trainer adapts exercises, equipment and pace to your abilities.\n\nTrainers vary in their experience with disability. Some have extra training and work with health professionals, while others may need guidance. Ask about their experience with your needs and whether they will liaise with your therapist or doctor.\n\nA health professional such as an exercise physiologist or physiotherapist is the right choice when you have a medical condition or injury, while a personal trainer suits general fitness goals. Many people use both, and it is worth talking to your health team before starting.",
        'choose' => [
            'Ask about the trainer\'s qualifications and experience with your needs.',
            'Find out whether they will speak to your health professionals.',
            'Check how they adapt exercises and equipment.',
            'Ask where sessions take place and whether they are private.',
            'Ask how they set and review goals.',
        ],
        'start' => [
            'Talk to your doctor or therapist about exercise.',
            'Contact trainers and describe your goals.',
            'Try a session to see whether the style suits you.',
            'Set goals and review them regularly.',
        ],
        'faq' => [
            ['Do I need to get clearance from my doctor?', 'For many people it is a good idea, particularly with a health condition.'],
            ['Can I train at home?', 'Many trainers can visit you, or you can train at a gym, park or online.'],
            ['How often should I train?', 'It depends on your goals and health. A trainer or health professional can advise.'],
        ],
    ],
    'Physiotherapy' => [
        'cat' => 'Therapy services',
        'short' => 'Physiotherapists assess and treat problems with movement and physical function, using exercise, manual therapy and education to improve mobility and reduce pain.',
        'overview' => "Physiotherapy helps people who have pain, injury, or difficulty moving. It can help after surgery or injury, support people living with long-term conditions such as arthritis or neurological conditions, and help children with developmental differences build movement skills.\n\nA physiotherapist begins with an assessment: your history, how you move and what you want to be able to do. They then use a combination of treatments, which may include exercises, hands-on therapy, use of equipment and advice on posture and activity. Education is an important part, so that you can manage between sessions.\n\nPhysiotherapists are registered with the Australian Health Practitioner Regulation Agency, and some have advanced training in areas such as neurological, paediatric or respiratory physiotherapy. Ask about their experience with your condition, whether they can treat you at home and how they measure progress.",
        'choose' => [
            'Check registration and ask about experience with your condition.',
            'Find out whether they provide home or community visits.',
            'Ask how they set goals and measure progress.',
            'Check what exercises you will be asked to do between sessions.',
            'Ask how they work with your doctor and other therapists.',
        ],
        'start' => [
            'Note what you want to be able to do and where it hurts or is difficult.',
            'Contact physiotherapists and ask about their experience.',
            'Book an assessment and ask what to bring.',
            'Follow the plan and review progress with your physiotherapist.',
        ],
        'faq' => [
            ['How will I know how many physiotherapy sessions I need?', 'It depends on your situation. Your physiotherapist can discuss a plan and review it with you.'],
            ['Is physiotherapy painful?', 'It should not cause unnecessary pain, although some exercises can be uncomfortable. Tell your physiotherapist how you feel.'],
            ['Can physiotherapy help children?', 'Yes. Paediatric physiotherapists work with children on movement, strength and coordination.'],
        ],
        'src' => ['ahpra'],
    ],
    'Plan management' => [
        'cat' => 'Plan management',
        'short' => 'A plan manager pays your providers\' invoices from your NDIS funding, tracks your budget and gives you regular statements, so you do not have to handle payments yourself and can choose any provider.',
        'overview' => "Managing an NDIS plan involves a lot of paperwork: checking that invoices match services, making sure claims are within your budget, paying providers on time and keeping records. A plan manager handles these tasks on your behalf. You continue to choose your providers and decide how to use your funding.\n\nPlan-managed participants have more flexibility than those whose plan is managed by the NDIA. They can use registered and unregistered providers, and have help staying on top of their budget. Plan managers give regular statements, so you can see what has been spent and what is left, and can help you understand your plan.\n\nPlan management is usually funded separately from your support budget, so choosing it should not reduce the money you have for supports. When comparing plan managers, look at how they communicate, how quickly they pay invoices and how easy it is to see your budget. Ask about any fees and read the service agreement carefully.",
        'choose' => [
            'Ask how quickly they pay invoices and how you will be kept informed.',
            'Check how you can see your budget and statements.',
            'Find out how you contact them and how quickly they respond.',
            'Ask how they handle disagreements about invoices.',
            'Read the service agreement carefully and ask about anything you do not understand.',
        ],
        'start' => [
            'Check that plan management is included in your plan.',
            'Compare a few plan managers using the questions above.',
            'Sign a service agreement and provide your plan details.',
            'Tell your providers who your plan manager is and how to send invoices.',
        ],
        'faq' => [
            ['Can I change plan manager?', 'Yes. You can change providers, and it is a good idea to read the agreement about notice.'],
            ['Does a plan manager choose my providers?', 'No. You choose your providers. The plan manager pays the invoices.'],
            ['Can I use providers who are not registered?', 'If your plan is managed by a plan manager or by you, generally yes.'],
        ],
    ],
    'Podiatry' => [
        'cat' => 'Therapy services',
        'short' => 'Podiatrists look after the health of your feet and lower limbs. They treat pain and injury, help manage conditions such as diabetes-related foot problems and advise on footwear.',
        'overview' => "Feet carry us through every day, and problems with them can affect mobility, balance and independence. Podiatrists treat conditions such as heel pain, ingrown toenails, corns and calluses, fungal infections and wounds. They also help people whose feet are at higher risk, such as those with diabetes or poor circulation.\n\nRegular foot care can prevent small problems from becoming serious. A podiatrist checks skin, nails and circulation, provides treatment, and advises on footwear and daily foot care. Some podiatrists make orthoses or shoe inserts to support the feet.\n\nPodiatrists are registered with the Australian Health Practitioner Regulation Agency. Ask about their experience with your condition, whether they visit homes or residential settings and how often they recommend visits. Tell them about any changes in your feet between appointments.",
        'choose' => [
            'Check that the podiatrist is registered.',
            'Ask about experience with your condition, such as diabetes.',
            'Find out whether they offer home visits.',
            'Ask how often they recommend visits.',
            'Check what advice they give about footwear and daily care.',
        ],
        'start' => [
            'Note any foot pain, wounds or changes.',
            'Book an appointment with a podiatrist.',
            'Bring your usual shoes and any medical information.',
            'Follow the care plan and return for regular check-ups.',
        ],
        'faq' => [
            ['Do I need a referral to see a podiatrist?', 'Often not, but check with the practice.'],
            ['Why is foot care important for people with diabetes?', 'Diabetes can reduce feeling and circulation in the feet, so small injuries may go unnoticed. Regular checks help find problems early.'],
            ['Can a podiatrist help with children?', 'Yes. Some podiatrists specialise in children\'s feet and walking.'],
        ],
        'src' => ['ahpra'],
    ],
    'Psychology' => [
        'cat' => 'Therapy services',
        'short' => 'Psychologists assess and treat mental health and behavioural concerns using evidence-based therapies, and can help you build skills and manage emotions.',
        'overview' => "Psychologists work with people of all ages on concerns such as anxiety, depression, trauma, behaviour, learning and adjustment to change. They assess what is going on, explain it in plain language and provide therapy based on research evidence. Common approaches include cognitive behavioural therapy, acceptance-based therapies and skills training.\n\nFor people with disability, psychologists may also carry out assessments, for example of development, learning or cognition, and may support families. Some psychologists specialise in areas such as child development, neuropsychology or behaviour support.\n\nPsychologists are registered with the Australian Health Practitioner Regulation Agency. Ask about their experience with your concerns, what approach they use and how they measure progress. Feeling comfortable with your psychologist is important, and it is fine to try more than one before deciding.",
        'choose' => [
            'Check registration and ask about experience with your concerns.',
            'Find out what therapy approach they use.',
            'Ask how sessions are structured and how long they last.',
            'Check how they involve family or carers where appropriate.',
            'Ask how they will review progress with you.',
        ],
        'start' => [
            'Think about what you would like help with.',
            'Contact psychologists and ask about their approach.',
            'Book a first appointment and ask what to expect.',
            'Review after a few sessions whether it is helping.',
        ],
        'faq' => [
            ['Do I need a referral to see a psychologist?', 'Not always, though a referral from a doctor may be needed for some arrangements. Ask the practice.'],
            ['How is a psychologist different from a psychiatrist?', 'Psychiatrists are medical doctors who can prescribe medication, while psychologists provide therapy and assessment. Some people see both.'],
            ['Is what I say kept private?', 'Psychologists keep information confidential, with limited exceptions, such as serious risk of harm. They explain this at the start.'],
        ],
        'src' => ['ahpra'],
    ],
];
