<?php
/**
 * Editorial content for service posts, part 3 (titles R-Y). See content-services-1.php for the shape.
 */
if (!defined('ABSPATH')) exit;

return [
    'Recreation equipment' => ['at',
        'People who want to take part in sport, hobbies and leisure and need adapted or specialised equipment to do so.',
        [
            ['What is recreation equipment?', 'Equipment that lets you take part in sport, hobbies and leisure, such as adapted bikes, sports wheelchairs, adaptive gear and specialised tools for a particular activity.'],
            ['How do I find the right equipment?', 'Talk to a therapist, sporting organisation or specialist supplier. Trying equipment before buying helps make sure it suits the activity and you.'],
            ['Can I try an activity first?', 'Many clubs and programs run come-and-try sessions, which is a good way to test an activity and its equipment before committing.'],
        ]],
    'Recurring transport allowance' => ['core',
        'People who cannot use public transport because of their disability and who have ongoing travel needs.',
        [
            ['What is a recurring transport allowance?', 'A regular allowance related to travel, for people who cannot use public transport because of their disability. How it is set up is described in the person\'s plan.'],
            ['How is it different from paying a transport provider?', 'An allowance is a regular amount for ongoing travel needs. Transport providers deliver specific trips or services. Ask your planner how your plan handles it.'],
            ['Where can I get advice?', 'Your planner, Local Area Coordinator or support coordinator can explain how transport is included in your plan and what you can use it for.'],
        ]],
    'School Leaver Employment Supports (SLES)' => ['cb',
        'Young people who are finishing school and want help to build work skills and move towards employment.',
        [
            ['What is SLES?', 'School Leaver Employment Supports help young people finishing school to build work skills, get work experience and prepare for a job.'],
            ['When should we start planning?', 'Planning in the final years of school gives time to explore interests, try work experience and set goals. Talk to the school and your planner early.'],
            ['What should I ask a SLES provider?', 'Ask about the activities and work experience they offer, how they set goals with you and how they will support the move from school to work.'],
        ]],
    'Self-management training' => ['cb',
        'NDIS participants who manage, or want to manage, their own plan and would like training in how to do it well.',
        [
            ['What does self-management involve?', 'Managing your own plan means choosing providers, agreeing prices, paying invoices, keeping records and making claims. Training helps you build the skills to do this confidently.'],
            ['Is self-management right for me?', 'It gives flexibility and control but also responsibility. Some people self-manage part of their plan and use a plan manager for the rest. Training can help you decide.'],
            ['Who provides self-management training?', 'Plan managers, support coordinators and specialist training providers offer it. Ask about what is covered and whether it suits your learning style.'],
        ]],
    'Short Term Accommodation (STA) / respite' => ['core',
        'People who would like a short stay away from home, and families or carers who need a break.',
        [
            ['What is short term accommodation?', 'A short stay away from home, giving the person a break or a change, and giving family or carers a period of respite. Stays are usually days or weeks.'],
            ['How do I find a good respite service?', 'Visit if you can, and ask about staffing, activities, the environment and how they get to know you before a stay. Feeling comfortable there matters.'],
            ['How far ahead should I book?', 'As early as you can. Popular services can be booked out, so plan around school holidays and other busy times.'],
        ]],
    'Skill-building camps and classes' => ['cb',
        'People who like to learn in a camp or class setting and want to build independence, social confidence or recreation skills.',
        [
            ['What happens at a skill-building camp?', 'Participants take part in activities that build skills, such as independence, teamwork, social confidence and recreation, in a supported group setting.'],
            ['Is support provided throughout?', 'Camps and classes usually include staff or support workers. Ask about the ratio of staff to participants and what help is available.'],
            ['How do I choose a program?', 'Consider the activities, the age and needs of the group, the length and how the program builds skills you want to work on.'],
        ]],
    'Skill-building community access' => ['cb',
        'People who want support in the community that also helps them learn a skill, such as using public transport or handling money.',
        [
            ['How is this different from ordinary community access?', 'The focus is learning a skill while you are out, for example catching a bus, shopping with a budget or joining a local group, with the aim of doing more independently.'],
            ['What skills can it cover?', 'Examples include travel training, money handling, communication, joining clubs and using local services.'],
            ['How do I know if it is working?', 'Good providers set clear goals with you and review progress regularly, changing the support as you become more confident.'],
        ]],
    'Social and recreation activities' => ['core',
        'People who want to enjoy leisure time and connect with others through sport, hobbies, social groups and outings.',
        [
            ['What activities can I take part in?', 'Anything that helps you enjoy your time and meet people, such as sport, arts, social groups, games, outings and hobbies.'],
            ['Can I take part with friends?', 'Often, yes. Some people go with friends or join a group, and others prefer one-to-one support. Tell your provider what you prefer.'],
            ['What should I ask a social and recreation provider?', 'Ask what activities they offer, how you can choose or suggest activities, how transport works and how they support your safety and wellbeing.'],
        ]],
    'Social skills and relationship development' => ['cb',
        'People who want help making friends, communicating and keeping healthy relationships.',
        [
            ['What does social skills support involve?', 'Coaching and practice to communicate, make friends, understand social situations and build healthy relationships, in one-to-one or group settings.'],
            ['Who can help with social skills and relationships?', 'Psychologists, occupational therapists, speech pathologists and trained support workers can all provide it. Ask providers about their approach.'],
            ['Is it only for children?', 'No. People of all ages can benefit from support with social skills and relationships.'],
        ]],
    'Social work' => ['cb',
        'People who want help working through practical or emotional challenges, connecting with services or understanding their rights and options.',
        [
            ['What does a social worker do?', 'A social worker helps people work through practical and emotional challenges, connect with services, understand their rights and options and get support during difficult times.'],
            ['When might I see a social worker?', 'Common reasons include complex family situations, navigating services, housing or financial stress and major life changes.'],
            ['How do I find a qualified social worker?', 'Look for someone eligible for membership of the Australian Association of Social Workers, and ask about their experience with your situation.'],
        ]],
    'Specialised driver training' => ['cb',
        'People with a disability who want to learn to drive, or to drive an adapted vehicle safely.',
        [
            ['What is specialised driver training?', 'Assessment and lessons for people with a disability, including learning to use adaptive controls or a modified vehicle. It usually starts with an assessment by a qualified professional.'],
            ['Do I need a driving assessment first?', 'Usually. A driving assessment, often by an occupational therapist with driver assessment training, looks at whether and how you can drive safely and what equipment you need.'],
            ['Will I need to modify my vehicle?', 'Possibly. The assessment can recommend adaptations, and modifications are done by specialist providers.'],
        ]],
    'Specialised transport' => ['core',
        'People who need transport in a vehicle suited to their needs, such as one with a wheelchair lift or extra help getting in and out.',
        [
            ['What makes transport "specialised"?', 'The vehicle or the help provided is suited to the person\'s needs, for example a wheelchair-accessible vehicle with a lift or a driver trained to assist with transfers.'],
            ['Can I use it for medical appointments?', 'Many services take people to appointments, activities and other places. Ask providers about the trips they cover and how to book.'],
            ['What should I check with a specialised transport provider?', 'Ask about vehicle accessibility and safety, how drivers are trained, how bookings work and what happens when plans change.'],
        ]],
    'Specialist Disability Accommodation (SDA)' => ['capital',
        'People with very high support needs or extreme functional impairment who need housing with specialist design features.',
        [
            ['What is Specialist Disability Accommodation?', 'Housing with special design features for people with very high support needs or extreme functional impairment. It covers the building, not the support services delivered inside it.'],
            ['Is SDA the same as Supported Independent Living?', 'No. SDA is the housing. Supported Independent Living is help with daily tasks. Some people have both, but they are separate and often provided by different organisations.'],
            ['How do I find out if SDA is right for me?', 'Talk with your planner, support coordinator or an occupational therapist. Eligibility is assessed against specific criteria and needs supporting evidence.'],
        ]],
    'Specialist Positive Behaviour Support' => ['cb',
        'People whose behaviour puts them or others at risk, or limits their life, and who need a specialist to work out why and develop a plan.',
        [
            ['What is positive behaviour support?', 'An approach that looks for the reasons behind behaviours of concern and focuses on meeting the person\'s needs and improving their quality of life, rather than on punishment or control.'],
            ['Who can provide specialist behaviour support?', 'Behaviour support practitioners, often psychologists, occupational therapists, speech pathologists or social workers with specialist experience, who must meet requirements set by the NDIS Commission.'],
            ['What is a behaviour support plan?', 'A written plan that describes the person\'s needs, the reasons behind behaviours and the strategies everyone should use. It is reviewed as needs change.'],
        ]],
    'Specialist Support Coordination (Level 3)' => ['cb',
        'People in complex situations, or at risk, who need extra help to resolve barriers and get their supports working together.',
        [
            ['What is specialist support coordination?', 'A higher level of support coordination for people in complex or high-risk situations. The coordinator works to resolve barriers and get multiple supports working together.'],
            ['How is it different from ordinary support coordination?', 'It is designed for more complex situations, and coordinators are expected to have specialist skills. Ask providers about their experience with your circumstances.'],
            ['How do I get it?', 'Whether it fits your plan depends on your circumstances. Speak with your planner or Local Area Coordinator.'],
        ]],
    'Speech pathology' => ['cb',
        'People, including children, with difficulty speaking, understanding, communicating, eating or swallowing.',
        [
            ['What does a speech pathologist do?', 'A speech pathologist assesses and treats difficulties with speaking, understanding, communication, and with eating and swallowing.'],
            ['Do speech pathologists only work with children?', 'No. They work with people of all ages, for example adults after stroke or with a communication disability, as well as children with developmental needs.'],
            ['How do I find a qualified speech pathologist?', 'Look for someone who is a Certified Practising Speech Pathologist through Speech Pathology Australia, and ask about their experience with your situation.'],
        ]],
    'Study and learning skills' => ['cb',
        'Students who want to build skills for learning, such as planning, note-taking, time management and confidence.',
        [
            ['What are study skills?', 'Practical skills that help you learn, such as planning your time, taking notes, organising work, revising for tests and staying motivated.'],
            ['Who provides this support?', 'Tutors, therapists and specialist coaches can help. Ask providers how they tailor support to the way you learn.'],
            ['Can it help with school and adult study?', 'Yes. The same kinds of skills help in school, TAFE, university and adult learning.'],
        ]],
    'Support Connection (Level 1)' => ['cb',
        'People who need help understanding their plan and connecting with providers and community services, without ongoing coordination.',
        [
            ['What is support connection?', 'Help to understand your plan and connect with providers and community services, without ongoing coordination.'],
            ['How is support connection different from support coordination?', 'Support connection is shorter and lighter. Support coordination involves more ongoing help to put supports in place and build your capacity.'],
            ['Who can provide support connection?', 'Support coordination providers. Check what is included in your plan and ask providers what they offer.'],
        ]],
    'Support Coordination (Level 2)' => ['cb',
        'People who need help putting their plan into action, finding providers and building the skills to manage their supports.',
        [
            ['What does a support coordinator do?', 'A support coordinator helps you turn your plan into action: finding providers, setting up services, understanding your budget and building your ability to manage your supports.'],
            ['Does a support coordinator make decisions for me?', 'No. They help you understand your options and set things up, but the decisions are yours.'],
            ['How do I choose a support coordinator?', 'Ask about their experience, how they communicate, how they handle conflicts of interest and how they will help you build your own skills.'],
        ]],
    'Supported Independent Living (SIL)' => ['core',
        'People who need help with daily tasks in a shared home, so they can live as independently as possible.',
        [
            ['What is Supported Independent Living?', 'Help with daily tasks in a shared home, so a person can live as independently as possible. It covers the support provided, not the housing itself.'],
            ['What is the difference between SIL and SDA?', 'SIL is the support delivered in the home. SDA is the specially designed housing. They are separate, though some people receive both.'],
            ['How do I choose a SIL provider?', 'Consider the home, the housemates, the staff and how the provider involves you in decisions. Visiting and meeting staff helps.'],
        ]],
    'Supported employment' => ['cb',
        'People who need ongoing support in the workplace to keep working, alongside their employer.',
        [
            ['What is supported employment?', 'Ongoing support in a workplace for people who need it to keep working, delivered by a provider that works alongside the employer and the person.'],
            ['Who does it suit?', 'People who need regular support at work, for example due to the nature of their disability or the tasks in their job.'],
            ['Is it a paid job?', 'Yes, employment includes pay, and workplace rules apply. Ask providers how wages are set and how the arrangement works.'],
        ]],
    'Supported holidays and camps' => ['core',
        'People who want a holiday or camp and need support to take part.',
        [
            ['What is a supported holiday?', 'A holiday or camp with the support a person needs to take part, whether in a group or with one-to-one help.'],
            ['Can I go with family or friends?', 'Often. Some providers support individuals on their own trips, and others run group holidays. Ask what is possible.'],
            ['What should I check when booking?', 'Ask about staff-to-participant ratios, accessibility, what is included and what happens if something goes wrong.'],
        ]],
    'Tenancy and accommodation assistance' => ['cb',
        'People who need help finding, applying for and keeping a rental or other accommodation.',
        [
            ['What does tenancy assistance involve?', 'Help to find and apply for a place, understand a lease and communicate with a landlord or agent.'],
            ['Can it help if I am at risk of losing my home?', 'It can help you understand your rights and options and connect you with services. Act early if you are worried about a tenancy.'],
            ['Where else can I get tenancy advice?', 'Community legal centres and tenants\' advice services offer free advice about tenancy rights in each state and territory.'],
        ]],
    'Tenancy skills and sustainment' => ['cb',
        'People who want to build the skills to keep a tenancy going, such as paying rent on time and looking after a home.',
        [
            ['What tenancy skills can I learn?', 'Skills such as budgeting for rent, understanding a lease, keeping a home clean and safe, and communicating with a landlord or agent.'],
            ['Is this for people who already have a home?', 'Yes. It helps people keep their tenancy successfully, as well as those preparing to move into a new home.'],
            ['Who provides tenancy skills support?', 'Support workers, skills coaches and some housing services. Ask about their experience.'],
        ]],
    'Therapy assistants' => ['cb',
        'People whose therapist has set a program and who would like a trained assistant to help carry it out between sessions.',
        [
            ['What does a therapy assistant do?', 'A therapy assistant works under the guidance of a qualified therapist to carry out parts of a therapy program, such as practising exercises or activities.'],
            ['Do they replace the therapist?', 'No. The therapist assesses, designs and reviews the program, and the assistant helps deliver it. Regular contact between them is important.'],
            ['Why use a therapy assistant?', 'They can allow more practice in daily life, and sessions can be more frequent than with a therapist alone.'],
        ]],
    'Training for carers and parents' => ['general',
        'Family members and carers who want to understand a person\'s needs and learn practical ways to support them.',
        [
            ['What kind of training is available?', 'Courses and coaching on topics such as understanding a diagnosis, communication, managing behaviour, health tasks and looking after your own wellbeing.'],
            ['Can it include hands-on training?', 'Often, yes. Therapists and nurses can show carers practical techniques for the person they care for.'],
            ['Where else can carers get support?', 'Carer organisations and helplines offer information, counselling and peer support. Your support coordinator may also know local options.'],
        ]],
    'Transition to further education' => ['cb',
        'People finishing school who want to plan and settle into further study, such as TAFE or university.',
        [
            ['What does transition support include?', 'Help to choose a course, enrol, understand the supports available and settle into study.'],
            ['When should I start?', 'Start early, ideally the year before. This gives time to explore options and arrange adjustments with the education provider.'],
            ['What can the education provider do?', 'Most have disability services that arrange adjustments. Contact them early to discuss your needs.'],
        ]],
    'Transport to activities and appointments' => ['core',
        'People who need help getting to and from activities and appointments and cannot use public transport independently.',
        [
            ['How does this work?', 'A support worker may travel with you, or transport may be arranged for you, so you get to appointments and activities safely and on time.'],
            ['Can a worker come with me into the appointment?', 'Often, yes, if you want them to. Tell your provider what you need, and ask the appointment provider about any rules.'],
            ['What if I need to change a booking?', 'Check your service agreement for notice periods and cancellation terms before you start.'],
        ]],
    'Vehicle modifications' => ['capital',
        'People who need changes to a vehicle so they can drive it or travel in it, such as hand controls, a hoist or a wheelchair-accessible conversion.',
        [
            ['What vehicle modifications are available?', 'Examples include hand controls, hoists, ramps and lifts, transfer seats and wheelchair-accessible conversions. What suits you depends on your needs.'],
            ['Who assesses and does the work?', 'Usually an occupational therapist assesses your needs, and a specialist modifier carries out and certifies the work. Check that modifiers are suitably qualified.'],
            ['Will modifications affect my insurance or registration?', 'They can. Tell your insurer and the relevant transport authority, and ask the modifier what approvals or certification are required.'],
        ]],
    'Vision and orientation & mobility' => ['cb',
        'People who are blind or have low vision and want to travel safely and independently and build everyday skills.',
        [
            ['What is orientation and mobility training?', 'Training that helps people who are blind or have low vision understand their surroundings and travel safely, for example learning routes, using a cane and crossing roads.'],
            ['Who teaches orientation and mobility?', 'Orientation and mobility specialists, who are trained to teach these skills. Ask about their qualifications and experience.'],
            ['Can it help with skills at home?', 'Yes. Support often includes everyday living skills, such as cooking, using technology and organising your home.'],
        ]],
    'Vision equipment' => ['at',
        'People who are blind or have low vision and want equipment to read, use technology or move around more easily.',
        [
            ['What vision equipment is available?', 'Examples include magnifiers, screen readers, braille displays, large-print and talking devices, and other aids that help with reading and using technology.'],
            ['How do I choose?', 'A low vision service, occupational therapist or vision specialist can assess your needs and arrange trials. Trying equipment in your own environment helps.'],
            ['Is training included?', 'Learning to use technology such as screen readers takes time, so training is worth asking about.'],
        ]],
    'Volunteering and community groups' => ['core',
        'People who would like to volunteer or join community groups and need support to take part.',
        [
            ['What support can help me volunteer?', 'A support worker can help you find opportunities, get there and settle in, and support you until you feel confident.'],
            ['How do I find a volunteering role?', 'Volunteering organisations and local councils list opportunities. A support worker can help you explore options that fit your interests.'],
            ['Can volunteering lead to work?', 'It can help you build skills and experience, and some people move on to paid work. Explore what you want to get out of it.'],
        ]],
    'Yard maintenance and gardening' => ['core',
        'People who cannot keep their yard or garden safe and tidy themselves, for example with mowing, weeding or clearing.',
        [
            ['What does yard maintenance cover?', 'Tasks such as mowing, weeding, trimming and clearing, so the yard is safe and tidy. The exact tasks depend on what you agree with the provider.'],
            ['Can I garden with support?', 'Yes. Some people prefer to do gardening with a worker rather than have it done for them. Tell your provider your goals.'],
            ['What should I check with a yard maintenance provider?', 'Ask about insurance, equipment, how often visits happen and what is included in the price.'],
        ]],
];
