<?php
/**
 * Deeper guide content for service posts, batch 3 (companion to content-long-3.php).
 * Same shape as content-deep-1.php. Plain, general guidance only: no prices, no timeframes, no promises about who qualifies.
 */
if (!defined('ABSPATH')) exit;

return [
    "Group skills development" => [
        "day" => "A group skills session brings a small number of people together around a shared goal, such as communication, cooking, money, travel or making friends. A facilitator explains the activity, demonstrates it and guides people through practising together. There is usually a mix of discussion, role play and hands-on tasks, with time to ask questions and share what works.\n\nLearning alongside others has its own benefits. People see how others approach a problem, feel less alone and often pick up ideas they would not have thought of. A good facilitator makes sure everyone can take part at their own pace, and follows up with each person about how to use the skills in their own life.",
        "who" => "Groups are run by therapists, trainers, support workers and community educators. Some are led by an occupational therapist or speech pathologist, particularly when the skills involve communication or daily living. Ask about the facilitator's experience with your age group and your kind of needs, and about the size of the group so you know how much individual attention to expect.",
        "fit" => "Group skills programs complement one-to-one therapy and community support. A person might learn a skill in a group and then practise it with a support worker in real situations. They also connect with social and recreation activities, since many people build friendships through them. It helps to talk with the facilitator about how the group links with your own goals.",
        "ask" => [
            "What skills does the program cover, and how is it structured?",
            "How large is the group, and how are participants matched?",
            "Who runs the sessions, and what is their experience?",
            "How will the program help me apply what I learn outside the group?",
            "How do you support people who need more time or a different approach?",
            "How will we know whether the program is working for me?",
        ],
        "mistakes" => [
            "Joining a group that does not match your goals or age group.",
            "Expecting the group alone to change everyday life without practice outside it.",
            "Not telling the facilitator about your needs, so the activities are not adjusted.",
            "Leaving early because the first few sessions feel awkward.",
            "Not asking how many people are in the group before you commit.",
        ],
        "faq" => [
            ["Is a group program better than one-to-one support?", "Neither is better in every case. Groups are good for practising with others and building social confidence, while one-to-one support suits people who need a personalised approach. Many people use both."],
            ["What if I feel nervous about joining a group?", "That is very common. Ask whether you can visit first, meet the facilitator or start with a shorter session. A good facilitator will help you feel comfortable."],
            ["Are there programs for young people and adults separately?", "Many programs are organised by age or by stage of life. Ask the provider who the group is designed for, and whether the topics match your interests."],
        ],
    ],
    "Hearing equipment" => [
        "day" => "Getting hearing equipment starts with a hearing assessment, after which an audiologist or hearing specialist recommends devices that match your hearing, your lifestyle and your preferences. Devices are then fitted and programmed, and you are shown how to insert them, use the controls, change batteries or charge them, and clean and store them.\n\nThe first stretch of use is a period of getting used to the sound, and follow-up appointments let the specialist fine-tune the settings. Regular reviews after that check the devices are working well and your hearing has not changed. Accessories such as remote microphones, phone connections and alerting devices may also be part of the picture.",
        "who" => "Audiologists and audiometrists assess hearing and fit hearing devices, and some services are provided through hearing clinics, hospitals or government programs. Specialists in cochlear implants and other implantable devices work in specialist clinics. Ask about the range of devices the clinic can offer and whether they are independent or tied to one manufacturer.",
        "fit" => "Hearing equipment is part of a broader approach to communication, alongside hearing services, communication supports and, for some people, sign language or interpreting. Good outcomes rely on ongoing care, since devices need maintenance and hearing can change. It also helps to think about equipment for specific situations such as work, study, phone calls and safety at home.",
        "ask" => [
            "What range of devices do you fit, and are you independent of any manufacturer?",
            "How will you match the device to my lifestyle and the situations where I struggle?",
            "What follow-up and adjustments are included after fitting?",
            "How do I clean, maintain and replace parts, and what happens if a device breaks?",
            "Are there accessories that could help with phone calls, television or noisy places?",
            "How often should I have my hearing and devices checked?",
        ],
        "mistakes" => [
            "Giving up on a device during the adjustment period rather than returning for fine-tuning.",
            "Not asking about care and maintenance, which shortens the life of the device.",
            "Choosing based on price or appearance alone, without checking it suits how you live.",
            "Ignoring changes in hearing that mean the settings need updating.",
            "Not considering accessories that help in specific situations.",
        ],
        "faq" => [
            ["Why do hearing aids need adjusting after they are fitted?", "The brain takes time to adapt to new sounds, and real-life use shows what the clinic could not predict. Follow-up visits let the audiologist adjust settings so the sound is comfortable and clear."],
            ["Can hearing devices connect to my phone?", "Many modern devices connect to phones and other equipment by Bluetooth. Ask the audiologist which options are available and compatible with your phone."],
            ["What should I do if a device stops working?", "Check the battery or charging first, then contact your clinic. They can often repair or replace the device or provide a loan while it is being fixed."],
        ],
    ],
    "Hearing services and audiology" => [
        "day" => "An audiology appointment usually begins with a conversation about your hearing, health history and any difficulties you notice. The audiologist examines your ears and carries out hearing tests in a quiet booth, playing tones and words at different volumes. They explain the results in plain language and talk through what the results mean for daily life.\n\nIf you need treatment or devices, the audiologist discusses options, and may refer you to a doctor or ear specialist if there is a medical concern. Follow-up may include fitting and adjusting devices, hearing rehabilitation, tinnitus management and advice on protecting your hearing.",
        "who" => "Audiologists have university qualifications in audiology and many belong to professional associations that set standards. Audiometrists carry out hearing tests and fit devices, particularly in hearing service programs. Ear, nose and throat specialists deal with medical and surgical issues. Ask about the clinician's qualifications and experience, particularly if you need help with a complex hearing problem or with a child's hearing.",
        "fit" => "Hearing services are the foundation for other communication supports, including hearing equipment, speech therapy and interpreting. They also link with education and employment, since hearing affects learning and work. Regular hearing checks are important because hearing can change, and finding a change early helps you keep up with the things you want to do.",
        "ask" => [
            "What qualifications do you have, and do you have experience with people like me or my child?",
            "What tests will you do, and what will they tell us?",
            "Will you explain the results and my options in plain language?",
            "Can you help with tinnitus or balance problems, or will you refer me elsewhere?",
            "How will you work with my doctor or an ear specialist if needed?",
            "How often should I have my hearing checked?",
        ],
        "mistakes" => [
            "Delaying a hearing test because the change is gradual and you have adapted to it.",
            "Assuming hearing problems are just part of getting older and cannot be helped.",
            "Not returning for reviews after starting to use hearing devices.",
            "Ignoring sudden hearing loss, which needs urgent medical attention.",
            "Not protecting your hearing in noisy work or leisure settings.",
        ],
        "faq" => [
            ["How do I know if I need a hearing test?", "Signs include asking people to repeat themselves, trouble following conversations in noise, turning the television up, or ringing in the ears. Children may not respond to sounds or may have delayed speech. If you are unsure, a test is a simple way to find out."],
            ["Does a hearing test hurt?", "No. It involves listening for tones and words, and looking in your ears. It is quiet, painless and normally quite quick."],
            ["What should I do if my hearing suddenly drops?", "Sudden hearing loss can be a medical emergency, so see a doctor or go to an emergency department promptly rather than waiting to see if it passes."],
        ],
    ],
    "High-intensity personal care" => [
        "day" => "High-intensity personal care involves complex tasks that need particular training, such as help with breathing equipment, tube feeding, catheter care or managing seizures. The worker arrives having been trained in your specific routines, and carries them out to the standard set out in your plan or by your health professionals.\n\nThe work depends on precision and consistency. Workers follow a written care plan, record what they do and watch for changes in your health or comfort. Because the tasks carry real risk, the worker also knows what to do in an emergency, who to call and when to seek help.",
        "who" => "Workers who deliver high-intensity supports need extra, specific training for each task, and that training usually comes from a nurse, allied health professional or the person who knows your routines. They must be assessed as competent before working on their own. Providers should be able to tell you what training their workers have, how they check competence and how often it is refreshed.",
        "fit" => "High-intensity personal care usually works alongside health professionals such as your doctor, nurse and therapists, who define what needs to be done. It often overlaps with community nursing, medication assistance and equipment. Everyone who provides care needs the same up-to-date information, so keeping the care plan current and shared is a big part of doing it well.",
        "ask" => [
            "What specific training do your workers have for the tasks I need?",
            "How do you check that workers are competent before they work with me alone?",
            "Who writes and updates my care plan, and how is it shared with the team?",
            "What is your emergency procedure, and how quickly can help be arranged?",
            "How will you make sure the same trained workers are rostered on my care?",
            "How do you handle a worker who is unwell or unavailable at short notice?",
        ],
        "mistakes" => [
            "Allowing untrained workers to carry out tasks that need specific training.",
            "Not keeping the care plan up to date when health needs change.",
            "Having no back-up plan when a trained worker is unavailable.",
            "Failing to agree on what to do in an emergency.",
            "Not sharing information between the workers, nurses and family.",
        ],
        "faq" => [
            ["What makes personal care high intensity?", "It involves tasks that carry higher risk or need specialised skills, such as managing breathing or feeding equipment, complex health needs or challenging behaviours. Workers need specific training to do them safely."],
            ["Who trains a worker to do these tasks?", "Usually a nurse, an allied health professional or someone else with the right expertise, who shows the worker how to do the task for your particular needs and checks they are competent."],
            ["What should I do if I have a concern about a worker's skills?", "Raise it with the provider straight away, and if it is not resolved you can contact the NDIS Quality and Safeguards Commission. Your safety comes first."],
        ],
    ],
    "Higher education and training support" => [
        "day" => "Support in higher education might include help with enrolling, choosing a course, organising assistive technology, arranging adjustments with the disability service, and finding your way around campus. During term, a support worker or mentor may help with getting to class, taking notes, organising study and managing deadlines.\n\nThe support changes as you move through your course. In the early stage it may focus on getting set up and understanding the systems, and later on assignments, exams and placements. Regular check-ins help catch problems early and keep you connected to the teaching staff and disability service.",
        "who" => "Support is provided by workers, mentors and tutors, often working alongside the university or training provider's disability service. Occupational therapists and specialist tutors can help with assessment and strategies. Ask whether the person has experience supporting students with your kind of needs, and how they work with the education provider.",
        "fit" => "Study support fits with the adjustments the education provider makes, such as extra time, accessible materials and note-taking. It also connects with transport, assistive technology, housing and employment planning. Thinking early about what you will do after study helps you choose courses, placements and supports that lead somewhere you want to go.",
        "ask" => [
            "How will you work with my university or training provider's disability service?",
            "Can you help with organising study, assignments and exam arrangements?",
            "What experience do you have supporting students with my kind of needs?",
            "How will the support change as I progress through the course?",
            "Can you help with placements and preparing for work?",
            "How will we review whether the support is helping me succeed?",
        ],
        "mistakes" => [
            "Waiting until problems arise before contacting the disability service.",
            "Not organising adjustments before the course starts.",
            "Relying on a support worker to do the work rather than to help you learn.",
            "Not planning for exams, placements and assessment periods, which are often the hardest.",
            "Leaving decisions about what to do after study to the last moment.",
        ],
        "faq" => [
            ["What adjustments can a university make?", "Common adjustments include extra time, accessible materials, note-taking support, flexible attendance and alternative assessment formats. The disability service can explain what is available and what evidence they need."],
            ["Can support workers attend classes with me?", "Often yes, but you should tell the education provider so arrangements can be made. Talk to the disability service about how it works."],
            ["Is study support available for vocational courses as well as university?", "Yes. TAFE and other training providers have similar disability services, and you can arrange support in much the same way."],
        ],
    ],
    "Home enteral nutrition (HEN)" => [
        "day" => "Home enteral nutrition means receiving nutrition through a tube into the stomach or bowel, in your own home. A typical day includes preparing the feed, connecting the equipment, running the feed at the right rate, flushing the tube and cleaning the equipment afterwards. Some people do this themselves, while others have help from a carer, support worker or nurse.\n\nRegular reviews with a dietitian and nurse check that the feed, the amount and the timing are right and that the tube site is healthy. They also help with practical problems such as blockages, leaks and skin irritation, and with supplies and equipment.",
        "who" => "Enteral nutrition is managed by a team that may include a doctor, a dietitian, a nurse, a speech pathologist and sometimes a specialised nutrition nurse. Support workers can help with feeds when they have been trained and are supervised. Training is essential, and the person or carer who will do the feeds should feel confident before the hospital or clinic hands over.",
        "fit" => "Home enteral nutrition sits within a wider health plan, and it works with community nursing, dietetic care, equipment supply and sometimes speech pathology if swallowing is affected. Supplies come regularly, so a reliable ordering and delivery system is an important part of the arrangement. Planning for holidays, hospital stays and emergencies helps prevent gaps in care.",
        "ask" => [
            "Who will train me or my carers, and how do we know when we are confident?",
            "Who do I call for help outside business hours if there is a problem with the tube or the feed?",
            "How are supplies ordered and delivered, and what if they are delayed?",
            "How often will the dietitian and nurse review the feeding plan?",
            "Are support workers trained and supervised to help with feeds?",
            "How should we plan for travel, holidays and hospital stays?",
        ],
        "mistakes" => [
            "Leaving the training too short, so carers feel unsure when problems arise.",
            "Running out of supplies because there is no reliable ordering process.",
            "Not asking who to call after hours.",
            "Not keeping the dietitian informed when weight, health or appetite changes.",
            "Not cleaning equipment and tube sites as instructed, which raises the risk of infection.",
        ],
        "faq" => [
            ["Can a support worker help with tube feeding?", "Yes, once they have been properly trained and are supervised by a nurse or other health professional. The training needs to cover the specific equipment and routines for the person they support."],
            ["What should I do if the tube becomes blocked or comes out?", "Follow the instructions you were given, and contact your nurse, doctor or hospital promptly if you cannot fix it. Make sure you know the emergency steps before you need them."],
            ["Can I still eat and drink by mouth?", "Some people can, and some cannot safely swallow. A speech pathologist and doctor will advise on what is safe for you."],
        ],
    ],
    "House cleaning and household tasks" => [
        "day" => "A cleaning visit follows a checklist agreed with you, such as vacuuming, mopping, bathrooms, kitchen, changing bed linen and taking out rubbish. The worker arrives at the arranged time, uses cleaning products that suit you and your home, and leaves it tidy. Some visits also cover tasks like laundry or ironing.\n\nRegular visits help keep the home safe and comfortable, particularly if you have difficulty with heavy or repetitive tasks. It is worth talking about what matters most to you, such as certain rooms, products or the way things are stored, so the worker does things the way you want.",
        "who" => "Cleaning and household tasks are carried out by domestic assistance workers, support workers and cleaning companies. Some providers specialise in support for people with a disability and understand issues such as allergies, hoarding, accessibility and respecting your belongings. Ask whether workers are screened and insured, and who is responsible if something is damaged.",
        "fit" => "This support frees your time and energy for other things and works alongside household management, meal preparation and personal care. It may be scheduled around other appointments and supports. For some people, the aim is to keep the home safe and healthy, and for others it is to keep up independence by getting help with the tasks that are hardest.",
        "ask" => [
            "What is included in a visit, and how can I change the list of tasks?",
            "What products do you use, and can you use my own if I have allergies or preferences?",
            "How do you screen workers, and what insurance do you have?",
            "What happens if something is damaged or goes missing?",
            "Can I have the same worker each time?",
            "How do I change or cancel a visit?",
        ],
        "mistakes" => [
            "Not agreeing on a written list of tasks, which leads to misunderstandings.",
            "Not mentioning allergies or sensitivities to certain products.",
            "Leaving valuables out or not agreeing what the worker can and cannot touch.",
            "Not checking insurance and screening.",
            "Assuming heavy work such as moving furniture or garden work is included.",
        ],
        "faq" => [
            ["Can I ask for the same cleaner each time?", "Many providers try to arrange this because consistency helps. Ask about it when you set up the service, and let them know if a change of worker does not suit you."],
            ["What if I am not happy with the standard of cleaning?", "Talk to the worker or provider soon after, and be specific about what needs to change. A good provider will want to fix it."],
            ["Does the worker need to be home when I am there?", "You decide. Some people prefer to be at home, while others give the worker access. Agree this in advance and put it in writing."],
        ],
    ],
    "Household management" => [
        "day" => "Household management is broader than cleaning. It can include organising shopping, planning meals, keeping track of bills, arranging repairs, managing laundry, and keeping the house running smoothly. A worker might do some of these tasks, or coach you to do them yourself, depending on what you prefer.\n\nA typical session might begin with a look at what needs doing that week, then work through it together, such as writing a shopping list, putting away groceries, checking the pantry and planning a couple of meals. Over time, the worker helps you build routines and systems that make it easier to stay on top of things.",
        "who" => "Household management support is provided by support workers, domestic assistance workers and sometimes occupational therapists who help you work out routines and strategies. Choose someone who respects your home and your choices, who can work in the way you like and who is comfortable teaching as well as doing.",
        "fit" => "This support connects with cleaning, meal preparation, financial skills and independent living. It can be part of a move toward more independence, or an ongoing support that lets you live in your own home. Reviewing it periodically shows whether the balance between doing and teaching is right for you.",
        "ask" => [
            "How will you decide with me which tasks you do and which I do myself?",
            "How will you help me build routines that I can maintain?",
            "How do you organise shopping and deliveries, and how do you handle my money?",
            "How will you respect my home and my way of doing things?",
            "How will we review whether the support is meeting my needs?",
            "What happens if my needs change?",
        ],
        "mistakes" => [
            "Having tasks done for you when you would prefer to learn to do them.",
            "Not being clear about who handles money and receipts for shopping.",
            "Letting routines get complicated, which makes them hard to keep.",
            "Not reviewing the arrangement as your skills and needs change.",
            "Leaving tasks such as bills and repairs to build up until they become urgent.",
        ],
        "faq" => [
            ["What is the difference between household management and cleaning?", "Cleaning covers the physical work of keeping the house clean. Household management is wider and covers the planning and organising that keeps a home running, such as shopping, meals, bills and repairs."],
            ["Can a worker do my shopping for me?", "Yes, if that is what you want, and it should be clear how money and receipts are handled. Some people prefer to shop with a worker so they can make their own choices."],
            ["Can I learn to manage my household on my own?", "Many people do, with practice and the right support. A worker or therapist can teach skills step by step and gradually reduce their involvement."],
        ],
    ],
    "Household task equipment" => [
        "day" => "Household task equipment is anything that makes everyday jobs safer and easier, such as adapted kitchen tools, jar openers, long-handled reachers, perching stools, easy-grip utensils, lightweight vacuum cleaners or trolleys for carrying items. An occupational therapist or supplier usually looks at the tasks you find difficult and suggests equipment to try.\n\nOnce the equipment is chosen, you try it in your own home, in the kitchen, laundry or wherever it will be used. A good supplier or therapist gives you time to check that it really helps, shows you how to use it safely and makes sure it is stored where you can reach it.",
        "who" => "Occupational therapists are often the best people to recommend household equipment, since they look at how you do tasks and what gets in the way. Suppliers and specialist retailers stock a wide range of products. Ask about experience with equipment for your particular needs, and whether you can trial items before you buy.",
        "fit" => "Household equipment complements household management, cleaning and personal care supports. Sometimes a simple piece of equipment means you can do a task yourself and need less hands-on help. It also links with home modifications, since some problems are better solved by changing the space than by adding equipment.",
        "ask" => [
            "Which tasks are hardest for me, and what different kinds of equipment could help?",
            "Can I try the equipment in my own home before I buy?",
            "How will you show me how to use it safely?",
            "How durable is the equipment, and what happens if it breaks?",
            "Is there equipment that would do the same job more simply or more cheaply?",
            "Could a small change to my home make the task easier instead?",
        ],
        "mistakes" => [
            "Buying gadgets that look helpful but do not suit your needs.",
            "Not trying equipment before buying it.",
            "Choosing equipment that is hard to store or reach, so it goes unused.",
            "Not considering safety, such as slip resistance and stability.",
            "Not reviewing equipment when your needs change.",
        ],
        "faq" => [
            ["Do I need an occupational therapist to choose household equipment?", "Not always, but a therapist can help you pick equipment that suits your body and the way you work, especially for complex needs. For simple items you may be able to choose yourself."],
            ["Where can I buy equipment for household tasks?", "Specialist disability equipment suppliers, some pharmacies and larger retailers stock a range. A therapist or your provider can suggest where to look."],
            ["Can I trial equipment before buying?", "Many suppliers allow trials, and a therapist may be able to arrange one. It is a good idea to test items in your own kitchen or home."],
        ],
    ],
    "Housing search and matching" => [
        "day" => "Housing search support usually begins with a conversation about what kind of home you want, where you want to live, who you might live with and what supports you need. A worker then helps you look at the options, such as rental properties, shared houses, specialist disability accommodation and social housing, and helps you understand how each works.\n\nThey may help with finding listings, arranging inspections, preparing applications and references, understanding tenancy agreements and organising the supports you need in the home. Matching is about fit, so the worker considers compatibility, location, accessibility and how the arrangement will work over time.",
        "who" => "Support with housing search is provided by support coordinators, housing support workers and specialist housing providers. Some organisations focus on helping people with disability find suitable homes. It is worth choosing someone who knows the local market, understands accessible housing and takes time to find out what you really want.",
        "fit" => "Finding a home is a major step, and it connects with support coordination, tenancy skills, home modifications and daily living supports. It is helpful to plan supports and housing together, since the right home can reduce the support you need, and the wrong one can create new problems. A move also involves practical things such as packing, changing addresses and setting up utilities.",
        "ask" => [
            "How will you find out what kind of home and support I want?",
            "What housing options do you know about in my area, including accessible and shared homes?",
            "How will you help me with applications, inspections and paperwork?",
            "How will you help me work out whether a home and housemates are a good match?",
            "What support will I have after I move in?",
            "How do you help if things do not work out?",
        ],
        "mistakes" => [
            "Rushing into a home that does not suit your needs because of time pressure.",
            "Not visiting the property or meeting housemates first.",
            "Overlooking accessibility features until after you move in.",
            "Not understanding the tenancy agreement and your rights.",
            "Not planning the support you need to settle in.",
        ],
        "faq" => [
            ["What types of housing are available for people with disability?", "Options include private rental, social and community housing, shared houses, supported accommodation and specialist disability accommodation for people with very high support needs. The right choice depends on your needs and preferences."],
            ["Can someone help me apply for social housing?", "Yes. A support coordinator or housing worker can help you understand the process, gather documents and complete applications."],
            ["What is matching?", "Matching means finding a home and housemates that suit you in terms of location, needs, interests and personality, so that the arrangement is likely to work well for everyone."],
        ],
    ],
    "Individualised Living Options (ILO)" => [
        "day" => "An Individualised Living Option is a way of arranging a home and supports around the person, rather than fitting the person into an existing model. The process usually begins with exploring what you want from your home life and who you want around you. This is followed by designing a support arrangement, which might involve living alone with tailored support, sharing with a friend or living with a host family.\n\nOnce the arrangement is up and running, day to day life is shaped by your routines and choices. Support workers help where you need it, and a coordinator or planner reviews how it is going and adjusts as things change. The idea is that the arrangement flexes with your life, not the other way around.",
        "who" => "ILO involves people with experience in planning individualised arrangements, including support coordinators, specialist planners and providers who can deliver flexible support. It also involves the person, their family and friends, who play an important role. It is worth asking whether a provider has experience with individualised arrangements, since they work differently from group models.",
        "fit" => "ILO sits within the wider group of housing and living options and may involve a range of other supports, such as personal care, community access and therapy. It suits people who want more choice and control over where and how they live. Because it is tailored, it takes careful planning and regular reviews to make sure it continues to work.",
        "ask" => [
            "How do you explore and design an arrangement around what I want?",
            "What experience do you have with individualised living arrangements?",
            "How are staffing and rosters organised so support fits my routine?",
            "How will you help me stay connected with friends, family and the community?",
            "How do you review and adjust the arrangement over time?",
            "What is the plan if the arrangement needs to change?",
        ],
        "mistakes" => [
            "Not exploring what you really want before settling on an arrangement.",
            "Leaving out family and friends who could help with design and support.",
            "Not planning for staffing gaps or emergencies.",
            "Skipping regular reviews, so the arrangement drifts from what you need.",
            "Assuming an individualised arrangement is more complicated than it needs to be.",
        ],
        "faq" => [
            ["How is an individualised living option different from supported independent living?", "Supported independent living usually involves shared housing with rostered support, while an individualised option is designed around one person, and might involve living alone, with a friend or with a host family."],
            ["Can an individualised arrangement include a friend as a housemate?", "That is often possible, and it is one of the strengths of an individualised approach. Everyone involved needs to agree, and the support arrangements are designed around the household."],
            ["Who helps set up an individualised arrangement?", "A support coordinator or specialist planner can help with exploring options, working out the supports and connecting you with providers."],
        ],
    ],
];
