<?php
/** Long-form guide content, batch 4. See content-long-1.php for the shape. */
if (!defined('ABSPATH')) exit;

return [
    'Innovative community participation' => [
        'cat' => 'Community access',
        'short' => 'Innovative community participation is support to take part in the community in new or creative ways that suit what you want to do, beyond standard programs.',
        'overview' => "Not everyone wants a weekly group outing or a standard day program. Innovative approaches start with the person: what they love, what they are curious about and what they would like to try. That might mean starting a small business, joining a band, volunteering in an unusual place, learning a craft or building a project with friends.\n\nBecause each plan is different, the support is designed from scratch. A provider works with you to shape the idea, find the people and places that can make it happen and provide the practical support that lets you take part. It often involves working with community groups and local businesses, not only with disability services.\n\nSuccess is measured by what matters to you, such as new friendships, new skills or a real role in your community. Good providers explain how they will review progress, and are honest when an idea needs to change.",
        'choose' => [
            'Ask for examples of similar projects the provider has supported.',
            'Find out how they will help you shape an idea into a plan.',
            'Ask how they work with local groups and businesses.',
            'Check how they will review whether it is working.',
            'Ask how they handle it if the idea needs to change.',
        ],
        'start' => [
            'Write down what you would love to try.',
            'Talk to your planner or support coordinator about how it might fit your plan.',
            'Speak to providers who like to work creatively.',
            'Agree a small first step and a date to review.',
        ],
        'faq' => [
            ['Do I need a fully formed idea?', 'No. A good provider helps you explore possibilities and turn them into a plan.'],
            ['Can it involve friends?', 'Often yes. Taking part with people you know can make it easier and more enjoyable.'],
            ['What if the idea does not work out?', 'That is a normal part of trying new things. A good provider helps you learn from it and try another approach.'],
        ],
    ],
    'Interpreting and translation' => [
        'cat' => '',
        'short' => 'Interpreting deals with spoken or signed communication, and translation deals with written material. Both help people who use a language other than English, including Auslan, to understand and be understood.',
        'overview' => "Being able to communicate with providers, doctors and services in the language you use is essential for making informed choices. Interpreters convert spoken or signed language in real time, for example at an appointment, while translators convert written text such as letters, forms and plans.\n\nProfessional interpreters and translators are trained to be accurate, impartial and confidential. Relying on family members, especially children, can put pressure on them and may lead to mistakes or missed information. Professional services are available in a wide range of languages, including Auslan, and can be arranged by phone, video or in person.\n\nIf you need an interpreter, tell the service when you book so it can be arranged in advance. Ask about the interpreter's qualifications and how confidentiality is handled, and let them know about any specialised terms, such as health or legal words, that will come up.",
        'choose' => [
            'Ask whether interpreters are professionally qualified and accredited.',
            'Find out how quickly an interpreter can be arranged.',
            'Check whether the service covers your language or dialect.',
            'Ask whether they offer phone or video options.',
            'Ask how they keep information confidential.',
        ],
        'start' => [
            'Tell services early that you need an interpreter and which language you use.',
            'Ask for a professional interpreter rather than relying on family.',
            'Share any documents in advance so the interpreter can prepare.',
            'Give feedback about how it went so future bookings improve.',
        ],
        'faq' => [
            ['Can a family member interpret for me?', 'It is usually better to use a professional interpreter, especially for health and legal matters, so that accuracy and privacy are protected.'],
            ['Are Auslan interpreters available?', 'Yes. Auslan interpreters are available through specialist services. Book early for appointments.'],
            ['Can documents be translated?', 'Yes, by qualified translators. Ask how long it will take and whether certified translation is needed.'],
        ],
    ],
    'Job coaching and workplace assistance' => [
        'cat' => 'Employment & education support',
        'short' => 'Job coaching gives on-the-job support to help you learn a role, settle into a workplace and keep working. It can include practical help at work and coaching to build skills and confidence.',
        'overview' => "Starting a new job means learning tasks, routines, a new environment and new relationships all at once. A job coach supports you through that. They might help you learn the steps of a task, work out a routine, communicate with colleagues or manage sensory and physical needs at work.\n\nSupport is usually most intensive at the start and reduces as you gain confidence, although some people continue to need help. The aim is for you to do your job well, with only as much support as you need, and for the workplace to become more confident supporting you.\n\nWorking with the employer matters. With your agreement, a job coach can talk with your manager about adjustments and about how colleagues can help. You decide what is shared, and a good coach will always check with you first.",
        'choose' => [
            'Ask how the job coach works alongside you and your employer.',
            'Find out how support is reduced over time as you gain confidence.',
            'Ask about their experience in your industry.',
            'Check what you will and will not share with your employer.',
            'Ask how they respond if a job is not going well.',
        ],
        'start' => [
            'Talk to your employer or employment provider about support at work.',
            'Contact job coaching providers and describe the job.',
            'Agree what the coach will help with and how often.',
            'Review regularly and plan how support will change over time.',
        ],
        'faq' => [
            ['Will my colleagues know I have a job coach?', 'That depends on what you and your employer agree. Discuss how you want it handled.'],
            ['How long will I have a job coach?', 'It varies. Support usually reduces as you become confident, but some people continue to need it.'],
            ['Can a job coach help me change jobs?', 'Yes. Coaches can support transitions and help you learn a new role.'],
        ],
        'src' => ['jobaccess'],
    ],
    'Life transition planning and mentoring' => [
        'cat' => 'Life skills',
        'short' => 'Life transition planning and mentoring prepares you for a major change, such as leaving school, moving out or starting work, so the change feels clearer and more manageable.',
        'overview' => "Big changes can feel overwhelming, particularly when there are many things to organise at once. Transition support breaks a change into steps, so you know what needs to happen and when. It can include exploring options, setting goals, building the skills you will need and putting the right supports in place.\n\nMentoring adds the guidance of someone with experience. A mentor might be an experienced support worker, a coach or a peer who has been through a similar change. They listen, share what they have learned and encourage you along the way.\n\nStarting early is one of the best things you can do. Planning well before a change, such as a year before leaving school, leaves time to try things, make mistakes and adjust. It also helps family and supporters feel more prepared.",
        'choose' => [
            'Ask how the provider helps you set goals and plan steps.',
            'Find out about the background of the mentors.',
            'Check how they involve family and supporters.',
            'Ask how they link with schools, employers and other services.',
            'Find out how plans are reviewed and updated.',
        ],
        'start' => [
            'Think about the change ahead and what you want it to look like.',
            'List the questions and worries you have.',
            'Contact providers and ask how they support transitions.',
            'Create a step-by-step plan with dates and review points.',
        ],
        'faq' => [
            ['How far ahead should I plan a big change?', 'As early as possible. Starting well before the change gives time to explore and prepare.'],
            ['Can family come to planning sessions?', 'Yes, if you want them to. Involving family often helps everyone feel prepared.'],
            ['What if my plans change?', 'That is normal. A good plan is flexible and reviewed regularly.'],
        ],
    ],
    'Low-cost assistive technology' => [
        'cat' => 'Assistive technology & equipment',
        'short' => 'Low-cost assistive technology is simple, everyday equipment that supports independence, such as adapted utensils, grab rails, alarms and magnifiers.',
        'overview' => "Not all assistive technology is complex or expensive. Many effective aids are simple: easy-grip handles, jar openers, pill organisers, large-print clocks, bath boards, non-slip mats and personal alarms. They solve everyday problems at home, and can make tasks safer, faster or possible.\n\nBecause these items are widely available, people often buy them without advice. That works for many, but an occupational therapist can help you choose well, especially if you are not sure what will suit. They can also suggest changes to how you do a task that reduce the need for equipment.\n\nWhere you buy matters. Specialist suppliers and pharmacies stock a range of aids and can often offer advice, and some general retailers carry useful items. Check returns, read reviews and be cautious about anything that claims to fix everything.",
        'choose' => [
            'Ask whether you can try the item before buying.',
            'Check the size, weight and grip against your abilities.',
            'Consider how easy it is to clean and maintain.',
            'Ask about returns and warranty.',
            'Get advice from an occupational therapist for more complex needs.',
        ],
        'start' => [
            'Identify the everyday tasks that cause difficulty.',
            'Ask a therapist or supplier about simple aids that might help.',
            'Try one or two items and see how they work.',
            'Add or swap items as your needs change.',
        ],
        'faq' => [
            ['Do I need a therapist to buy low-cost items?', 'Not always, but advice helps you avoid buying things that do not suit.'],
            ['Can simple aids be safe for older people?', 'Yes. Items such as grab rails and non-slip mats reduce the risk of falls, but they should be installed and used correctly.'],
            ['Are cheap items lower quality?', 'Not necessarily, but it is worth checking reviews and warranty before you buy.'],
        ],
    ],
    'Meal preparation' => [
        'cat' => 'Domestic assistance',
        'short' => 'Meal preparation is help with planning, preparing and cooking meals, either by supporting you to cook or by preparing meals for you.',
        'overview' => "Preparing meals involves many steps: planning, shopping, chopping, cooking, serving and cleaning up. If any of these are difficult, a support worker can step in. They might cook with you so you keep your skills, prepare meals in advance for the week, or cook for you when you are tired or unwell.\n\nNutrition matters. If you have dietary needs, allergies or a medical condition, a dietitian can provide guidance that workers should follow. Workers should also respect your preferences, culture and religious requirements, and be aware of food safety.\n\nMany people want to build their cooking skills rather than hand over the task. Support can be arranged to teach recipes step by step, using safe equipment and adapting tasks to what you can do. It can be a rewarding way to gain independence.",
        'choose' => [
            'Tell the provider about dietary needs, allergies and preferences.',
            'Ask how workers handle food safety and hygiene.',
            'Check whether they can shop for ingredients with you or for you.',
            'Ask whether they can teach cooking skills.',
            'Find out what happens if your regular worker is away.',
        ],
        'start' => [
            'Decide which meals you want help with and how often.',
            'Talk to your provider about your preferences and any dietary needs.',
            'Agree who does the shopping and how it is paid for.',
            'Review after a few weeks and adjust.',
        ],
        'faq' => [
            ['Can a worker cook meals for the whole week?', 'Often yes, if agreed in advance. Ask about storage, labelling and reheating.'],
            ['Can I learn to cook with support?', 'Yes. Many workers teach cooking skills step by step.'],
            ['How do I make sure meals suit my dietary needs?', 'Provide the details and any dietitian advice so workers follow it closely.'],
        ],
    ],
    'Medication assistance' => [
        'cat' => 'Nursing',
        'short' => 'Medication assistance is support to take medication safely as prescribed, such as reminders, prompting and help preparing or giving doses.',
        'overview' => "Taking the right medication at the right time matters, and can be hard to manage alone. Support ranges from reminders and prompting, through to helping open packaging or setting up a dosette box, to giving doses where that is appropriate and agreed.\n\nWhat a support worker can do depends on the person, the medication and the provider's policies. Your doctor or pharmacist can advise on what is needed, and many providers require a written medication plan. Workers should have relevant training and should record what is given.\n\nGood practice includes checking that everyone involved has the same information, storing medications safely, and knowing what to do if a dose is missed or something goes wrong. Regular medication reviews with your doctor or pharmacist help make sure the plan still suits you.",
        'choose' => [
            'Ask how workers are trained in medication support.',
            'Check whether the provider uses written medication plans and records.',
            'Find out what happens if a dose is missed or an error occurs.',
            'Ask how they communicate with your doctor and pharmacist.',
            'Check how medications are stored.',
        ],
        'start' => [
            'Ask your doctor or pharmacist to review your medication and provide a written list.',
            'Share it with your provider and agree what help is needed.',
            'Consider a dosette box or blister packs to make it easier.',
            'Review regularly and update the plan when your medication changes.',
        ],
        'faq' => [
            ['Can any support worker give medication?', 'Not necessarily. It depends on their training and the provider\'s policies. Ask what workers are permitted to do.'],
            ['What is a dosette box?', 'A container that holds a person\'s medication sorted by day and time. Pharmacists can prepare them.'],
            ['Where can I get a medication review?', 'Your doctor or pharmacist can review your medications and explain what each one is for.'],
        ],
    ],
    'Medium Term Accommodation (MTA)' => [
        'cat' => 'Housing (SDA & SIL)',
        'short' => 'Medium term accommodation is housing for a temporary period, for example while waiting for a long-term home or for modifications to be finished.',
        'overview' => "Sometimes a person cannot go straight from one living situation to the next. They may be leaving hospital and waiting for a home to be modified, or they may need somewhere to live while a long-term option is arranged. Medium term accommodation fills that gap.\n\nIt is different from respite, which is a short break with a return home. Medium term stays are longer and the aim is to bridge a period between one home and another. The accommodation may be in a purpose-built home, a shared house or another suitable place.\n\nBefore you move in, ask about what the home is like, what support is available, how long you can stay and how the move to your next home will be planned. Having a clear plan for what happens next reduces stress and helps make sure the stay does its job.",
        'choose' => [
            'Ask about the type of home and the support available.',
            'Find out how long you can stay and what happens if your next home is delayed.',
            'Check accessibility, including bathroom and bedroom.',
            'Ask how the stay will be planned around your next move.',
            'Check how costs and rules are explained in the agreement.',
        ],
        'start' => [
            'Talk to your planner or support coordinator about why you need temporary housing.',
            'Ask providers about availability and suitability.',
            'Visit if you can and check accessibility.',
            'Agree a plan for moving to your long-term home.',
        ],
        'faq' => [
            ['How is this different from respite?', 'Respite is a short break with a return home. Medium term accommodation bridges a longer gap between homes.'],
            ['Can I bring my own belongings?', 'Usually yes. Ask about space and what is provided.'],
            ['Who helps me plan the move?', 'Your support coordinator or planner can help, together with the housing provider.'],
        ],
    ],
    'Minor home modifications' => [
        'cat' => 'Home modifications',
        'short' => 'Minor home modifications are smaller changes that make your home easier and safer to use, such as fitting handrails, ramps or adjusting fixtures.',
        'overview' => "You do not always need major building work to make a home suit you. Small changes can have a large effect: rails beside steps and in bathrooms, a short ramp at the door, lever taps, non-slip flooring, lowering shelves or adjusting a shower. They improve safety and make daily tasks easier.\n\nA short assessment by an occupational therapist is a good starting point. They can suggest the right changes and where to place them, and advise on how to use them safely. Licensed tradespeople or specialist modification providers then carry out the work.\n\nAsk for a written quote, check that the person doing the work is suitably qualified and licensed, and confirm what is included. If you rent, ask the owner or agent before making changes, because approval is usually required.",
        'choose' => [
            'Check that tradespeople are licensed and insured.',
            'Ask for a written quote that describes the work.',
            'Ask how long the job will take and whether it will disrupt your home.',
            'Check that the changes meet relevant standards.',
            'Ask about warranty and who to contact if something is not right.',
        ],
        'start' => [
            'Identify where you have difficulty in your home.',
            'Ask an occupational therapist for advice.',
            'Get a written quote from a qualified provider.',
            'If you rent, get permission from the owner before work begins.',
        ],
        'faq' => [
            ['Do I need permission to modify a rental home?', 'You generally need the owner\'s agreement. Ask early.'],
            ['Can I take modifications with me when I move?', 'Some items, such as removable rails, can be moved. Ask the installer what is possible.'],
            ['Are handrails enough to prevent falls?', 'They help, but a falls-prevention assessment looks at lighting, flooring, footwear and more.'],
        ],
    ],
    'Mobility equipment' => [
        'cat' => 'Assistive technology & equipment',
        'short' => 'Mobility equipment helps people move around, such as wheelchairs, walking frames, scooters and transfer aids. The right choice depends on your body, your home and how you live.',
        'overview' => "Choosing mobility equipment is a personal decision. A manual wheelchair, a power chair, a walking frame and a mobility scooter each suit different people and different environments. What works well indoors may not work outdoors, and equipment needs to fit both the person and the spaces they use.\n\nA physiotherapist or occupational therapist can assess your needs, take measurements and recommend options. Trying equipment in your own environment is one of the best ways to check comfort, control and fit. Ask about adjustments, seating and pressure care, which matter for anyone sitting for long periods.\n\nOnce you have equipment, maintenance keeps it safe. Ask about servicing, repairs and what to do if something breaks, so you are not left without mobility for long. Review your equipment regularly, because your needs may change.",
        'choose' => [
            'Ask for a trial in your home and in the places you go.',
            'Check how the equipment can be adjusted as your needs change.',
            'Ask about servicing, warranty and repairs, including loan equipment.',
            'Consider transport, storage and charging.',
            'Ask a therapist to check seating, posture and pressure care.',
        ],
        'start' => [
            'Write down where and how you want to move.',
            'Book an assessment with a physiotherapist or occupational therapist.',
            'Trial the recommended options.',
            'Arrange training, delivery and a first service check.',
        ],
        'faq' => [
            ['How do I choose between a wheelchair and a scooter?', 'It depends on your body, environment and needs. A therapist can compare them with you.'],
            ['Can equipment be customised?', 'Often yes. Seating, controls and accessories can be adjusted for you.'],
            ['What if I outgrow or no longer suit my equipment?', 'Review it with your therapist. Equipment should be reassessed as needs change.'],
        ],
    ],
    'Music therapy and art therapy' => [
        'cat' => 'Therapy services',
        'short' => 'Music therapy and art therapy use music-making or art to support communication, emotional expression, wellbeing and skill development. They are led by qualified therapists.',
        'overview' => "Creative therapies work through activities that many people find natural and enjoyable. In music therapy a person might sing, play instruments, improvise or listen, while in art therapy they might draw, paint or work with clay. The therapist guides the activity with a therapeutic purpose, such as building communication, expressing feelings or developing movement and attention.\n\nYou do not need to be musical or artistic. The focus is on the process rather than the finished product, and activities are adapted to the person. These therapies can be helpful for people who find words difficult, and for those who benefit from a non-verbal way to connect and express themselves.\n\nCreative therapists have specific training and belong to professional associations. Ask about qualifications, experience with people like you and how progress is measured, so that you can tell whether the sessions are helping.",
        'choose' => [
            'Ask about qualifications and membership of a professional association.',
            'Find out whether the therapist has experience with your age group or needs.',
            'Ask how goals are set and how progress is measured.',
            'Check whether sessions are one-to-one or in a group.',
            'Ask whether family or support workers can attend.',
        ],
        'start' => [
            'Think about what you hope to get from therapy.',
            'Contact therapists and ask about their approach.',
            'Try a session and see how it feels.',
            'Review goals after a few weeks.',
        ],
        'faq' => [
            ['Do I need to be good at music or art?', 'No. The therapy is about the experience, not the result.'],
            ['Is this the same as an art class?', 'No. Therapy has therapeutic goals and is led by a qualified therapist, whereas classes teach creative skills.'],
            ['Can children take part?', 'Yes. Creative therapies are widely used with children and can be adapted to their needs.'],
        ],
    ],
];
