<?php
/**
 * Deeper guide content for service posts, batch 2 (companion to content-long-2.php).
 * Same shape as content-deep-1.php. Plain, general guidance only: no prices, no timeframes, no promises about who qualifies.
 */
if (!defined('ABSPATH')) exit;

return [
    "Counselling" => [
        "day" => "A counselling session is a conversation in a private, comfortable setting, in person, by phone or online. At the first meeting the counsellor usually explains how they work, what is confidential and what the limits of confidentiality are, and asks what has brought you there and what you hope will change. You are not expected to have everything worked out.\n\nLater sessions follow the pace you set. Some focus on a specific problem such as a difficult relationship, grief or adjusting to a diagnosis, while others explore patterns in thoughts and feelings and build practical ways of coping. Many counsellors suggest small things to try between sessions and check in about how they went.",
        "who" => "Counsellors have a range of qualifications and backgrounds, and the profession is regulated in different ways depending on the title. Psychologists are registered with AHPRA, while many counsellors belong to professional associations that set training and ethical standards. It is reasonable to ask about qualifications, experience with disability or with your particular concern, and which professional body they belong to.",
        "fit" => "Counselling can sit alongside therapy, support coordination, psychosocial supports and the help of family and friends. It is one way of looking after emotional wellbeing, not a replacement for medical care, and if you are living with a mental health condition it is worth keeping your doctor informed. Some people use counselling for a defined period, others return when life becomes harder.",
        "ask" => [
            "What is your training and which professional body are you a member of?",
            "Have you worked with people who have a disability or a situation like mine?",
            "What approach do you use, and how will we know whether it is helping?",
            "What is confidential, and when might you need to share information?",
            "Are sessions available in person, by phone and online?",
            "What happens if I need more urgent help between sessions?",
        ],
        "mistakes" => [
            "Staying with a counsellor who does not feel like a good fit rather than trying someone else.",
            "Expecting quick answers when meaningful change usually takes time and effort.",
            "Not asking about qualifications or professional membership.",
            "Keeping quiet about medication or a mental health diagnosis that the counsellor should know about.",
            "Waiting until a crisis before seeking any support.",
        ],
        "faq" => [
            ["What is the difference between a counsellor and a psychologist?", "Psychologists complete extended university training and must be registered with AHPRA, and they can assess and treat a wide range of mental health conditions. Counsellors have a range of qualifications and focus on talking therapies. Both can help, and the right one depends on what you need."],
            ["Do I have to talk about painful things in counselling?", "You set the pace. A good counsellor will not push you to share more than you are ready for, and will work with you to find a way that feels safe."],
            ["Can counselling be done online or by phone?", "Yes, many counsellors offer both. Some people find it easier to talk from home, and it can also help if travelling is difficult."],
        ],
    ],
    "Cultural, religious and civic participation" => [
        "day" => "This support helps you take part in the parts of community life that matter to you, such as attending a place of worship, joining a cultural celebration, going to a council meeting or voting. A support worker or guide helps with the practical side, which might include transport, communication, reading materials or being with you for the event.\n\nThe support is led by your own values and choices. Some people want a worker who understands their language, faith or cultural practices, while others simply want reliable help getting there and feeling included. A good worker respects the setting, follows the customs of the community and steps back when you want to take part on your own.",
        "who" => "Support is provided by workers who are chosen for their skills and, where it matters, their understanding of your culture, faith or language. Some people prefer a worker from their own community, and community organisations, cultural groups and faith communities can also be important sources of support. It is fine to ask a provider whether they can match you with someone who understands your background.",
        "fit" => "Participation in cultural, religious and civic life is a natural companion to community access, social activities and transport support. It also connects to advocacy and self-determination, since many people want a say in the decisions that affect their community. Because it is so personal, it helps to talk about what you want to do in your own words and let the plan follow.",
        "ask" => [
            "Can you match me with a worker who understands my culture, faith or language?",
            "How will you respect the customs and expectations of the place or event?",
            "Can the worker help with communication, such as interpreting or reading materials?",
            "How will you support me to take part as independently as I choose?",
            "What is your approach to privacy when the activity is personal, such as worship?",
            "How do you handle events that are held at short notice or at unusual times?",
        ],
        "mistakes" => [
            "Assuming any support worker will understand a community's customs without asking.",
            "Not telling the provider what matters most, so the support feels generic.",
            "Overlooking simple practical barriers such as transport, timing or communication.",
            "Expecting the worker to make decisions on your behalf rather than support your choices.",
            "Not making use of community and faith organisations that may already offer help.",
        ],
        "faq" => [
            ["Can support workers attend religious services with me?", "Yes, if that is what you want and the community is comfortable with it. Talk to the provider about the worker's role and about any customs they should know."],
            ["Can this support help me take part in civic activities like voting?", "Yes. A worker can help with getting to a polling place, understanding information and making sure you are able to take part as you choose."],
            ["What if I need a worker who speaks my language?", "Tell the provider at the start. Some providers have workers from a range of backgrounds, and interpreters can also help with communication where needed."],
        ],
    ],
    "Customised prosthetics and orthotics" => [
        "day" => "The process usually begins with a consultation with a prosthetist or orthotist, who talks with you about what you want to do, examines you and takes measurements or a scan. A device is then designed and made for your body. This can involve a series of fittings, adjustments and trial periods before the final version is ready.\n\nOnce you have the device, follow-up matters. Your body changes, and so does what you ask of the device, so adjustments, repairs and reviews are a normal part of the arrangement. Most people also need to learn how to use, care for and check the device, and a good practitioner gives you time to practise and ask questions.",
        "who" => "Prosthetists and orthotists are health professionals who design, make and fit devices. They often work with doctors, physiotherapists and occupational therapists, and referral or a medical opinion may be part of the process. Check their qualifications and whether they are registered or a member of the relevant professional association, and ask about their experience with your type of device.",
        "fit" => "A customised device sits alongside therapy and other health care. Physiotherapy can help you use it well, while regular check-ups help detect problems early. Because these devices are made for one person and are used every day, it is sensible to plan for repairs, replacements and changes in your needs over time.",
        "ask" => [
            "What experience do you have with the type of device I need?",
            "How many fittings and adjustments are usually involved, and where do they take place?",
            "What warranty and repair options are there, and how quickly can repairs be arranged?",
            "Who do I contact if the device causes pain or skin problems?",
            "How will you work with my doctor and therapist?",
            "How often should the device be reviewed, and what would signal that it needs replacing?",
        ],
        "mistakes" => [
            "Leaving problems such as rubbing or pain until they become serious.",
            "Not going back for adjustments during the first stage of use.",
            "Overlooking a change in weight or activity that affects fit.",
            "Skipping physiotherapy that would help you use the device effectively.",
            "Not asking about repair arrangements before committing.",
        ],
        "faq" => [
            ["How do I know if my device needs adjusting?", "Signs include pain, rubbing, skin marks, a change in how it feels or moves, or difficulty doing things you used to do easily. Contact your prosthetist or orthotist as soon as you notice these."],
            ["Do I need a referral to see a prosthetist or orthotist?", "It depends on the situation and the funding arrangements. A doctor or therapist can advise, and the practitioner can tell you what they need before starting."],
            ["Can children use prosthetic and orthotic devices?", "Yes, and because children grow, devices need to be reviewed and replaced more often. Practitioners with paediatric experience can help families plan for this."],
        ],
    ],
    "Daily living and life skills development" => [
        "day" => "A session is usually practical and takes place where the skill is used, such as in your own kitchen, at the shops or on public transport. A support worker or therapist and you agree on a goal, for example cooking a simple meal, budgeting or managing your morning routine. They break it into steps, show you or do it together, and gradually step back as you gain confidence.\n\nProgress is reviewed regularly. You might keep a simple record of what has been achieved, celebrate small wins and adjust the goal if it turns out to be too hard or too easy. The aim is not for the worker to do things for you but for you to do them yourself, or to direct how they are done.",
        "who" => "Life skills support is provided by support workers, occupational therapists and specialist trainers. An occupational therapist can assess what gets in the way and design a plan, while a support worker can carry it out day to day. Choose someone who is patient, works at your pace and treats you as an adult who is learning, not a child who is being taught.",
        "fit" => "Daily living skills connect with almost everything else in a plan, including housing, transport, community access and employment. Building these skills often reduces how much support you need in the long run, and it can open doors to more independent living. Because goals change, it is worth revisiting the plan whenever you feel ready for something new.",
        "ask" => [
            "How will we decide which skills to work on first?",
            "How will you teach the skill, and will it be practised in my own home and community?",
            "How will we know whether I am making progress?",
            "What will you do if something turns out to be too difficult?",
            "How will you involve my family or others who support me?",
            "How will you help me to keep using the skill when you are not there?",
        ],
        "mistakes" => [
            "Choosing goals that are too big and leave you discouraged.",
            "Having a worker do tasks for you instead of teaching you to do them.",
            "Practising skills in a setting that is different from where you will use them.",
            "Not recording progress, which makes it hard to see improvement.",
            "Forgetting to celebrate small achievements along the way.",
        ],
        "faq" => [
            ["What kinds of skills can I work on?", "Common examples are cooking, cleaning, managing money, using public transport, shopping, personal care routines and organising your time. The list is driven by what matters to you."],
            ["Do I need an occupational therapist for life skills support?", "Not always, but a therapist can help when you are unsure what is getting in the way or when the skills are complex. Many people work with a support worker guided by a therapist."],
            ["How long will I need this support?", "It depends on your goals and how quickly you learn. The idea is to build independence, so support usually reduces over time as you gain skills."],
        ],
    ],
    "Dietitian" => [
        "day" => "A first appointment usually includes a detailed conversation about what you eat and drink, your health, your routine, your preferences and your goals. The dietitian may ask about swallowing, appetite, allergies, cultural food practices, medications and how meals are prepared. They may also look at test results or information from your doctor.\n\nFrom this they suggest practical changes, such as new ways of preparing food, adjustments to portion sizes, strategies for eating enough or managing a condition. Follow-up appointments check how things are going, adapt the plan and provide encouragement. Good advice fits your life, not a rigid ideal.",
        "who" => "Accredited practising dietitians have university training in nutrition and dietetics and are members of a professional body that sets standards. Some specialise in areas such as diabetes, kidney disease, paediatrics, disability or eating disorders. If you have complex needs, ask about experience with your particular situation, and check that the person is a qualified dietitian, since the word nutritionist is not always regulated in the same way.",
        "fit" => "Dietitians often work with doctors, speech pathologists, occupational therapists and support workers. If you have difficulty swallowing, a speech pathologist and dietitian may work together, and if a support worker prepares your meals, sharing the dietitian's advice helps make sure it is followed. Nutrition connects with energy, mood, medications and long-term health.",
        "ask" => [
            "Are you an accredited practising dietitian?",
            "Do you have experience with my condition or with people who have a disability?",
            "How will you take account of my likes, dislikes, culture and budget?",
            "Can you give advice that my support workers or family can follow?",
            "How often will we review my progress?",
            "Will you liaise with my doctor and other health professionals?",
        ],
        "mistakes" => [
            "Following general diet advice from the internet instead of tailored guidance.",
            "Cutting out foods without professional advice, which can create new problems.",
            "Not telling the dietitian about swallowing difficulties or medications.",
            "Expecting a single appointment to solve everything, without follow-up.",
            "Not sharing the plan with the people who prepare your meals.",
        ],
        "faq" => [
            ["What is the difference between a dietitian and a nutritionist?", "Accredited practising dietitians have specific qualifications and are recognised by a professional body, and they can give medical nutrition advice. The title nutritionist can be used more broadly, so it is worth checking qualifications."],
            ["Can a dietitian work out the right tube feed for me?", "Yes. Dietitians work out the type and amount of feed someone needs and monitor how it is going, often in partnership with doctors and nurses."],
            ["Can a dietitian help children with fussy eating?", "Yes. Dietitians who work with children can suggest strategies for families and coordinate with other professionals if there are sensory or developmental factors."],
        ],
    ],
    "Early Childhood Intervention" => [
        "day" => "Early childhood intervention is built around the child and family. Sessions are often play-based and may take place at home, in a childcare setting, at a clinic or in a group. A therapist or early childhood educator works with the child on skills such as communication, movement, play and self-care, and shows parents and carers what to do between sessions.\n\nFamilies are treated as partners. A good practitioner listens to what you notice about your child, explains what they see, and sets goals that fit your family routines. Progress is shared in plain language, and the team keeps in touch with childcare, preschool or school so that everyone is working in the same direction.",
        "who" => "Early childhood teams may include speech pathologists, occupational therapists, physiotherapists, psychologists, early childhood educators and special educators. Some services offer a key worker who is the main contact and coordinates the rest. Look for practitioners who work with young children and understand family-centred practice, where parents are involved as the experts on their child.",
        "fit" => "Early support is often most effective when it fits into everyday life, including home routines, childcare and preschool. It works alongside health care, family supports and later transition to school. Because young children develop quickly, it helps to review goals often and to prepare early for changes such as starting school.",
        "ask" => [
            "How will you involve our family and make use of our daily routines?",
            "Who will be our main contact, and how will the team communicate with us?",
            "What are the goals likely to be, and how will you tell us how our child is progressing?",
            "How do you work with childcare, preschool or school?",
            "Can therapy be provided at home or in our child's usual settings?",
            "How will you help us prepare for starting school?",
        ],
        "mistakes" => [
            "Waiting for a firm diagnosis before seeking support, when help with skills can start earlier.",
            "Leaving practice to therapy sessions only, instead of building it into daily routines.",
            "Not sharing information between therapists, educators and family.",
            "Feeling that you must accept advice that does not fit your family or values.",
            "Leaving the transition to school until the last minute.",
        ],
        "faq" => [
            ["Do we need a diagnosis to start early childhood support?", "Not always. Support can often start when there are developmental concerns, and the team can help work out what is going on. Talk to your doctor or child health nurse about next steps."],
            ["What is a key worker?", "A key worker is one member of the team who acts as the family's main contact, coordinates the other professionals and helps make sure everyone works toward shared goals."],
            ["How can I help my child between sessions?", "Your therapist can show you simple activities to build into everyday moments such as meals, bath time and play. Small, regular practice is often more useful than long sessions."],
        ],
    ],
    "Employment assessment and counselling" => [
        "day" => "An assessment usually starts with a conversation about your interests, experience, skills, health and the kind of work you would like. It may include questionnaires, practical exercises, and a look at any barriers such as transport, confidence or workplace adjustments. The result is a picture of the work that suits you and what might help you get and keep it.\n\nCounselling follows, and it focuses on putting that into action. You might explore training, prepare a resume, practise interviews or plan how to talk to an employer about your needs. A counsellor helps you set realistic steps, keeps track of progress and adjusts the plan if things change.",
        "who" => "Employment assessment and counselling are provided by career counsellors, vocational rehabilitation professionals, occupational therapists and specialist employment services. It helps to choose someone with experience of disability and the local job market, and who focuses on what you want rather than only what is available.",
        "fit" => "This support usually comes before or alongside job coaching, training and supported employment. The assessment provides a plan that other supports can follow, and it is useful for conversations with employers and training providers. It also connects with other parts of your life, such as transport, health and housing, which affect how easily you can work.",
        "ask" => [
            "How will you find out what work suits me, and not only what jobs are available?",
            "What experience do you have with people who have a disability like mine?",
            "How will you support me to talk to employers about workplace adjustments?",
            "What happens after the assessment, and who helps me act on it?",
            "How will you work with other supports, such as my therapist or training provider?",
            "How will we know whether the plan is working?",
        ],
        "mistakes" => [
            "Applying for any job available instead of one that fits your interests and strengths.",
            "Leaving out barriers such as health or transport, which then cause problems later.",
            "Not asking about workplace adjustments before the job starts.",
            "Treating the assessment as the end of the process rather than the start.",
            "Not involving your family or supporters where you would like their help.",
        ],
        "faq" => [
            ["What is a vocational assessment?", "It is a structured look at your interests, skills, experience and needs so you and your counsellor can work out what kind of work suits you and what support you might need to get and keep it."],
            ["Must I disclose my disability when I apply for jobs?", "It is your choice, and there are pros and cons. A counsellor can talk through your options and help you decide what to share and how."],
            ["Can I get help with a resume and interviews?", "Yes. Many employment counsellors help with preparing resumes, practising interviews and thinking about how to present your strengths."],
        ],
    ],
    "Exercise physiology" => [
        "day" => "An exercise physiologist begins by learning about your health, history and goals, and may assess strength, fitness, movement and any limits on what you can do. From this they design a program of exercises that suits your body and your aims, whether that is managing a condition, building strength, improving balance or increasing everyday energy.\n\nSessions can take place in a clinic, gym, pool or at home. The physiologist demonstrates each exercise, watches your technique, adjusts the load and explains how to do the program on your own between appointments. They review your progress regularly and change the program as you improve or as your needs change.",
        "who" => "Accredited exercise physiologists have university degrees in exercise science and clinical training, and are accredited by Exercise and Sports Science Australia. They differ from personal trainers in that they are trained to work with people who have medical conditions or disability. Ask about experience with your condition and whether they work with your doctor or physiotherapist.",
        "fit" => "Exercise physiology complements physiotherapy, medical care and personal training. A physiotherapist may treat an injury or movement problem, and an exercise physiologist can then help build long-term fitness and function. A doctor's advice about what is safe is also important, particularly if you have a heart, lung or metabolic condition.",
        "ask" => [
            "Are you an accredited exercise physiologist?",
            "Do you have experience with my condition or with people who have a disability?",
            "What will my program focus on, and how will you measure progress?",
            "Where will sessions take place, and is the equipment accessible?",
            "How will you keep me safe and adjust the program if I feel unwell?",
            "Will you share information with my doctor and physiotherapist?",
        ],
        "mistakes" => [
            "Starting an exercise program without checking that it is safe for your health.",
            "Doing too much too soon, then stopping because of pain or exhaustion.",
            "Not following the program between sessions.",
            "Choosing a trainer without experience in your condition.",
            "Ignoring signs such as dizziness or chest pain, instead of reporting them.",
        ],
        "faq" => [
            ["What is the difference between an exercise physiologist and a personal trainer?", "Exercise physiologists are trained health professionals who work with medical conditions and disability. Personal trainers focus on general fitness and may not have the clinical training to work with complex health needs."],
            ["Can exercise physiology help with chronic conditions?", "Yes. It is used for many conditions, including diabetes, heart disease, arthritis and neurological conditions, to improve strength, fitness and everyday function."],
            ["Do I need my doctor's approval before starting?", "Often it is a good idea, especially if you have a health condition. An exercise physiologist can tell you what information they need from your doctor."],
        ],
    ],
    "Financial and organisational skills" => [
        "day" => "Sessions are hands-on and focused on the things you actually deal with, such as paying bills, keeping track of appointments, sorting mail, budgeting or using a phone or app to stay organised. A worker or therapist sits with you, shows you a method, and you practise together until it starts to feel natural.\n\nThe approach is to build systems that work for you. That might be a simple weekly planner, a folder for important papers, reminders on your phone or a way of checking your bank balance. Over time you take more of the tasks on yourself, and the worker is there for questions and to help you adjust.",
        "who" => "This support is provided by support workers, occupational therapists and specialist trainers. Some people also involve a financial counsellor or plan manager for particular questions. A good worker is patient, respects your privacy and teaches you rather than taking over, and it is important to feel comfortable sharing information about your finances.",
        "fit" => "Financial and organisational skills connect with independent living, employment, and managing a plan. Building them can help you feel more in control of your life and can reduce the risk of missed payments or forgotten appointments. Working on them alongside daily living skills, and with a plan manager if you have one, gives you a fuller picture of how your money and time are managed.",
        "ask" => [
            "How will you help me build a system that suits how I think and work?",
            "How will you keep my financial information private and secure?",
            "Will you teach me to do things myself, or do them for me?",
            "How will we measure whether I am becoming more confident?",
            "What will you do if I make a mistake or miss a payment?",
            "How will you work with my plan manager, family or financial counsellor?",
        ],
        "mistakes" => [
            "Handing over control of your money or documents without clear agreement.",
            "Trying to build a system that is too complicated to keep up.",
            "Not keeping important papers in one safe, easy place.",
            "Hiding financial worries rather than asking for help early.",
            "Not checking that a worker respects privacy and boundaries.",
        ],
        "faq" => [
            ["Will the support worker have access to my bank account?", "That should only happen if you choose it, and any access should be clearly agreed and limited. The aim is usually to help you manage your own money, not to take control of it."],
            ["What if I have debts or money problems?", "A financial counsellor can help with debts and bills, and the service is free and confidential in many places. A support worker can help you get in touch."],
            ["Can this support help with keeping track of appointments?", "Yes. Many people work on calendars, reminders and routines that help them remember and prepare for appointments."],
        ],
    ],
    "Group / shared living support" => [
        "day" => "In a shared home, support is organised around the household as well as each person. Workers help with everyday tasks such as meals, personal care, cleaning and getting to appointments, and they support people to get along, make shared decisions and keep the home running smoothly.\n\nEach person keeps their own goals, routines and choices. A good service makes time for individual attention while also encouraging friendships, household meetings and a sense of being at home. Staff change over shifts, so handovers, written notes and consistent practices are important.",
        "who" => "Support in shared living is provided by teams of support workers, coordinated by a manager or team leader. Some homes involve nurses or allied health professionals for particular needs. Because you live with the people who support you, it is important to ask about staff training, how many workers are present, and how the provider handles changes in staffing.",
        "fit" => "Shared living can be part of a wider housing arrangement and may involve a tenancy agreement as well as a support agreement. Think about who you would live with, where the home is and how it fits with your work, study, family and community. It is good to know how you can change your arrangements later if things do not work out.",
        "ask" => [
            "Who will I be living with, and how are housemates matched?",
            "How many staff are there at different times, and how consistent is the team?",
            "How can I have a say in the house rules, meals and daily routines?",
            "What happens if I have a disagreement with a housemate or staff member?",
            "Can I have visitors, and what privacy will I have?",
            "What are my options if I want to move on?",
        ],
        "mistakes" => [
            "Agreeing to a home without meeting the housemates or seeing the house.",
            "Not asking about staffing levels and how often staff change.",
            "Mixing up the support agreement and the tenancy agreement.",
            "Not finding out how decisions are made in the house.",
            "Overlooking how easy it will be to leave if the arrangement does not suit you.",
        ],
        "faq" => [
            ["How much say do I have in who shares my home?", "You should have a say, and a good provider takes compatibility seriously. Ask about how housemates are matched and whether you can meet them before deciding."],
            ["What is the difference between shared living and supported independent living?", "The terms are often used for similar arrangements in which support is provided in a shared home. Ask the provider exactly what is included, how staffing works and how the arrangements are documented."],
            ["Can I have my own room and keep my own belongings?", "That is normally expected, and it is important to confirm it in the agreement. Ask what furniture, storage and privacy you will have."],
        ],
    ],
    "Group and centre-based activities" => [
        "day" => "A group or centre-based program usually runs on a schedule, with a mix of activities such as arts, cooking, exercise, games, outings and skills sessions. Participants arrive at set times, take part in the activities that interest them and are supported by staff and volunteers who help with anything from personal care to communication.\n\nA good program is more than a place to spend the day. It offers choice, respects individual goals and helps people meet friends and try new things. Staff adjust activities to suit the group and to make sure people who need more support are included.",
        "who" => "Group and centre programs are run by disability service providers and community organisations. Staff are usually support workers and activity coordinators, sometimes with therapists and nurses involved. Ask about staff ratios, training and how the program supports people with different needs at the same time.",
        "fit" => "Group activities complement one-to-one community access, transport and skill-building. Some people like a mix, using the group for social contact and individual support for community outings. It is important that the program has a purpose that connects with your goals, such as building friendships or trying new skills, and not just filling time.",
        "ask" => [
            "What activities are on offer, and can I help choose them?",
            "How many participants and staff are there, and what is the mix of needs?",
            "How do you support people who need help with personal care or communication?",
            "How do you make sure the program connects with my goals?",
            "How does transport work for getting to and from the centre?",
            "What is your approach to safety, including emergencies and medication?",
        ],
        "mistakes" => [
            "Choosing a program on convenience alone without visiting or trying it first.",
            "Not checking whether the mix of participants suits you.",
            "Expecting the program to meet individual goals without discussing them.",
            "Overlooking transport, which can make or break attendance.",
            "Not reviewing whether the program is still right after a while.",
        ],
        "faq" => [
            ["Can I visit a centre before I decide?", "Yes, and it is a good idea. Many providers offer a visit or trial session so you can see the activities and meet staff and other participants."],
            ["Can I take part in some activities but not others?", "Usually yes. Programs are meant to offer choice, so ask how you can tailor your participation."],
            ["Is centre-based support the same as day programs?", "The terms are often used interchangeably, but programs differ in what they offer. Ask what a typical day looks like at the service you are considering."],
        ],
    ],
];
