<?php
/**
 * Deeper guide content for service posts, batch 1 (companion to content-long-1.php).
 * Shape: 'Title' => [
 *   'day'      => what a typical session or arrangement looks like (2 paragraphs separated by a blank line),
 *   'who'      => who usually delivers this support (1 paragraph),
 *   'fit'      => how it fits with the rest of a plan (1 paragraph),
 *   'ask'      => [ 6 questions worth asking a provider ],
 *   'mistakes' => [ 5 common mistakes or things people overlook ],
 *   'faq'      => [ [question, answer] x3 ]  (added to the FAQs in content-services-*.php and content-long-*.php),
 * ].
 * Plain, general guidance only: no prices, no timeframes, no promises about who qualifies.
 */
if (!defined('ABSPATH')) exit;

return [
    "AT repairs, maintenance, rental and trial" => [
        "day" => "A repair or servicing visit usually starts with the technician asking what has gone wrong or what you have noticed, then looking over the equipment, testing it and explaining what needs to be done. Some repairs can be done on the spot. Others need parts, or the item has to go to a workshop, and this is the point where a loan item makes a real difference to your week.\n\nA trial or rental usually begins with a conversation about what you want the equipment to do, followed by setting it up for you and showing you how it works. You then use it in your ordinary routine, and there is normally a check-in partway through and a conversation at the end about whether to keep it, return it, or try something different.",
        "who" => "Repairs and servicing are usually done by technicians employed by the supplier or manufacturer, or by independent repairers who specialise in a type of equipment such as wheelchairs, hoists or communication devices. Trials and rentals are arranged by suppliers, often together with an occupational therapist or another allied health professional who knows how the equipment needs to be set up for your body and your home. Ask who will be doing the work and whether they are experienced with your particular make and model.",
        "fit" => "Repairs, maintenance, rental and trial sit alongside the purchase of equipment itself and any training in how to use it. A trial often comes before a purchase, so the result of the trial can be used to support a request for the right item. If you rely on equipment every day, it is sensible to think about maintenance as part of the plan from the start, rather than something that only gets attention when a breakdown happens.",
        "ask" => [
            "Can you tell me in writing what is included in servicing and what would be charged separately?",
            "Is a loan item available if my equipment has to be taken away for repair, and how is it set up for me?",
            "Who do I contact after hours if something fails and I cannot manage without it?",
            "How do you decide whether a repair is worthwhile compared with replacing the item?",
            "For a trial, what information will you give my therapist afterwards so the decision is based on what actually happened?",
            "If the equipment is damaged during a rental, what is my responsibility and what is yours?",
        ],
        "mistakes" => [
            "Waiting until equipment fails completely before arranging a service, which can leave you without it for longer.",
            "Trialling equipment for too short a time, or only in one place, and missing problems that show up in real use.",
            "Not keeping the paperwork from repairs and servicing, which makes it harder to show what was done and when.",
            "Assuming a rental includes maintenance without checking the agreement.",
            "Skipping a conversation with your therapist and ending up with equipment that is technically fine but does not suit how you move or live.",
        ],
        "faq" => [
            ["Who is responsible for repairing equipment that was bought for me?", "It depends on the arrangements made when it was supplied and on any warranty that applies. Check the paperwork from the supplier, and ask about maintenance and repair terms before you agree to a purchase or rental."],
            ["Can a trial be arranged for equipment I already own but am not sure about?", "Sometimes a supplier or therapist can review how you are using it and suggest changes or an alternative to try. It is worth asking, especially if the equipment is causing pain or not doing what you need."],
            ["What records should I keep for repairs and rentals?", "Keep quotes, invoices, service reports and any agreement about a loan item or rental. They make it much easier to explain what happened, to claim a warranty, or to show a therapist the history of the equipment."],
        ],
    ],
    "Activity-based transport" => [
        "day" => "A trip usually begins with the driver or support worker arriving at the agreed time and place, helping you get in and settled, and making sure you have what you need for the activity. They take you to the venue, and depending on the arrangement they may wait, help you get inside, or come back at a set time to bring you home.\n\nThe support is often as much about confidence as about the vehicle. A worker who travels with you on public transport might practise the route with you until you are comfortable, then gradually step back. For others, the value is having someone dependable who understands their needs, so that getting to a class or event is no longer a source of worry.",
        "who" => "Activity-based transport is typically provided by support workers or drivers working for a provider, or by independent workers. Depending on the person's needs, the driver may need additional training, for example in assisting with wheelchairs, in supporting someone who becomes anxious while travelling, or in helping with communication. The vehicle also matters, and it should be suitable for the person's mobility needs and properly maintained and insured.",
        "fit" => "This support usually works alongside the activities it enables, such as community access, social and recreation programs, group activities or skill-building classes. It can help to think of the two together: an activity that is out of reach without transport is not really accessible yet. It also sits next to other transport arrangements, so it is worth being clear with your provider about which trips the support is meant to cover.",
        "ask" => [
            "Which trips does this cover, and which would need to be arranged separately?",
            "Is the vehicle suitable for my mobility equipment, and how is it kept safe and roadworthy?",
            "Will the same driver or worker usually come, and what happens if they are unavailable?",
            "How do you handle delays, cancellations and changes to the activity?",
            "What screening and training do your drivers and workers have?",
            "Can the worker stay with me during the activity if I need it, or do they only do the travel?",
        ],
        "mistakes" => [
            "Agreeing to transport without being clear about whether waiting time and the return trip are part of the arrangement.",
            "Not checking that the vehicle can safely carry your equipment before the first trip.",
            "Assuming a worker will stay for the activity when the arrangement only covers the drive.",
            "Leaving cancellation and change terms unclear until something goes wrong.",
            "Relying on a single driver with no back-up plan for when they are unwell or unavailable.",
        ],
        "faq" => [
            ["Can transport support help me learn to use public transport?", "Yes, this is a common use. A worker can travel with you, practise the route, and gradually reduce their involvement as your confidence grows. It helps to agree at the start what you are aiming for."],
            ["Is the support worker allowed to drive my own car?", "Arrangements differ between providers and depend on insurance and policy. Ask the provider directly, and make sure you understand who is covered if something happens."],
            ["What if the activity is cancelled after the driver has arrived?", "The provider's agreement should say how cancellations and changes are handled. Asking for this in writing before you start avoids misunderstandings later."],
        ],
    ],
    "Assistance animal training and assessment" => [
        "day" => "Assessment usually involves a trained professional looking at what you need an animal to do, how you live, and whether an assistance animal is a suitable and safe option. This often includes conversations with you and the people around you, observation at home or in the community, and a written report that explains the findings.\n\nTraining is a longer process. It may involve the animal being trained by a specialist organisation before it comes to live with you, followed by sessions in which you and the animal learn to work as a team. Training continues in your own environment, because a skill learned in a training centre often needs adjusting to the places where you will actually use it.",
        "who" => "Assessment and training are usually carried out by specialist organisations and trainers with experience in assistance animals, sometimes working with an occupational therapist or another health professional. Because there are different types of assistance animals and different standards, it is worth asking about the trainer's experience, the methods they use and how they assess whether an animal is suitable and healthy for the work.",
        "fit" => "An assistance animal is a long-term commitment, so assessment and training sit alongside decisions about ongoing care, veterinary needs and how the animal will be looked after when it is not working. Many people also continue to use other supports, such as personal care or therapy, and the animal is one part of a wider picture rather than a replacement for those supports.",
        "ask" => [
            "What is your process for deciding whether an assistance animal is right for me?",
            "How is the animal selected and trained, and what standards do you follow?",
            "Will training take place in my own home and community, and how much of it involves me?",
            "What support do I get after the animal comes to live with me?",
            "How do you assess the animal's health and temperament, and what happens if it turns out to be unsuitable?",
            "What are the public access rules I should know about, and how do you help me meet them?",
        ],
        "mistakes" => [
            "Choosing an animal or trainer without a proper assessment of whether it will suit your daily life.",
            "Underestimating the ongoing effort involved in caring for an animal, on top of its working role.",
            "Not asking what happens if the match does not work out.",
            "Assuming any trained animal automatically has public access rights everywhere.",
            "Expecting training to be finished once the animal arrives, when follow-up in your own environment is often what makes it work.",
        ],
        "faq" => [
            ["What is the difference between an assistance animal and a pet?", "An assistance animal is trained to do specific tasks that help with a person's disability, and it is expected to behave reliably in public. A pet provides companionship but does not have this training or these responsibilities."],
            ["Do I need an assessment before getting an assistance animal?", "An assessment is a sensible first step because it looks at whether an animal would really help and whether it is practical for you. Some organisations require one, and some funding decisions rely on it."],
            ["Can I train an assistance animal myself?", "Some people do, but it requires a lot of time, skill and consistency, and there are standards the animal generally needs to meet. Speak to a specialist organisation about what is involved before deciding."],
        ],
    ],
    "Assistance animal upkeep" => [
        "day" => "Upkeep is the everyday and occasional care that keeps an assistance animal healthy and able to work. Day to day, that means feeding, grooming, exercise, toileting and keeping up the routines the animal was trained with. Less often it means veterinary check-ups, vaccinations, parasite control and any treatment the animal needs.\n\nBecause the animal is working, its wellbeing directly affects how well it can support you. An animal that is unwell, tired or in pain may struggle to do its tasks, so regular checks and a consistent routine are a practical part of the arrangement, not an extra.",
        "who" => "The main carer for an assistance animal is normally the person it supports, sometimes with help from family, a support worker or the organisation that trained the animal. Veterinarians provide the health care, and the training organisation or a specialist trainer can advise on working behaviour, refresher training and any changes needed as the animal ages.",
        "fit" => "Upkeep needs to be planned along with the rest of your supports. It is a recurring part of having an assistance animal and it changes over time, especially as the animal grows older and eventually retires. Thinking about this early helps you keep the animal healthy and avoid being caught out by a sudden need.",
        "ask" => [
            "What routine care does my animal need, and what should I watch for?",
            "How often should the animal see a vet, and what should be checked?",
            "When should I contact the training organisation for a refresher or advice?",
            "What plan is there for the animal's retirement or replacement when the time comes?",
            "Who can help me look after the animal if I am unwell or in hospital?",
            "How should I keep records of the animal's health and care?",
        ],
        "mistakes" => [
            "Delaying veterinary checks because the animal seems fine, when small problems can affect its ability to work.",
            "Letting routines and training slip so that the animal's behaviour gradually changes.",
            "Not having a plan for who cares for the animal if you cannot.",
            "Forgetting to keep records, which can be needed for access, insurance or funding purposes.",
            "Leaving retirement planning until it is urgent.",
        ],
        "faq" => [
            ["Who should I talk to if my assistance animal's behaviour changes?", "Start with your vet to rule out pain or illness, then contact the organisation or trainer that worked with you. Behaviour changes are often an early sign that something needs attention."],
            ["What happens when an assistance animal gets too old to work?", "Many animals retire and continue to live with their handler or another family, and a replacement may be considered. It helps to discuss this with the training organisation well ahead of time."],
            ["Can someone else look after my animal if I go into hospital?", "Often yes, but it needs to be arranged in advance. Choose someone the animal knows, and give them clear instructions about routines and health needs."],
        ],
    ],
    "Assistance animals" => [
        "day" => "Living with an assistance animal becomes part of your daily routine. The animal may help with tasks such as guiding, retrieving items, alerting to sounds or medical events, providing physical support or helping with anxiety. Out in the community, it works alongside you at the shops, on public transport and at appointments, and it needs a calm, well-established routine to do that reliably.\n\nAt home the animal is also a living companion that needs rest, play, exercise and care. Many people find the best results come when the whole household understands the animal's role, follows consistent commands and lets it do its job without distraction.",
        "who" => "Assistance animals are generally trained by specialist organisations or trainers, and different organisations focus on different types of work, such as guide dogs, hearing dogs or animals for psychosocial or physical support. Once the animal is with you, its ongoing care involves you, your vet, and often the training organisation, which may provide follow-up support.",
        "fit" => "An assistance animal is one part of a plan that may also include therapy, personal care, community access and equipment. It does not replace human support, but for some people it changes how independently they can live and how confident they feel in public. Thinking about how the animal fits with your other supports helps you use it well.",
        "ask" => [
            "What tasks would the animal be trained to do for me, specifically?",
            "How long does the matching and training process usually involve me, and what is expected of me?",
            "What ongoing support will I have from your organisation after the animal is placed?",
            "How will my household and the people around me be prepared to live with the animal?",
            "What are my responsibilities under the law and the access rules that apply to me?",
            "What happens if the placement is not working for me or for the animal?",
        ],
        "mistakes" => [
            "Choosing an animal for the wrong reasons, such as companionship alone, when the aim is a working relationship.",
            "Not involving family or housemates in the decision and the training.",
            "Overlooking the cost in time and energy of caring for an animal every day.",
            "Assuming the animal will work equally well in every setting without practice.",
            "Not checking that the organisation follows recognised standards.",
        ],
        "faq" => [
            ["What types of assistance animals are there?", "The best-known are guide dogs for people who are blind or have low vision, hearing dogs for people who are deaf or hard of hearing, and dogs trained to help with mobility, medical alerts or psychosocial disability. Each type has its own training."],
            ["Are assistance animals allowed in public places?", "There are rules about public access, and they depend on the animal meeting certain standards. Ask the training organisation how they help you meet these requirements and what documentation you may need."],
            ["Can an assistance animal help with mental health conditions?", "Some animals are trained to support people living with psychosocial disability, for example by interrupting distress or providing grounding. It is best discussed with a professional who can assess whether it suits your situation."],
        ],
    ],
    "Assistive technology assessment and training" => [
        "day" => "An assessment usually starts with a conversation about what you want to do and what gets in the way. The assessor then looks at your abilities, your home or workplace, and the technology already available, and may arrange for you to try a few options. Afterwards you receive a written recommendation that explains what suits you and why.\n\nTraining follows once you have the equipment. A trainer shows you how to set it up, use it safely and get the best from its features, often in the places where you will use it. Good training is practical and paced to you, with time to practise and a way to ask questions when something does not work.",
        "who" => "Assessments are often carried out by occupational therapists, speech pathologists, physiotherapists or other allied health professionals, depending on the type of technology. Training may be done by the assessor, the supplier or a specialist trainer. The right person depends on what you need, and someone experienced with your kind of equipment is more useful than someone with general knowledge.",
        "fit" => "An assessment often comes first and guides the choice and purchase of equipment, while training helps you use it effectively. The results are also useful evidence if a request for funding needs to explain why a particular item is the right choice. Reviews later on help you adjust as your needs, your home or the technology itself change.",
        "ask" => [
            "How will you find out what I actually want to be able to do?",
            "Will you compare more than one option, and can I try them before deciding?",
            "Can you explain the reasons for your recommendation in a written report?",
            "Where will training take place, and how many sessions are usually needed?",
            "What help is there if I have trouble with the equipment after training ends?",
            "How will we check that the equipment is still working for me later on?",
        ],
        "mistakes" => [
            "Buying equipment before an assessment and finding it does not suit your needs.",
            "Skipping training because the equipment seems easy, then not using its full capability.",
            "Not involving the people who will help you use it every day.",
            "Assuming one assessment is enough for good, when needs change over time.",
            "Focusing only on the device and not on how it fits with your home, routine and other supports.",
        ],
        "faq" => [
            ["Why do I need an assessment if I already know what equipment I want?", "An assessment checks that the equipment is safe, suitable and likely to work for you, and it provides the reasoning that supports a funding request. It can also uncover options you had not considered."],
            ["Who should attend the training?", "Ideally you and anyone who will help you use or maintain the equipment, such as family, carers or support workers. That way everyone learns the same way of doing things."],
            ["Can assessment and training be done at home?", "Often yes, and it is usually better because the therapist can see the actual space and routines. Ask whether home visits are possible when you book."],
        ],
    ],
    "Behaviour support implementation" => [
        "day" => "Behaviour support implementation is the day-to-day work of putting a behaviour support plan into practice. A support worker follows the strategies in the plan, such as changing the environment, using specific ways of communicating, teaching new skills and responding to challenging situations in a consistent way.\n\nThe work is about consistency and observation. Workers record what happens, share information with the behaviour support practitioner and the person's family or team, and flag anything that suggests the plan needs changing. Progress is often gradual, and a good implementer stays calm, respectful and focused on the person's goals and dignity.",
        "who" => "Implementation is carried out by support workers, therapy assistants and family members, guided by a behaviour support practitioner who wrote the plan. Workers need to understand the plan properly, be trained in the strategies and know when and how to raise concerns. Workers who have not been trained in a person's plan should not be left to manage difficult situations alone.",
        "fit" => "This support depends on a behaviour support plan and works alongside other supports such as therapy, community access and daily living support. It is more effective when everyone who works with the person uses the same approach, so it helps to share the plan across all providers and to review it regularly with the practitioner.",
        "ask" => [
            "Have all staff who will work with me been trained in my behaviour support plan?",
            "How do you record and share information about what is working and what is not?",
            "What happens if a worker is unsure how to respond in a difficult moment?",
            "How will you make sure my rights, choices and dignity are respected?",
            "How often will the plan be reviewed with the practitioner, and who takes part?",
            "What is your policy on restrictive practices, and how do you report on them?",
        ],
        "mistakes" => [
            "Using different approaches in different settings, which can confuse the person and slow progress.",
            "Treating the plan as a document to file rather than a guide to daily practice.",
            "Not involving the person and their family in reviewing how the plan is going.",
            "Leaving untrained workers to cover shifts where the plan is needed.",
            "Assuming a restrictive practice is acceptable without checking that it is authorised and reported.",
        ],
        "faq" => [
            ["What is the difference between writing a behaviour support plan and implementing it?", "A practitioner writes the plan after assessing the person and their situation. Implementation is what happens every day when workers and family put the strategies into practice, record what happens and share feedback."],
            ["Who should know about a person's behaviour support plan?", "Everyone who supports the person on a regular basis, including family, support workers and other providers, so that the approach stays consistent. The person themselves should be involved wherever possible."],
            ["What if the plan does not seem to be working?", "Tell the practitioner. Plans are meant to change as the person's needs and circumstances change, and the information collected during implementation is what guides those changes."],
        ],
    ],
    "Communication and information equipment" => [
        "day" => "Communication equipment can range from simple picture boards to tablets with specialised software, eye-gaze systems and devices that give a voice to people who cannot speak. A typical process begins with an assessment, often by a speech pathologist, then a trial of different options and finally setup and training so that the person and the people around them can use it easily.\n\nInformation equipment helps people access things like phones, computers and the internet, and can include screen readers, adapted keyboards, switches or speech recognition. Once the equipment is chosen, the biggest factor in success is regular use, so families, teachers and support workers all benefit from learning how it works and how to encourage its use.",
        "who" => "Speech pathologists and occupational therapists often lead the assessment and trial for communication equipment, sometimes working with an assistive technology specialist. Suppliers and specialist trainers help with setup and instruction. For information technology, a therapist or technology specialist can match a person's abilities with the right adaptations.",
        "fit" => "Communication and information equipment is part of a wider effort to help someone take part in their life, and it works best alongside therapy, training and the support of people around them. Its value comes from being used every day at home, at school or work and in the community, so the plan needs to include the training and follow-up that make that possible.",
        "ask" => [
            "How will you assess what communication method or device is right for me or my family member?",
            "Can we try several options in real situations before deciding?",
            "What training is included for the user and for the people around them?",
            "How is the device programmed and personalised, and who does the updates?",
            "What support is available if the device fails or the software needs to change?",
            "How will we check over time that it is still meeting the person's needs?",
        ],
        "mistakes" => [
            "Choosing a device on the strength of a demonstration alone rather than a trial in daily life.",
            "Neglecting training for family, teachers and support workers, who are needed to make it work.",
            "Not planning for repairs, updates and back-up options if the device fails.",
            "Expecting a device to work straight away when learning to communicate this way takes practice.",
            "Failing to review the setup as the person's needs and skills develop.",
        ],
        "faq" => [
            ["What is augmentative and alternative communication?", "It is a range of methods, from gestures and picture boards to speech-generating devices, that support or replace speech for people who find it hard to communicate verbally. A speech pathologist can help decide which approach fits."],
            ["How long does it take to learn to use a communication device?", "It varies a great deal from person to person, and it depends on the device, the person's skills and how often it is used. Regular practice and support from the people around them make a big difference."],
            ["Can a communication device be used at school and at work?", "Yes, and it is important that it can be. Talk to the school or employer early so they understand how the device works and what support the person needs to use it there."],
        ],
    ],
    "Community nursing care" => [
        "day" => "A community nursing visit normally happens at home or in another community setting. The nurse arrives at the arranged time, checks in with you about how you are feeling, and carries out the care in your plan, such as wound care, medication support, managing a health condition, or monitoring changes in your health.\n\nThe nurse also watches for early signs of problems, explains what they are doing and why, and keeps records that can be shared with your doctor and other health professionals. Many people value having someone with clinical skills who can answer questions and help them feel more confident managing their health at home.",
        "who" => "Community nursing is provided by registered nurses and, for some tasks, enrolled nurses working under the supervision of a registered nurse. Nurses must be registered with the relevant national board, and it is reasonable to ask about their experience with your particular condition. Some tasks in a health plan are delegated to trained support workers, and the nurse should explain how that is supervised.",
        "fit" => "Community nursing works alongside your general practitioner, specialists, therapists and support workers. It often complements personal care, medication assistance and daily living support, so it helps if the nurse, the doctor and other supporters share information about your health. Your plan should make clear which health needs the nurse looks after and which are managed by others.",
        "ask" => [
            "Can you check my nurse's registration, and do they have experience with my condition?",
            "How will visits be arranged, and what happens if my needs change or I become unwell?",
            "Who will you share information with, and how do you keep my records safe?",
            "How do you work with my doctor and other health professionals?",
            "Are any tasks handled by support workers, and how are they trained and supervised?",
            "What should I do if I have a concern about the care I am receiving?",
        ],
        "mistakes" => [
            "Not checking a nurse's registration on the national register before care begins.",
            "Expecting a nurse to handle needs that are outside the agreed plan without first discussing it.",
            "Leaving other health professionals out of the loop, which can lead to gaps or repeated advice.",
            "Not raising small changes in health early, when they are easier to address.",
            "Assuming all tasks are done by nurses when some may be delegated to support workers.",
        ],
        "faq" => [
            ["What can a community nurse help with at home?", "Common tasks include wound care, medication management, continence care, monitoring health conditions and helping you understand and follow health advice. The exact tasks depend on your needs and your health plan."],
            ["How can I check that a nurse is properly registered?", "Registered health practitioners appear on the national register kept by AHPRA, which you can search online. It is a quick and reliable way to confirm their registration."],
            ["What is the difference between a nurse and a support worker for health tasks?", "Nurses have clinical training and registration, which allows them to assess health needs and carry out clinical tasks. Support workers may help with certain tasks when they have been trained and are supervised, but they do not replace a nurse's clinical judgment."],
        ],
    ],
    "Complex home modifications" => [
        "day" => "A complex home modification is a building project, not a single visit. It usually begins with an occupational therapist assessing how you use your home and what needs to change, followed by a design and quotes from a builder, and then approval where it is needed. Work on site follows, often involving structural changes such as widening doorways, installing ramps or lifts, or rebuilding a bathroom.\n\nDuring the build it helps to have a single point of contact who keeps everyone informed, and to agree beforehand how you will manage daily life while the work is happening. At the end, the therapist and builder check that the finished work does what it was designed to do and that you are comfortable using it.",
        "who" => "Complex modifications typically involve several professionals working together: an occupational therapist who assesses need, a builder or building designer who plans and carries out the work, and sometimes a certifier, surveyor or architect. If you rent, the landlord's approval is also needed. Look for builders with experience in accessible design, not only general renovation.",
        "fit" => "Home modifications are among the larger and longer-term decisions in a plan, and they interact with other supports such as equipment, accommodation and personal care. Because the work is difficult to reverse, it is worth making sure the design will still suit you as your needs change. Good planning up front can prevent expensive corrections later.",
        "ask" => [
            "What experience do you have with accessible design and with people who have needs like mine?",
            "Will an occupational therapist be involved in the assessment and the final check?",
            "Can you give me a clear written scope, quote and schedule before work starts?",
            "How will you manage the site during the project, and how will you keep me informed?",
            "What approvals or permits are needed, and who is responsible for getting them?",
            "What warranty or guarantee is there on the completed work?",
        ],
        "mistakes" => [
            "Starting design before an occupational therapist has assessed how you actually use your home.",
            "Comparing quotes that do not cover the same work, making the cheapest look better than it is.",
            "Not getting landlord or body corporate permission early when you do not own the home.",
            "Failing to plan how you will manage daily life during the build.",
            "Skipping the final inspection with your therapist, so problems are found only after the builder has left.",
        ],
        "faq" => [
            ["How is a complex home modification different from a minor one?", "It generally means significant structural or specialised work, such as lifts, major bathroom rebuilds or changes to the layout of the house, rather than small fixes like grab rails. Your occupational therapist can explain how your project is classified."],
            ["Can I make modifications to a rented home?", "Often, but the landlord's written approval is normally needed, and there may be conditions about restoring the property or leaving the changes in place. Speak to your landlord and your therapist before anything is designed."],
            ["Who checks the work is done properly?", "The builder is responsible for the quality of the work, and your occupational therapist can check that it meets the design and works for you. Keep records of approvals, plans and inspections."],
        ],
    ],
    "Continence products" => [
        "day" => "Getting the right continence products usually begins with a conversation, often with a continence nurse, a physiotherapist or your doctor, about what you need and what is comfortable and practical. Products are then chosen and supplied, and you learn how to use them, change them and dispose of them with dignity and confidence.\n\nOngoing supply is part of the routine. Some people receive regular deliveries so they do not run out, while others buy what they need as they go. It is worth reviewing your products from time to time, because the right choice can change with your health, your activities and the seasons.",
        "who" => "Continence nurses and physiotherapists with a special interest in continence can assess needs and advise on products and management. Suppliers provide the products and often offer advice, while support workers may help with using them. A good starting point is speaking to your doctor or a continence service about the cause of the problem, since some causes can be treated or improved.",
        "fit" => "Continence products are one part of managing continence, alongside assessment, treatment, exercises, diet and personal care. They work best as part of a plan that also asks whether anything else can help. Regular reviews make sure the products still suit you and help keep skin healthy and comfortable.",
        "ask" => [
            "Can someone assess my needs before I choose products?",
            "Which products are available, and can I try samples to find what works?",
            "How and how often are products delivered, and can I change the order?",
            "Is the delivery packaged discreetly?",
            "Who can I contact if a product is not working for me or I have skin problems?",
            "Are there other treatments or strategies that could reduce how much I rely on products?",
        ],
        "mistakes" => [
            "Choosing products without an assessment, and ending up with the wrong type or size.",
            "Not reviewing products after a change in health, weight or activity.",
            "Overlooking treatments or exercises that might improve the underlying problem.",
            "Running out because there is no regular supply arrangement.",
            "Not raising skin irritation or discomfort early with a nurse or doctor.",
        ],
        "faq" => [
            ["Do I need an assessment to get continence products?", "An assessment helps make sure you get the right type and fit and that any treatable cause has been looked at. Many people find it valuable, and some funding arrangements ask for one."],
            ["Is it embarrassing to talk about continence?", "It is a common health issue, and professionals who work in this area deal with it every day. Being open about what you need helps them find the best solution for you."],
            ["Can products be delivered to my home?", "Many suppliers offer home delivery, often in plain packaging. Ask about delivery options and how orders are changed when your needs change."],
        ],
    ],
];
