<?php
/**
 * Deeper guide content for service posts, batch 5 (companion to content-long-5.php).
 * Same shape as content-deep-1.php. Plain, general guidance only: no prices, no timeframes, no promises about who qualifies.
 */
if (!defined('ABSPATH')) exit;

return [
    "Nursing training for support workers" => [
        "day" => "A nurse who trains support workers starts by looking at the person's health needs and the tasks the workers will do, such as help with medication, catheter care, wound care or managing a health condition. They then teach the workers step by step, usually in the person's own home, using the person's actual equipment and routines.\n\nTraining includes showing, practising and checking. The nurse watches the worker do the task, gives feedback and signs them off only when they are competent. Written instructions are left in the home, and follow-up visits check that the skills have stayed sharp, particularly when a task is rare or the person's health changes.",
        "who" => "The training is delivered by registered nurses, often with experience in community or disability nursing. Support workers who receive the training need to be willing, able and supervised. Ask how the nurse assesses competence, how often the training is refreshed and who is responsible if a new worker joins the team.",
        "fit" => "Nursing training makes it possible for support workers to carry out certain health-related tasks safely, so that the person can be supported by a familiar team. It sits alongside community nursing, medication assistance and personal care. For people with complex health needs, it helps to build up a team of workers who share the same skills.",
        "ask" => [
            "How will the nurse teach and check each task?",
            "Will the training take place in my home with my equipment?",
            "How do you decide when a worker is competent to work alone?",
            "How often is the training refreshed?",
            "What happens when a new worker joins my team?",
            "What are the limits of what support workers can do, and when does a nurse need to step in?",
        ],
        "mistakes" => [
            "Assuming a worker who has done a task elsewhere can safely do it for you without training.",
            "Not training back-up workers, so there are gaps when the usual worker is away.",
            "Letting training lapse, so skills fade.",
            "Not keeping written instructions where workers can see them.",
            "Asking workers to do tasks beyond what they have been trained and cleared for.",
        ],
        "faq" => [
            ["Why does a worker need specific training for my care?", "Every person's needs and equipment are different, and small differences can matter for safety. Training shows the worker how to do the task for you, and confirms they can do it correctly."],
            ["Who is responsible if a trained worker makes a mistake?", "Responsibility is shared across the provider, the worker and the health professionals involved, which is why clear training, supervision and records matter. Ask the provider about its policies."],
            ["Can family members receive the same training?", "Often yes, and it is useful because it means care can continue when workers are not available. Ask the nurse whether family can be included."],
        ],
    ],
    "Occupational therapy" => [
        "day" => "An occupational therapy session starts with a conversation about what you want to be able to do in everyday life, such as dressing, cooking, working, studying or getting around. The therapist may observe you doing a task, test strength and coordination, and look at your home or workplace. They then suggest strategies, equipment, or changes to the environment that make things easier.\n\nSessions can be practical and varied. You may practise a task, try out equipment, learn new ways of doing things or work on skills such as planning and organisation. The therapist also writes reports, for example to support a request for equipment or home modifications, and often coordinates with other professionals and your family.",
        "who" => "Occupational therapists are registered health professionals with university degrees, and they must be registered with AHPRA. Many specialise in areas such as children, mental health, hand therapy, seating and mobility, home modifications or neurological conditions. Ask about experience in the area you need, and whether the therapist can visit your home, school or workplace.",
        "fit" => "Occupational therapy often sits at the centre of a plan, since therapists assess needs and recommend supports such as equipment, modifications, skill-building and daily living help. They work with physiotherapists, speech pathologists, psychologists, support coordinators and support workers, and their reports are frequently used to justify other supports.",
        "ask" => [
            "What experience do you have with my kind of needs or with my age group?",
            "Can you see me at home, school or work, where the tasks actually happen?",
            "How will we set goals and measure progress?",
            "Can you write reports to support equipment or modification requests?",
            "How will you work with my other supports and family?",
            "How often will we review the plan?",
        ],
        "mistakes" => [
            "Waiting until a crisis before seeing a therapist.",
            "Not telling the therapist about your goals, so the sessions focus on the wrong things.",
            "Buying equipment or making changes without a therapist's advice.",
            "Not practising between sessions.",
            "Not checking the therapist's registration and experience.",
        ],
        "faq" => [
            ["What will an occupational therapist actually do with me?", "They help people do the everyday activities that matter to them, by working on skills, changing how tasks are done, recommending equipment and adapting environments."],
            ["Can I book an occupational therapist directly without a referral?", "Often you do not, but requirements depend on how the service is funded. The therapist or their clinic can tell you what they need."],
            ["Can occupational therapists help children?", "Yes. Paediatric occupational therapists help with skills such as handwriting, self-care, play, sensory processing and taking part at school."],
        ],
    ],
    "One-to-one community access" => [
        "day" => "A support worker meets you at the agreed time and goes with you to an activity or place in the community, such as a library, a class, a sports club, a cafe or a park. They help in the ways you need, from getting there and communicating to joining in and managing money. Where you can, you do things yourself, and the worker steps in only as much as needed.\n\nThe activity is chosen by you. Some people work on a particular goal, such as making friends or trying a new hobby, and others simply want to get out and about. A good worker is friendly, respectful and flexible, and helps you build connections that can last beyond the paid support.",
        "who" => "Community access is provided by support workers employed by providers or working independently. The most important thing is a good match, so it is worth meeting the worker first and asking about shared interests, experience and approach. Workers should be screened, trained and insured, and comfortable supporting you in public settings.",
        "fit" => "One-to-one access works with transport, group programs, skill building and social activities. It is often a stepping stone, helping people build confidence in the community. You may want to review the arrangement from time to time to see whether the activities still suit you and whether you are meeting people.",
        "ask" => [
            "Can I meet the worker before we start?",
            "How will you help me choose activities that match my interests?",
            "How will you support me to meet people and make connections?",
            "How do you manage transport and costs for activities?",
            "What happens if the worker is unavailable?",
            "How will we review whether the support is helping me reach my goals?",
        ],
        "mistakes" => [
            "Letting the worker choose the activities instead of you.",
            "Not clarifying who pays for activity costs.",
            "Doing the same thing every week without thinking about your goals.",
            "Not building connections with others in the community.",
            "Not agreeing on what happens if a session is cancelled.",
        ],
        "faq" => [
            ["Can I choose what we do together?", "Yes. Community access is meant to reflect your interests and goals, so you should have the main say in what you do."],
            ["Who pays for the activity, like a class or a meal out?", "Usually you pay for the activity itself, and the support covers the worker's time. Talk to the provider so it is clear before you go."],
            ["Can I have different workers for different activities?", "Sometimes. Some people prefer a worker with a particular skill or interest for a given activity. Ask the provider about options."],
        ],
    ],
    "Overnight support" => [
        "day" => "Overnight support means a worker is present in the home through the night. Depending on your needs, this may be an active shift, where the worker is awake and helping with personal care, repositioning, medication or supervision, or a sleepover shift, where they are available if needed but can sleep between tasks.\n\nA typical night includes a handover in the evening, help getting ready for bed, and checks through the night as agreed. The worker records what happens, responds to any needs or emergencies and helps with the morning routine before handing over to the day team. A quiet, calm approach helps you rest.",
        "who" => "Overnight support is provided by trained support workers, and workers need to be alert, reliable and comfortable working alone at night. Some tasks require additional training, such as managing a seizure or helping with breathing equipment. Ask about the worker's training, how the provider handles emergencies and how workers are supervised overnight.",
        "fit" => "Overnight support connects with personal care, supported living and respite. It offers reassurance to the person and their family and can make it possible to live at home safely. It is worth reviewing the level of support from time to time, since needs may change, and technology such as alarms and sensors can sometimes complement or replace some checks.",
        "ask" => [
            "Will the worker be awake overnight or available on a sleepover basis?",
            "How do you make sure workers are alert and trained for my needs?",
            "What happens in an emergency, and who does the worker call?",
            "How is my privacy respected during the night?",
            "How do you record events overnight and share them with the day team?",
            "How will we review whether the level of support is still right?",
        ],
        "mistakes" => [
            "Not being clear about whether the worker is awake or asleep.",
            "Not training workers in specific night-time tasks such as repositioning or seizure care.",
            "Not having an emergency plan that the worker knows.",
            "Failing to record what happens, so the day team is not informed.",
            "Never reviewing whether overnight support is still needed at the same level.",
        ],
        "faq" => [
            ["What is the difference between active and sleepover overnight support?", "An active shift means the worker stays awake and available throughout the night. A sleepover means the worker is on site and can sleep, but must wake if you need help."],
            ["Can technology reduce the need for overnight support?", "For some people, alarms, sensors or monitoring can help, but they suit some needs better than others. Discuss with your team what is safe for you."],
            ["Will the worker disturb my sleep?", "A good worker keeps checks as quiet as possible, and you can agree on how often they check and how they respond."],
        ],
    ],
    "Personal care" => [
        "day" => "A personal care visit helps with the things you need to get through the day, such as showering, dressing, grooming, toileting, eating or getting in and out of bed. The worker arrives at the agreed time, checks how you are, and helps in the way you prefer. They pay attention to your privacy, your comfort and your dignity throughout.\n\nRoutines matter. Many people like things done a certain way, and a good worker learns your preferences and follows them. They also watch for changes, such as skin problems, pain or shifts in mood, and let you or your family know if they notice anything that needs attention.",
        "who" => "Personal care is delivered by support workers, and some tasks may need extra training. Ask about screening, training and how the provider matches workers to people. Many people feel more comfortable with a worker of a particular gender or background, and it is fine to say so.",
        "fit" => "Personal care sits at the core of many plans and links with nursing, equipment, home modifications and daily living support. The right equipment, such as a shower chair or hoist, makes personal care safer and easier. It also helps to think about what you want to do for yourself, so the support builds on your independence.",
        "ask" => [
            "Can I choose the gender or background of my worker?",
            "How do you make sure my privacy and dignity are protected?",
            "How will the worker learn my routines and preferences?",
            "What training do workers have in safe handling and hygiene?",
            "What happens if my usual worker is away?",
            "How can I raise concerns or make changes?",
        ],
        "mistakes" => [
            "Not telling the worker how you like things done.",
            "Accepting a worker who makes you uncomfortable rather than asking for a change.",
            "Not checking that workers are trained in safe handling.",
            "Not having the right equipment, which puts workers and you at risk.",
            "Not reviewing the routine as your needs change.",
        ],
        "faq" => [
            ["Can I choose who provides my personal care?", "You should have a say, including preferences about gender and approach. Tell the provider at the start and raise it again if something changes."],
            ["What if I am uncomfortable with a worker?", "Speak up. A good provider will listen and arrange a change, and you can contact the NDIS Quality and Safeguards Commission if you have a concern that is not resolved."],
            ["How can I stay independent while receiving personal care?", "Talk to the worker about the parts you can do yourself, and ask for support that fills gaps rather than taking over."],
        ],
    ],
    "Personal care and safety equipment" => [
        "day" => "Personal care and safety equipment includes items such as shower chairs, commodes, bath boards, grab rails, hoists, slings, bed rails, pressure-relieving cushions and alarms. The right choice depends on your body, your home and the tasks you need to do. A therapist usually assesses you and recommends equipment, and a supplier delivers and sets it up.\n\nAfter installation, the therapist or supplier shows you and your support workers how to use it safely. This is especially important for equipment used to move or lift people. Regular checks and servicing keep it in good condition, and reviews confirm it still suits you.",
        "who" => "Occupational therapists and physiotherapists assess and prescribe personal care and safety equipment, and specialist suppliers provide and maintain it. Ask about the therapist's experience with your needs and whether the supplier offers servicing and repairs. Anyone who helps you use the equipment should be trained in it.",
        "fit" => "This equipment works closely with personal care and home modifications. A good match between equipment, home and the way workers help you makes daily routines safer for everyone. It is worth considering how the equipment fits in the space, and whether modifications such as a wider doorway or a roll-in shower would help.",
        "ask" => [
            "Which items would make my routines safer and easier?",
            "Can the equipment be tried before I commit?",
            "Who will teach me and my workers how to use it safely?",
            "How is the equipment serviced and repaired?",
            "Does my home need any changes to make the equipment work?",
            "How will we review whether it still suits me?",
        ],
        "mistakes" => [
            "Buying equipment without an assessment, and finding it does not fit the bathroom or bedroom.",
            "Not training workers on the equipment.",
            "Skipping regular checks of lifting and moving equipment.",
            "Using equipment in ways it was not designed for.",
            "Not replacing worn parts such as slings.",
        ],
        "faq" => [
            ["Why does lifting equipment need regular servicing?", "It carries people's weight, so faults can cause serious injury. Regular checks by a qualified person keep it safe."],
            ["Can a support worker set up the equipment?", "Simple items may be easy, but more complex equipment should be set up by the supplier or therapist, with training for anyone who will use it."],
            ["What if the equipment no longer suits me?", "Contact your therapist for a review. Needs change, and there may be a better option."],
        ],
    ],
    "Personal training" => [
        "day" => "A personal training session begins with a warm-up and moves through exercises chosen to suit your body and goals, such as strength, balance, endurance or flexibility. The trainer demonstrates each movement, watches your technique, adjusts equipment and encourages you. Sessions can take place in a gym, at home, outdoors or in a pool.\n\nA good trainer for someone with a disability is experienced in adapting exercises, understands your health and pays attention to how you feel. They set goals with you, track progress and change the program as you get stronger. The aim is to help you build a habit of regular activity that you enjoy.",
        "who" => "Personal trainers hold fitness qualifications and are usually registered with a fitness industry body. For people with medical conditions or complex needs, an exercise physiologist or physiotherapist may be a better starting point, and a trainer can then continue the program. Ask about experience with disability and how the trainer works with your health professionals.",
        "fit" => "Personal training complements therapy and exercise physiology. A physiotherapist or exercise physiologist may design a program, and a trainer may help you carry it out. It also links with community access, since a gym or pool can be a place to meet others. Checking with your doctor first is sensible if you have a health condition.",
        "ask" => [
            "What qualifications do you hold, and are you registered with a fitness body?",
            "Do you have experience training people with disability?",
            "How will you adapt exercises to my body and my goals?",
            "Will you work with my doctor or therapist?",
            "Where will sessions be held, and is it accessible?",
            "How will we track progress?",
        ],
        "mistakes" => [
            "Starting a program without checking it is safe for your health.",
            "Choosing a trainer with no experience of your needs.",
            "Pushing too hard and risking injury.",
            "Not having a plan for continuing exercise between sessions.",
            "Ignoring pain or unusual symptoms.",
        ],
        "faq" => [
            ["When is an exercise physiologist a better choice than a personal trainer?", "An exercise physiologist has clinical training and works with medical conditions, while a personal trainer focuses on fitness. For complex health needs, an exercise physiologist is often the right person."],
            ["Can personal training be done at home?", "Yes, many trainers offer home sessions, which can suit people who find it hard to get to a gym."],
            ["Do I need my doctor's approval?", "It is a good idea if you have a health condition. A trainer or therapist can tell you what information they need."],
        ],
    ],
    "Physiotherapy" => [
        "day" => "A physiotherapy appointment starts with questions about your problem, your health and what you want to achieve. The physiotherapist examines how you move, checks strength, balance and pain, and explains what they find. Treatment may include exercises, hands-on techniques, advice on posture and movement, and the use of equipment.\n\nYou are usually given a home program to practise between visits, because regular practice is a big part of progress. Follow-up sessions check how you are doing, adjust the program and add new challenges. For long-term conditions, physiotherapy focuses on maintaining function, preventing problems and managing symptoms.",
        "who" => "Physiotherapists are registered health professionals with university degrees and must be registered with AHPRA. Many have additional training in areas such as neurology, paediatrics, sports, respiratory care or women's health. Ask about experience with your condition, and whether the therapist works at a clinic, in your home or at a community setting.",
        "fit" => "Physiotherapy works alongside occupational therapy, exercise physiology, medical care and equipment prescription. For example, a physiotherapist may advise on the right walking aid and train you to use it. It also links with home modifications and community access, since movement affects almost every part of daily life.",
        "ask" => [
            "What experience do you have with my condition?",
            "What will the treatment involve, and what are the goals?",
            "Will you give me a home program, and how will you check it?",
            "Can you visit me at home or another place where I need to move?",
            "How will you work with my doctor and other therapists?",
            "How will we measure progress?",
        ],
        "mistakes" => [
            "Stopping exercises as soon as the pain eases.",
            "Not doing the home program.",
            "Not telling the physiotherapist about other health conditions or medications.",
            "Expecting quick results for a long-standing problem.",
            "Not asking how to prevent the problem returning.",
        ],
        "faq" => [
            ["Can I book a physiotherapist directly without a referral?", "In many cases you do not, but requirements depend on how the service is funded. The clinic can tell you what is needed."],
            ["Can physiotherapy help with long-term conditions?", "Yes. It can help maintain movement, prevent complications and manage symptoms for many long-term conditions, including neurological and respiratory conditions."],
            ["What should I wear to a physiotherapy appointment?", "Comfortable clothes that let you move and allow the therapist to see the area being treated. If you are unsure, ask the clinic when you book."],
        ],
    ],
    "Plan management" => [
        "day" => "A plan manager takes care of the financial side of your plan so you do not have to. When you receive a service, the provider sends their invoice to the plan manager, who checks it against your plan and pays it. You see what is being spent through regular statements or an online portal.\n\nThey also help you understand your budget, track what is left and flag when you are on track or off track. If you receive a bill you are unsure about, the plan manager can check it. Many also help with agreements, quotes and choosing providers, though the level of help varies.",
        "who" => "Plan managers are usually businesses or individuals who specialise in managing plan funds. They need to be registered to manage funds for people using this option. Ask how they communicate, how quickly they pay invoices, what they can help with beyond payment, and how they keep your information secure.",
        "fit" => "Plan management works with support coordination and other supports. A support coordinator helps you find and arrange services, and a plan manager handles the payments and budgets. Together they let you focus on what you want to do, not the paperwork. Understanding who does what avoids confusion.",
        "ask" => [
            "How will I see what has been spent and what is left?",
            "How quickly are invoices paid, and how do you handle disputes?",
            "What help do you give with budgets and agreements?",
            "How do you keep my information secure?",
            "How can I contact you, and how quickly do you reply?",
            "What happens if I want to change plan manager?",
        ],
        "mistakes" => [
            "Not checking statements regularly.",
            "Assuming the plan manager will find you providers, which is normally the coordinator's role.",
            "Not asking how invoices are checked.",
            "Overlooking how a plan manager communicates and how often.",
            "Staying with a plan manager who is unresponsive without considering a change.",
        ],
        "faq" => [
            ["What is the difference between a plan manager and a support coordinator?", "A plan manager handles payments and budget tracking. A support coordinator helps you find, organise and manage your supports. Some people use both."],
            ["Can I choose any provider if I have a plan manager?", "Plan management typically gives you the freedom to use registered or unregistered providers, subject to the rules of your plan. Check details with your plan manager."],
            ["What if I think an invoice is wrong?", "Tell your plan manager, who can query it with the provider before paying. Keep records of what was agreed and what was delivered."],
        ],
    ],
    "Podiatry" => [
        "day" => "A podiatry appointment focuses on the health of your feet and lower legs. The podiatrist asks about problems such as pain, nails, skin, wounds, footwear and how you walk. They examine your feet, check circulation and sensation, and treat problems such as corns, calluses, ingrown nails or infections.\n\nThey also give advice on footwear, foot care and exercises, and may prescribe orthotics or other devices. For people with conditions that affect the feet, such as diabetes, regular checks are especially important to catch problems early.",
        "who" => "Podiatrists are registered health professionals with university degrees and must be registered with AHPRA. Some specialise in areas such as diabetes, sports, children or wound care. Ask about experience with your condition and whether they make home visits if getting to a clinic is difficult.",
        "fit" => "Podiatry connects with mobility, physiotherapy, diabetes care and personal care. Healthy feet make it easier to move, take part and stay independent. It is worth working with your doctor and other professionals if you have a condition that affects your circulation or sensation.",
        "ask" => [
            "Do you have experience with my condition, such as diabetes?",
            "Can you visit me at home if I cannot get to the clinic?",
            "How often should I have my feet checked?",
            "What footwear would you recommend for me?",
            "Do you make orthotics or refer to someone who does?",
            "What should I look out for between appointments?",
        ],
        "mistakes" => [
            "Ignoring foot pain or small wounds until they become serious.",
            "Cutting nails or treating corns yourself when you have a condition that affects your feet.",
            "Wearing shoes that do not fit or support you.",
            "Not having regular checks when you have diabetes or poor circulation.",
            "Not telling the podiatrist about changes in feeling or colour.",
        ],
        "faq" => [
            ["Why are foot checks important for people with diabetes?", "Diabetes can reduce feeling and circulation in the feet, so injuries may go unnoticed and heal slowly. Regular checks help find problems early."],
            ["Can a podiatrist visit me at home?", "Some do, especially for people who find travelling difficult. Ask when you book."],
            ["What should I do about a wound on my foot?", "Have it looked at promptly by a health professional, especially if you have diabetes or poor circulation, because foot wounds can become serious quickly."],
        ],
    ],
    "Psychology" => [
        "day" => "A psychology session is a confidential conversation with a registered psychologist. In the first session they ask about what has brought you in, your history and what you would like to change. They explain how they work, how sessions run and what the limits of confidentiality are.\n\nLater sessions may use a structured approach, such as cognitive behavioural therapy, or a more exploratory style, depending on your needs. The psychologist may suggest exercises to practise between sessions and review how things are going. For some people, psychology involves assessment, such as testing for learning or developmental difficulties.",
        "who" => "Psychologists are registered with AHPRA and complete extended university training. Some are clinical psychologists with additional training in mental health conditions, and others specialise in areas such as children, neuropsychology or behaviour support. Ask about experience with your concern and whether they work with people with disability.",
        "fit" => "Psychology can work alongside medical care, counselling, therapy and support coordination. If you are living with a mental health condition or a disability that affects your wellbeing, psychology can help build coping skills and manage symptoms. Psychologists may work with your doctor, so it helps to keep them informed about medications and other treatment.",
        "ask" => [
            "Are you registered, and what is your experience with my concerns?",
            "What approach do you use, and how do we decide whether it is helping?",
            "Do you have experience working with people with disability?",
            "How does confidentiality work, and when might you share information?",
            "Can sessions be by phone or video?",
            "What happens if I need more urgent help between sessions?",
        ],
        "mistakes" => [
            "Expecting instant results when change takes time.",
            "Not doing the exercises between sessions.",
            "Staying with a psychologist who is not a good fit.",
            "Not telling the psychologist about medications or other treatment.",
            "Waiting until a crisis to seek help.",
        ],
        "faq" => [
            ["What is the difference between a psychologist and a psychiatrist?", "A psychologist is trained in assessing and treating mental health through therapy, while a psychiatrist is a medical doctor who can diagnose and prescribe medication. They often work together."],
            ["Can I book a psychologist directly without a referral?", "Often you do not, but some funding arrangements need a doctor's referral. The psychologist's practice can tell you."],
            ["Is what I say kept confidential?", "Yes, with limited exceptions such as serious risk of harm. The psychologist will explain these at the start."],
        ],
    ],
];
